### ISSUE TITLE
[Enhancement] 버전 자동 감지 기능 개선

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#100]
상당히 impressive 합니다 (짝짝)

다만 사용자들을 github 링크로 이동시키면 혼란스러울 것 같습니다.
추후에 deployment 할 버전이 최종적으로 정해지면 그 apk 를 제가 구글 드라이브 폴더에 두고
파일 자체의 링크를 추출할 예정입니다.

"업데이트" 버튼을 눌렀을 때 그 링크로 이동시켜주면 좋을 것 같습니다.
나중에 알려드릴게요~

**Comment by KimYC1223** [comment]
감사합니다 (짝짝)

확인했습니다
