### ISSUE TITLE
[BUG] 앱에서 기록 추가하다가 중단하는 상황

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#101]
[하루보기] 화면에서 직접 아이콘을 추가하려다가 중단하는 상황에서 발생하는 버그입니다.

아이콘을 추가하다가 중단할 수 있는 기존 방법은 아래 2가지 입니다.
1. 아이콘을 다시 클릭
2. 화면의 어두워진 부분 아무곳을 클릭

1번대로 중단하면 버그가 없고, 2번대로 중단하면 아래 화면처럼 아이콘 위에 'x' 표시가 유지됩니다.
물, 음료, 오줌, 똥 모두 동일한 버그 발생합니다.

2번이 불가능하도록 수정이 필요할 것 같습니다.

![Screenshot_20210902-164100_MOA GARDEN](https://user-images.githubusercontent.com/65483592/131804726-44fc543a-2a25-4ce3-9e17-b080e512fdc1.jpg)

**Comment by KimYC1223** [comment]
- #106 와 통합

> 이봉신 박사님 코멘트
>
> 오줌 기록을 Edit 을 하려다가 화면의 아무 곳이나 눌러서 edit 모드를 해제했는데,
> 그때 다른 timeline bar 를 눌렀더니 오줌 기록이 시간 변경 되어버림

**Comment by KimYC1223** [comment]
- #104 와 통합

> 이봉신 박사님과 비슷한 유형의 버그입니다.
> 이봉신 박사님 말씀대로 실제로는 edit 모드를 나가지 않기 때문인지 edit모드에서 나간 뒤 상단 아이콘을 클릭해 앱을 추가하는 것이 불가합니다.
>
> 모든 아이콘에서 발생합니다.
>
> 똥 아이콘 edit 모드에서 나가는 경우의 수는 3가지인데,1, 3번만 버그가 발생하고 2번은 발생하지 않습니다.
>
> edit할 기록을 고르지 않고 '취소' 버튼을 누른다.
> 대변 모양을 고르지 않고 '취소' 버튼을 누른다.
> '시간변경' 선택한 뒤 어두운 부분을 선택하여 중단

**Comment by KimYC1223** [comment]
# 문제 해결

![ezgif-3-c2c95e4f8eaa](https://user-images.githubusercontent.com/40852277/132098509-00c43973-6e98-4db6-8fc4-0ec25ef50fd9.gif)

![ezgif-3-500bd3e7b209](https://user-images.githubusercontent.com/40852277/132098650-31d668cc-5c4a-4c2c-af43-4defcab01d9c.gif)

## 개발 사항

- 인터페이스 개선 ( 클릭 : Edit / 꾹 누르기 : Edit, Delete )
- 편집 모드에서 나갈 시 버튼이 눌리지 않는 현상 개선
- 추가 / 제거 / 편집 모드에서 나갈 때 아이콘이 원래대로 돌아오도록 수정
