### ISSUE TITLE
[BUG] edit 모드 나간 뒤 아이콘 추가 불가

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#104]
이봉신 박사님과 비슷한 유형의 버그입니다.
이봉신 박사님 말씀대로 실제로는 edit 모드를 나가지 않기 때문인지 edit모드에서 나간 뒤 상단 아이콘을 클릭해 앱을 추가하는 것이 불가합니다.

모든 아이콘에서 발생합니다.

똥 아이콘 edit 모드에서 나가는 경우의 수는 3가지인데,1, 3번만 버그가 발생하고 2번은 발생하지 않습니다.
1. edit할 기록을 고르지 않고 '취소' 버튼을 누른다.
2. 대변 모양을 고르지 않고 '취소' 버튼을 누른다.
3. '시간변경' 선택한 뒤 어두운 부분을 선택하여 중단

**Comment by KimYC1223** [comment]
비슷한 느낌의 버그이므로,

#101 에서 통합하여 관리합니다.
