### ISSUE TITLE
[Enhancement] 하루보기 화면 interaction 방식 변경

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#105]
이봉신 박사님 코멘트
"Tap & hold 하면 바로 Edit 모드로 이동
Tap 만 하면 삭제/edit 메뉴 팝업이 뜨도록"

**Comment by KimYC1223** [comment]
비슷한 느낌의 버그이므로,

#101 에서 통합하여 관리합니다.

**Comment by junhyungmoon** [comment]
제가 다시 보니 메모를 잘못 썼었는데 알아서 잘 해주셨네요ㅎㅎ 혹시 몰라서 수정해뒀습니다.

다만, 이봉신박사님의 의도는 Tap 만 하면 Edit 메뉴가 뜨는게 아니라 Edit 모드로 바로 이동하는걸 말씀하신 것입니다.
혹시 이렇게 수정하는게 burden 이 크거나 뭔가 꼬여서 에러가날 소지가 높은지 생각해보시고 의견주세요

**Comment by 2sukhyunlee** [comment]
1.0.17 버전에서 interaction이 유지될지 변경될지 미리 말씀 해주시면 어떤 버전으로 매뉴얼을 수정할지 참고하도록 하겠습니다!

**Comment by junhyungmoon** [comment]
@Yeohyun00 
여현학생도 숙현학생과 동일하게 참고해야겠네요~

**Comment by Yeohyun00** [comment]
> @Yeohyun00
> 여현학생도 숙현학생과 동일하게 참고해야겠네요~

넵넵 확인했습니다

**Comment by KimYC1223** [comment]
# 문제 해결

말씀 하신대로 반영했습니다.

## 수정 전

![수정전](https://user-images.githubusercontent.com/40852277/132374609-3130d2c2-d829-4e30-8a7e-7fa392f2af70.gif)

꾹 누르면 ```수정 버튼```과 ```삭제 버튼```이, 한번 클릭하면 ```수정 버튼``` 이 나타남

## 수정 후

![ezgif-2-d9702c3531a4](https://user-images.githubusercontent.com/40852277/132374778-325ee810-07da-4b7c-bfac-0ee7d3281433.gif)

꾹 누르면 ```수정 버튼```과 ```삭제 버튼```이, 한번 클릭하면 바로 ```수정 모드```로 변경
