### ISSUE TITLE
[BUG] 하루보기 edit 모드 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#106]
이봉신 박사님 코멘트

오줌 기록을 Edit 을 하려다가 화면의 아무 곳이나 눌러서 edit 모드를 해제했는데,
그때 다른 timeline bar 를 눌렀더니 오줌 기록이 시간 변경 되어버림

**Comment by KimYC1223** [comment]
비슷한 느낌의 버그이므로, 

#101 에서 통합하여 관리합니다.
