### ISSUE TITLE
[Enhancement] 모아밴드로 기록한 똥 이름 수정

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#107]
아까 이봉신 박사님께서 말씀하신 것처럼, 
모아밴드로 기록한 똥을 수정하면 '잘 모름(사실 선택하지 않았다는 의미)'에서 '잘 모름(실제로 모양을 모름)'으로 되니까 충분히 혼동스러울 것 같습니다.
모아밴드로 기록한 똥 이름을 '잘 모름'에서 '아직 모양 선택 안함'으로 바꾸면 좋을 것 같습니다.

**Comment by KimYC1223** [comment]
너무 길 것 같은데... 알겠습니다

**Comment by Yeohyun00** [comment]
> 너무 길 것 같은데... 알겠습니다

다시 보니 '아직'은 빼도 될 것 같습니다 ㅎㅎ

**Comment by KimYC1223** [comment]
# 문제 해결

![image](https://user-images.githubusercontent.com/40852277/132096810-7f30c1d9-376c-4f1b-9daf-49cfab7656c3.png)
