### ISSUE TITLE
[BUG] 음료 종류/양 변경 취소 불가

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#109]
음료 기록의 종류와 양을 변경할 수 있는 UI에서 
'취소' 버튼을 눌러도 이전 화면으로 되돌아가지 않습니다.

**Comment by junhyungmoon** [comment]
오 그러네요.. 새로 추가할때 UI의 "취소"는 되는데, 기록을 수정할때 UI에서 "시간변경"은 되고 "취소"는 안됩니다.

**Comment by KimYC1223** [comment]
# 문제 해결

- #105 이슈를 해결하면서

제가 실수로 코드를 한 줄 지워버렸던게 원인이었습니다.

지금은 문제 해결했습니다.

추가로, **음료 수정하기 UI에서 용량 스크롤바가 정상적으로 동작하지 않던 버그**와

**음료 선택하기 UI, 똥 선택하기 UI에서 취소를 누를경우, 추가하기 버튼이 눌리지 않던 버그**를 발견하여 수정하였습니다.
