### ISSUE TITLE
[Question] 몽몽이 state 확인

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#110]
가장 최근에 영찬학생이 어떤 이슈에서 몽몽이 state diagram 을 그려서 공유했던것 같은데
이슈가 너무 많아지니 못찾겠네요...

그걸 원노트 페이지에 업로드 해두면 어떨까요. 과거 버전의 diagram 은 굳이 남길 필요 없겠습니다.

아무튼 질문은, 오늘 꽃이 없으면 몽몽이가 시들시들했던것 같은데, 혹시 저게 맞나요?
아직 시간이 오전이라 안 시들시들해진건가요?

![Screenshot_20210906-101040_MOA GARDEN](https://user-images.githubusercontent.com/8017454/132147620-345870eb-07fb-4f1d-949a-84754c2d8e97.jpg)

**Comment by Yeohyun00** [comment]
몽몽이는 "어제"를 기준으로 판단하고 출현하기 때문에, 오늘 기록을 안하거나 꽃을 안 피운 상태여도 밝은 몽몽이가 나올 수 있습니다.
위 상황에서는, 어제 앱 접속/기록/꽃 피우기까지 완벽하게 한 상태이기 때문에 권장 몽몽이가 출현했습니다.

아래는 가장 최신 버전의 state diagram입니다. 원노트에도 업데이트해놓겠습니다!
![몽몽이 state diagram_최신](https://user-images.githubusercontent.com/77374615/132157605-f6701d23-e469-4b0c-85cb-3045c4727883.png)

**Comment by junhyungmoon** [comment]
넵 답변 감사합니다. 원노트는 업데이트 해 주시고, App에는 문제가 없다는 것이니 close 하겠습니다!
