### ISSUE TITLE
[BUG] 정원가기 줌인/아웃 시, 디버그 팝업 출현

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#112]
정원가기에서 줌인 줌아웃을 하면 저 팝업이 수시로 출현합니다.
![Screenshot_20210908-101609_MOA GARDEN](https://user-images.githubusercontent.com/8017454/132430218-db1c0513-541e-4c0d-bb18-2ed78f51c6d3.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

- #87 이슈를 해결하려다

작업하는데 거슬려서 구름 이펙트를 잠시 꺼둔걸 잊어버리고 릴리즈해서 그렇습니다.

바로 수정하도록 하겠습니다.
