### ISSUE TITLE
[BUG] 하루보기 음료수정 후 오류현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#113]
영상1: 태블릿에서 추가한 음료 기록(1시)을 수정한 후에 상단의 + 버튼 4개 모두 먹통 현상
https://drive.google.com/file/d/1X46XX1EngyB5ksbEc3IUKmdZscMqhNVa/view?usp=sharing

영상2: 위 상황에서 물 기록(2시)를 누르고 타임라인 bar를 몇개 눌렀더니 물 기록이 삭제되어버림
https://drive.google.com/file/d/1fBL9OC7qknupq_T3YKnt-gmRqw77DPMN/view?usp=sharing

**Comment by junhyungmoon** [comment]
참고로 수정을 하려고 팝업창으로 들어가서 실제 수정하지 않고 취소하고 나오면 위 현상이 나타나지 않습니다. (시간변경 시도한 뒤 취소하거나 팝업 내에서 취소하는 것 모두 동일)

**Comment by KimYC1223** [comment]
# 일부 해결

영상 1번의 문제는 해결했습니다. 그러나 영상 2번의 경우 문제 파악중입니다.

**Comment by KimYC1223** [comment]
다시 확인해도 2번의 문제는 발생하지 않았습니다.

일단 1번 까지 해결하고 1.0.18 배포합니다.

새 버전에서도 며칠 더 지켜보고, 다시 발생하지 않으면 close 하겠습니다.
