### ISSUE TITLE
[Question] 앞으로 남은 날들의 영역 오픈 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#114]
시작하면 오늘 말고 길이 전부 구름에 가려져 있었던 것 같은데 갑자기 달라진 것 같아서요~
한 4~5일째 정도 되는 길까지 다 보이는 것 같습니다.

![Screenshot_20210908-115550_MOA GARDEN](https://user-images.githubusercontent.com/8017454/132439119-4a952ae7-35c9-4156-aacf-c4d4f77a5f4e.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

앗... 이것도 #87 에서 문제를 해결하려다... 편집에 걸리적거리는 구름을 치우려고 지웠던게 문제였습니다.

새벽에 작업하느랴고 정신이 없었던것 같습니다.

복구 완료했습니다.
