### ISSUE TITLE
[Discuss] 튜토리얼 용 데이터 세팅 관련 질문입니다.

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#116]
환자와 부모에게 튜토리얼을 할 때, 연구팀 전용 세트에 "이상적인 시나리오의 4주치 데이터"를 담아가서 보여주자고 이박사님, 최교수님과 결정하였습니다.

이렇게 하려면 2가지가 필요합니다.
1) 27일치 데이터 생성 (28일이 아닌 이유는 아래에 설명) - 연구원들 가내수공업
2) 위에서 생성한 데이터를 환자가 내원하는 날에 맞추어서 매번 일자를 조정

예를 들면 우리가 8월 1일부터 8월 27일에 해당하는 데이터를 생성했다고 가정하겠습니다.
그 후에 환자가 9월 10일에 온다고 하면 그 전날에 9월 10일이 "28일째"가 되도록 생성한 데이터의 날짜를 모두 맞게 shift 시키는 것입니다. (8월 1일 -> 8월 14일, 8월 2일 -> 8월 15일, 8월 3일 -> 8월 16일 ... 이런 방식)
28일째를 비워둔 이유는 튜토리얼 하면서 아동과 부모에게 연구팀의 세트를 사용하게 하기 위함입니다. 
본인들 세트를 사용하게 하면 사용 첫날부터 dummy data 가 들어갈 수 밖에 없어서요... 
향후에 이어서 오는 다음 환자들의 내원 일자에 맞게 계속 날짜를 shift 합니다.

이 shift 하는 것을 서버 상에서 명령어로 가능할지 영찬학생 의견이 궁금합니다.

**Comment by KimYC1223** [comment]
더미 데이터를 만드는 것은 정말 순수 가내수공업이 필요합니다만,

데이터 쉬프트는 서버에서 해결 할 수 있을 것 같습니다.

- #108 이슈 기능 추가하면서

같이 추가하겠습니다.
