### ISSUE TITLE
[BUG] 내일의 땅이 미리보이는 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#117]
내일(화요일) 땅이 구름 위로 미리 보입니다.
제가 3차례 앱 완전 종료 후 재접속을 해 봐도 동일합니다.

![Screenshot_20210913-113623_MOA GARDEN](https://user-images.githubusercontent.com/8017454/133015663-0397c027-0a7c-43df-9b0d-4f2f6f9d2e04.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

![image](https://user-images.githubusercontent.com/40852277/133627269-695f6321-e581-412b-8788-40e2c51b07b8.png)

garden_log가 미래에 있을 경우, 이런 버그가 생길 수 있습니다.

(DB 직접 수정이 아닌) 정상적인 방법으로는 현재 시간보다 미래의 garden_log를 만들 수 없을텐데...

어떻게 이런 일이 생긴건진 잘 모르겠지만, 오늘 날짜보다 미래의 garden_log는 그리지 않도록 하는 기능을 추가하여

해당 이슈를 해결하였습니다.

[```HomeHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/MainPage/HomeHandler.cs)의 ```public void InitGardenSpot()``` 함수 중에서,

타겟 시간과 현재 시간을 비교해서 현재 시간보다 미래일 경우,

garden_log에 상관 없이 ```nulll``` 값을 할당하여, 그림을 그리지 않도록 하였습니다.

```C#
public void InitGardenSpot() {
    // ... 중략 ...
    foreach (GardenSpotHandler spot in Spots) {
            
        DataHandler.GardenLog inputData = null;
        for(int i = 0; i < logs.Length; i++) {
            if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(
                new TimeHandler.DateTimeStamp(logs[i].timestamp), inputDate)
                == 0) {
                inputData = logs[i];
                break;
            }
        }

        //=========================================================================================
        // 이 부분 추가
        if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(inputDate, TimeHandler.CurrentTime) > 0) 
            inputData = null;
        //=========================================================================================
        spot.InitSpot(inputData,inputDate);
        inputDate = inputDate+1;
    }
    // ... 후략 ...
}
```

잘 동작하는 모습입니다.

![image](https://user-images.githubusercontent.com/40852277/133626444-0b7777b4-26f2-4b6e-a650-021ddd3580e6.png)
