### ISSUE TITLE
[BUG] 물 모두주기 클릭시 버그 발생 

### ISSUE THREAD

**Issue by mminkyongkim** [FluidTrack/MOA_garden#118]
하루보기에서 물, 오줌, 똥 클릭후 물 모두주기 버튼을 누르니 버그가 발생했다는 화면이 떴습니다.
그리고 그 후 버그 정보 전송 후, 화면이 얼고 화면이 움직여지지 않았습니다. 
[bug.pdf](https://github.com/FluidTrack/MOA_garden/files/7176077/bug.pdf)

**Comment by KimYC1223** [comment]
# 중간 정리

@mminkyongkim 와 통화 후 상황 전달

가끔 꽃 키우기 화면의 아이콘을 모두 사용했지만 "모두주기"버튼이 비활성화가 **안되는**경우가 발생함

모두주기에서 Animation의 play time을 계산 하는 수식에서 아이콘 개수로 나누는 과정이 있기 때문에,

0으로 나누는 값이 ```NaN```으로 처리되어 발생하는 문제인듯

**Comment by KimYC1223** [comment]
# 문제 해결

- #94 이슈를 해결하기 위해

[작업했던 내용](https://github.com/FluidTrack/MOA_garden/issues/94#issuecomment-909959824)때문에 발생한 버그입니다.

## #94 [[BUG] 물 모두주기 오류 본문 내용](https://github.com/FluidTrack/MOA_garden/issues/94#issuecomment-909959824) 중
> 따라서, `private bool wateringAllButtonClicked`라는 변수를 추가하고,
> 
> 모두주기 버튼을 누를 때엔 값을 `true`로 바꿔주는 기능을 추가했습니다.
> 
> 그리고 문제가 되었던 `IEnumerator ReDrawSpot()`에서는
> 
> `wateringAllButtonClicked`값이 `false`일 때에만
> 
> `WateringAllButton`의 `interactable`값을 변경하도록 하였습니다.
> 
> ```cs
> IEnumerator ReDrawSpot() {
>     // 중략
>     if(!wateringAllButtonClicked)
>         WateringAllButton.interactable = waterIconCount > 0;
>     // 후략
> }
> ```

이 과정에서 **물 모두주기**가 아니라 일반적으로 물을 줄 때에는 ```wateringAllButtonClicked```가 ```false``` 이므로

해당 코드가 동작하지 않았습니다.

...라는 것은 제 의도대로 동작한 것이었습니다만,

적어도 일반적 물 주기 방법으로 물을 주고 난 다음엔

화면에 남아있는 물 아이콘 개수가 0인지는 확인을 했어야 했던 것입니다.

따라서 다음과 같이 수정했습니다.

```C#
IEnumerator ReDrawSpot() {
    if(!wateringAllButtonClicked)
        WateringAllButton.interactable = waterIconCount > 0;
    if(waterIconCount == 0)
        WateringAllButton.interactable = false;
}
```

이제는 잘 동작합니다. 감사합니다.
