### ISSUE TITLE
[Calendar] 8주 기록 모음 페이지 구현

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#13]
# 8주 기록 모음 페이지 구현

![image](https://user-images.githubusercontent.com/40852277/108940348-8b597600-7696-11eb-9c0e-5b4bb6a6903b.png)

8주 기록 모음 페이지 High-Fi 디자인이 완성됨!

@KimYC1223 가 Unity에 임포트 하는 작업을 완료함

@dannyboy0103 는 그동안 작업했던 ```CalendarHandler.cs```를 적절히 수정하여

실제로 동작하는 8주 기록 모음 화면을 만들면 됨.

디자인에 사용된 소스는 [```Asset/HighFi/Calendar```](https://github.com/FluidTrack/MOA_garden/tree/master/Assets/HighFi/Calendar)에 저장됨.

---

### 1. Water Log Fetcher 구현 ( ✅ 완료됨 )

- 1-1. 사용자 id에 기반하여 데이터베이스에서 물 기록 가져오기

### 2. Pee Log Fetcher 구현 ( ✅ 완료됨 )

- 2-1. 사용자 id에 기반하여 데이터베이스에서 오줌 기록 가져오기

### 3. Poo Log Fetcher 구현

- 3-1. 사용자 id에 기반하여 데이터베이스에서 똥 기록 가져오기

### 4. Set Date Range 구현

- 4-1. 테이블의 1행 1열의 날짜에 따라 테이블 위쪽의 요일 레전드 변경되도록 하기
- 4-2. 테이블의 1행 1열의 월/일에 따라 테이블 전체 (28개)에 그에 맞는 날짜 맵핑하기

> **📌 참고**
> 
> 해당하는 날짜의 요일은 [```TimeHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/TimeHandler.cs)에 선언된 ```DateTimeStamp```클래스의 ```Date``` 필드로 확인이 가능함.
>
> ```C#
>    public class DateTimeStamp {
>        // 중략
>        static public string[] DateList = { "월요일","화요일","수요일","목요일",
>                                            "금요일","토요일","일요일"};
>        public int Date;  // 월요일 : 0 ~ 일요일 : 6
>    }
>```
>
> 예를 들어, 이렇게 확인 가능
> 
>```C#
>    DateTimeStamp temp = new DateTimeStamp(System.DateTime.Now);
>    Debug.Log(temp.Date);     // 0 ~ 6
>    Debug.Log(TimeHandler.DateTimeStamp.DateList[temp.Date]);  // 월요일 ~ 일요일
>```

### 5. Week Select Button 구현

- 5-1. 테이블 중앙의 버튼을 통해 보여지는 주차가 1주씩 변경되어야 함 (Up/Down 버튼)
- 5-2. 변경된 주차에 맞게 화면도 갱신되어야 함
- 5-3. 1주차에서 Up 버튼 동작과, 8주차에서 Down 버튼 동작은 아무 일도 일어나지 않도록 예외처리
- 5-4. 게임 오브젝트가 OnEnable될 때, 보여지는 주차는 1~4주차부터 시작해야 함

### 6. Draw Water Gauge 구현

- 6-1. ```Week1WaterGauge1``` 부터 ```Week4WaterGauge7```까지 표에 그리기
- 6-2. 테이블의 날짜에 맞는 데이터로 그릴 것
- 6-3. 소스는 [```Asset/HighFi/Calendar```](https://github.com/FluidTrack/MOA_garden/tree/master/Assets/HighFi/Calendar)에서 확인 가능함
- 6-4. ```Water_Circle01.png``` ~ ```water_Circle05.png```, ```Water_CircleEmpty.png```를 사용해서 표현 할 것.

![image](https://user-images.githubusercontent.com/40852277/108942561-90b8bf80-769a-11eb-8447-94a85adbf3ac.png)

- 6-5. 마신 횟수가 원 안에 ```Text```로 표시되게 할 것.
- 6-6. Sprite는 다음과 같은 범위로 설정 할 것.

| 0회 | 1회 이상 2회 이하 | 3회 이상 5회 이하 |  6회 이상 7회 이하 | 8회 이상 9회 이하 | 10회 이상 |
|:---:|:---:|:---:|:---:|:---:|:---:|
| CircleEmpty | Circle01 | Circle02 | Circle03 | Circle04 | Circle05 |

- 6-7. 아직 다가오지 않은 날은 ```Water_CircleEmpty.png```를 그릴 것
- 6-8. **아직 다가오지 않은 날**과 **0잔 마신 날** 의 차이는 텍스트에 숫자가 있는지 없는지 차이임

### 7. Draw Pee Gauge 구현

- 7-1. ```Week1PeeGauge1``` 부터 ```Week4PeeGauge7```까지 표에 그리기
- 7-2. 테이블의 날짜에 맞는 데이터로 그릴 것
- 7-3. 소스는 [```Asset/HighFi/Calendar```](https://github.com/FluidTrack/MOA_garden/tree/master/Assets/HighFi/Calendar)에서 확인 가능함
- 7-4. ```Pee_Level0.png``` ~ ```Pee_Level4.png```를 사용해서 표현 할 것.

![image](https://user-images.githubusercontent.com/40852277/108943336-f35e8b00-769b-11eb-9852-56ed812968d1.png)

- 7-5. 소변 횟수가 원 안에 ```Text```로 표시되게 할 것.
- 7-6. Sprite는 다음과 같은 범위로 설정 할 것.

| 0회 | 1회 이상 3회 이하 | 4회 이상 7회 이하 |  8회 이상 20회 이하 | 21회 이상 |
|:---:|:---:|:---:|:---:|:---:|
| Level0 | Level1 | Level2 | Level3 | Level4 |

- 7-7. 아직 다가오지 않은 날은 ```Pee_Level0.png```를 그릴 것
- 7-8. **아직 다가오지 않은 날**과 **0잔 마신 날** 의 차이는 텍스트에 숫자가 있는지 없는지 차이임

### 8. Draw Poo Gague 구현

- 8-1. ```Week1PooMark1``` 부터 ```Week4PooMark7```까지 표에 그리기
- 8-2. 테이블의 날짜에 맞는 데이터로 그릴 것
- 8-3. 소스는 [```Asset/HighFi/Calendar```](https://github.com/FluidTrack/MOA_garden/tree/master/Assets/HighFi/Calendar)에서 확인 가능함
- 8-4. ```Poo_good.png```, ```Poo_none.png```를 사용해서 표현 할 것.

![image](https://user-images.githubusercontent.com/40852277/108943336-f35e8b00-769b-11eb-9852-56ed812968d1.png)

- 8-5. **좋은 똥이 있는 날**이란, poo log에서 ```type```이 **3**또는 **4**인 타입의 데이터가 하나라도 존재하는 날임
- 8-6. Sprite는 다음과 같은 기준으로 설정 할 것.

| 좋은 똥이 있는 날 | 좋은 똥이 있는 날이 아닌날 |
|:---:|:---:|
| Poo_good.png | Poo_none.png |

- 8-7. 아직 다가오지 않은 날은 ```Poo_none.png```를 그릴 것
- 8-8. 따라서, **아직 다가오지 않은 날**과 **좋은 똥이 있는 날이 아닌날**의 차이가 없음

---

@dannyboy0103 완료 후 git push하고, 본 Issue에 정리할 것.

## 📅 Deadline

2021.02.27 토요일 23:00

시간이 더 필요하면 연락 할 것

**Comment by dannyboy0103** [comment]
### **8주 기록 모음 페이지 구현 상황 보고**

-  To-Do List에서 현재 Water Log Fetcher, Pee Log Fetcher, Poo Log Fetcher, Set Date Range, Week Select Button, Poo Gauge는 전부 이상 없이 구현했습니다.

-  다만 Pee Gauge와 Water Gauge에서 아직 다가오지 않은 날과 0잔 마신 날을 텍스트의 숫자 유무로 차이점을 두어야하지만 아직 그 부분은 구현하지 못했습니다. 빠른 시일 내에 구현하여 다시 보고드리겠습니다.

-  [Server] 데이터 Fetch 문제 Issue에서도 언급된 내용과 연결되는 내용 같은데 Water, Pee와 같은 다른 logs에서도 특정 상황 (데이터가 비어있는 상황 등)에서 에러가 발생하는 것 같습니다. 이 부분에 대해서도 추가적으로 더 확인해보고 다시 보고드리겠습니다.

**Comment by junhyungmoon** [comment]
"6. Draw Water Gauge 구현" 이 부분에 오해가 있는 것 같습니다.
- 목표 달성 실패: 마신 횟수에 비례하여 하늘색 원 크기 조정 (1~9 모두 다름)
- 목표 달성 성공: 실선 동그라미에 파란색이 꽉찬 아이콘 동일 적용 (횟수에 무관함)

**Comment by KimYC1223** [comment]
# 버그 수정

## 데이터 없을 때

> ### **8주 기록 모음 페이지 구현 상황 보고**
> * [Server] 데이터 Fetch 문제 Issue에서도 언급된 내용과 연결되는 내용 같은데 Water, Pee와 같은 다른 logs에서도 특정 상황 (데이터가 비어있는 상황 등)에서 에러가 발생하는 것 같습니다. 이 부분에 대해서도 추가적으로 더 확인해보고 다시 보고드리겠습니다.

```C#
    public int CountPee(DataHandler.PeeLog[] logs, string Date) {
        int Count = 0;
        int Current = 0;

        // log 길이가 0이면 count할 대상이 없으므로 0 리턴
        if (logs.Length == 0) return 0;      // 이 부분 추가
        TimeHandler.DateTimeStamp CurrentLogTime = new TimeHandler.DateTimeStamp(logs[Current].timestamp);
        while (CurrentLogTime.ToDateString() != Date) {
            // ... 후략 ...
```

같은 동작을 ```CountPee```, ```CountWater```, ```FindGoodPooDay``` 함수에 추가

데이터가 없을 때에도 정상적으로 동작 하는 것을 확인

---

## 다가오지 않은 날 표시

>다만 Pee Gauge와 Water Gauge에서 아직 다가오지 않은 날과 0잔 마신 날을 텍스트의 숫자 유무로 차이점을 두어야하지만 아직 그 부분은 구현하지 못했습니다. 빠른 시일 내에 구현하여 다시 보고드리겠습니다.

```MyDates[i]```를 순회하며 미래가 됐을 경우 GaugeText를 중지

```C#
    public void ChangePeeGaugeText(DataHandler.PeeLog[] logs, Text[] texts) {
        for (int i = 0; i < texts.Length; i++) {
            // 이 if문 추가
            if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(
                new TimeHandler.DateTimeStamp(MyDates[i]), TimeHandler.CalendarCanvasTime) > 0)
                return;
            texts[i].text = CountPee(logs, MyDates[i]).ToString();
        }
    }
```

같은 내용을 ```ChangePeeGaugeText```, ```ChangeWaterGaugeText```에 적용

정상 동작 확인

---

## 바운더리 수정

> "6. Draw Water Gauge 구현" 이 부분에 오해가 있는 것 같습니다.
> * 목표 달성 실패: 마신 횟수에 비례하여 하늘색 원 크기 조정 (1~9 모두 다름)
> * 목표 달성 성공: 실선 동그라미에 파란색이 꽉찬 아이콘 동일 적용 (횟수에 무관함)

10개로 세분화

```C#
    public void ChangeWaterGaugeImage(DataHandler.WaterLog[] logs, Image[] beforeImages, Sprite[] afterImages, int[] boundary) {
        for (int i = 0; i < beforeImages.Length; i++) {
            if (CountWater(logs, MyDates[i]) <= boundary[0]) {
                beforeImages[i].sprite = afterImages[0];
            } else if (CountWater(logs, MyDates[i]) <= boundary[1]) {
                beforeImages[i].sprite = afterImages[1];
            } else if (CountWater(logs, MyDates[i]) <= boundary[2]) {
                beforeImages[i].sprite = afterImages[2];
            } else if (CountWater(logs, MyDates[i]) <= boundary[3]) {
                beforeImages[i].sprite = afterImages[3];
            } else if (CountWater(logs, MyDates[i]) <= boundary[4]) {
                beforeImages[i].sprite = afterImages[4];
            } else if (CountWater(logs, MyDates[i]) <= boundary[5]) {
                beforeImages[i].sprite = afterImages[5];
            } else if (CountWater(logs, MyDates[i]) <= boundary[6]) {
                beforeImages[i].sprite = afterImages[6];
            } else if (CountWater(logs, MyDates[i]) <= boundary[7]) {
                beforeImages[i].sprite = afterImages[7];
            } else if (CountWater(logs, MyDates[i]) <= boundary[8]) {
                beforeImages[i].sprite = afterImages[8];
            } else if (CountWater(logs, MyDates[i]) <= boundary[9]) {
                beforeImages[i].sprite = afterImages[9];
            } else {
                beforeImages[i].sprite = afterImages[10];
            }
        }
    }
```

<br><br>
