### ISSUE TITLE
[Server] 데이터 Fetch 문제

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#14]
# 데이터 Fetch할 때 문제 발생

![image](https://user-images.githubusercontent.com/40852277/109227946-77cc1d80-7804-11eb-951f-36187c1533d8.png)

미션 현황페이지에서 로드 할 때 프로그램이 멈춤

## 📢 에러 내용

> NullReferenceException: Object reference not set to an instance of an object
> MissionCanvasHandler+<FetchCheck_Garden>d__23.MoveNext () (at Assets/Scripts/CanvasHandler/MissionCanvasHandler.cs:102)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <d1422b3fc93746018c92eda852993b93>:0)

## 발생 원인

문제가 생기는 위치는 [```MissionCanvasHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/MissionCanvasHandler.cs)의 102번줄

```C#
        foreach(DataHandler.GardenLog log in DataHandler.Garden_logs.GardenLogs) {
            try {
                int index = dateList[log.timestamp.Split(' ')[0]];
                flowers[index] = log.flower;
            } catch(System.Exception e) { e.ToString(); }
        }
```

여기서 데이터를 가져올 때, ```DataHandler.Garden_logs.GardenLogs```이 **비어있기 때문으로 추정 됨!**

#12 이슈를 적용 할 때, Database가 초기화 되면서, Fetch할 때 비어있는 값이 들어오기 때문임..

지금까지는 DB가 비어 있던 적이 없어서 잘 몰랐던 것으로 추정

**Comment by junhyungmoon** [comment]
제가 안 보는 것 같지만 메일로 오는거 다 보고 있습니다...ㅋㅋ
이 에러를 보니 저희가 디자인을 입히는 것도 중요하지만 기능 테스트는 필요 없는지 궁금하네요.
혹은 개발팀이 원노트나 다른 자료의 내용을 다른 의도로 생각해서 개발하고 있는지 등도 
언젠가는 한번 확인이 필요할 것 같아요.
예전부터 한 얘기를 반복하는 이유가 꼭 하자는 의미는 아닌데,
걱정이 되어서 주기적으로 말하는 것입니다.
잊지만 마시고 개발팀이 적절히 스케줄을 생각해서 해 주시면 되겠습니다.

**Comment by KimYC1223** [comment]
> 제가 안 보는 것 같지만 메일로 오는거 다 보고 있습니다...ㅋㅋ
> 이 에러를 보니 저희가 디자인을 입히는 것도 중요하지만 기능 테스트는 필요 없는지 궁금하네요.
> 혹은 개발팀이 원노트나 다른 자료의 내용을 다른 의도로 생각해서 개발하고 있는지 등도
> 언젠가는 한번 확인이 필요할 것 같아요.
> 예전부터 한 얘기를 반복하는 이유가 꼭 하자는 의미는 아닌데,
> 걱정이 되어서 주기적으로 말하는 것입니다.
> 잊지만 마시고 개발팀이 적절히 스케줄을 생각해서 해 주시면 되겠습니다.

보고... 계셨군요 😆

안그래도 오늘 아침 회의에서 위와 같은 버그가 생기는 것을 보고

말씀하신 실제 기능 테스트는 반드시 필요하다고 생각했습니다.

일정 정해서 말씀드리겠습니다.

**Comment by KimYC1223** [comment]
# 문제 해결

[```DataHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/DataHandler.cs)의 417 줄을 수정

```DataHandler.Garden_logs.GardenLog```가 ```null``이기 때문에, 배열로 취급할 수 없었음

만약 데이터 parsing에 실패(데이터가 존재하지 않는 경우)한다면, 길이가 0인 배열을 리턴 하도록 수정

## 수정 전

```C#
static public IEnumerator ReadGardenLogs(int target_id) {
        yield return 0;

        UnityWebRequest request = new UnityWebRequest();
        string url = "read_garden_logs";
        url += "?id=" + target_id;

        using (request = UnityWebRequest.Get(DataHandler.ServerAddress + url)) {
            yield return request.SendWebRequest();
            if (request.isNetworkError)
                QuitApplication();
            else {
                try {
                    string jsonString = request.downloadHandler.text;
                    Garden_logs = JsonParsing<GardenLogsJson>(jsonString);
                    User_isGardenDataLoaded = true;
                } catch (System.Exception e) {
                    Debug.Log(e.ToString());
                    Garden_logs = new GardenLogsJson();
                    Garden_logs.GardenLogs = null;    // <--------------- 이 부분이 null로 되어 있었음
                    User_isGardenDataLoaded = true;
                }
            }
        }
    }
```

## 수정 후

```C#
static public IEnumerator ReadGardenLogs(int target_id) {
        yield return 0;

        UnityWebRequest request = new UnityWebRequest();
        string url = "read_garden_logs";
        url += "?id=" + target_id;

        using (request = UnityWebRequest.Get(DataHandler.ServerAddress + url)) {
            yield return request.SendWebRequest();
            if (request.isNetworkError)
                QuitApplication();
            else {
                try {
                    string jsonString = request.downloadHandler.text;
                    Garden_logs = JsonParsing<GardenLogsJson>(jsonString);
                    User_isGardenDataLoaded = true;
                } catch (System.Exception e) {
                    Debug.Log(e.ToString());
                    Garden_logs = new GardenLogsJson();
                    Garden_logs.GardenLogs = new GardenLog[0];     // <--------------- 수정함
                    User_isGardenDataLoaded = true;
                }
            }
        }
    }
```
