### ISSUE TITLE
[FLOWERS] 꽃 키우기 페이지 간단하게 구현

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#15]
# 🌼 꽃 키우기 페이지 구현

---

## 🎯 첫번째 미션

- Flower Page에서 특정 날짜의 Garden log의 데이터 가져오기

> 📌 Garden Log Class
> 
> | field | description |
> |:---:|:---:|
> | log_id | 로그 고유의 아이디 |
> | id | 해당 로그 주인의 아이디. ```users``` 테이블의 id임 |
> | timestamp | 로그가 생성된 시기 (YYYY-MM-DD hh:mm:ss) |
> | flower | 핀 꽃의 개수 |
> | item_0 | 사용하지 않은 물의 개수 |
> | item_1 | 미정 (2021.03.17 기준) |
> | item_2 | 미정 (2021.03.17 기준) |
> | item_3 | 미정 (2021.03.17 기준) |
> | item_4 | 미정 (2021.03.17 기준) |

- 로그가 없거나 비어있을 때도 처리하는 코드 작성하기
- 가져온 데이터에서 ```timestamp```,```flower```,```item_0``` 값을 ```Debug.Log()```함수로 출력하기

---

## ✔️ Hint

- ```TimeHandler.DateTimeStamp``` 클래스를 통해 String을 Class로 변경
- ```CmpDateTimeStamp(DateTimeStamp a, DateTimeStamp b)```함수를 통해 ```DateTimeStamp```클래스간 대소구분 가능
> 📌 ```CmpDateTimeStamp(DateTimeStamp a, DateTimeStamp b)``` 함수
> 
> **두 DateTimeStamp의 YYYY-MM-DD를 가지고 시간 순서를 비교하는 함수**
> ( YYYY-MM-DD hh:mm:ss)기준으로 비교할 경우```CmpDateTimeStampDetail```함수 사용
>
> - a가 b보다 미래일 때 : return 1
> - a와 b가 같은 시간     : retrurn 0
> - a와 b보다 과거일 때 : return -1

- 데이터를 가져 올 때는 ```StartCoroutine()```함수 사용
- ```Garden_logs```를 가져오기 전에 반드시 ```DataHandler.ReadGardenLogs()```메소드 사용

---

## 📅 Dead line

**2021-03-20 오후 3시**까지
시간이 더 필요할 경우 연락 할 것

**Comment by KimYC1223** [comment]
# 참고사항

제가 아까 알려드린 코드에 살짝 문제가 있었습니다.
[```FlowerPageHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/HSY_Script/FlowerPageHandler.cs)에서,

```C#
    public void OnEnable() {
        StartCoroutine(DataHandler.ReadGardenLogs(DataHandler.User_id));
        StartCoroutine(dataLoadCheck());
        targetDate = new TimeHandler.DateTimeStamp(TargetDateString);
    }
```

```DataHandler.ReadGardenLogs```코루틴을 호출 할 때, 파라미터로 ```DataHandler.User_id```넘겨서

해당 태블릿을 사용하는 유저에 맞는 로그를 가져온다고 했는데

일단 해당 부분 파라미터에 ```DataHandler.User_id```대신 그냥 숫자 ```1```로 하도록 하겠습니다.

일단 [```FlowerPageHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/HSY_Script/FlowerPageHandler.cs) 의 11번째 줄을 다음과 같이 바꿔주세요

```C#
    public void OnEnable() {
        StartCoroutine(DataHandler.ReadGardenLogs(1));    // 이 부분을 1로
        StartCoroutine(dataLoadCheck());
        targetDate = new TimeHandler.DateTimeStamp(TargetDateString);
    }
```

감사합니다.

**Comment by sayiovme** [comment]
안녕하세요.
코드 작성 완료 후 push 하였습니다.
확인 부탁드립니다.

감사합니다.
