### ISSUE TITLE
[Calendar] Water Log Handler 구현

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#2]
# Calendar Water Log Handler 구현

Assignees : @sayiovme 

Text Field에 입력된 값에 따라 아래 Sprite가 변경됨
```Sprites/CircleChart/``` 참고

0 이하일 때 : 0.png
1 일 때 : 1.png
2 일 때 : 2.png
3 일 때 : 3.png
4 일 때 : 4.png
5 이상일 때 : 5.png

**Comment by KimYC1223** [comment]
@sayiovme 

잘 진행되고 있는지 중간 보고 부탁드립니다!

**Comment by sayiovme** [comment]
> @sayiovme
> 
> 잘 진행되고 있는지 중간 보고 부탁드립니다!

지금 유튜브 영상도 참고하여 이것저것 만져보고 있는 중입니다. (늦게 시작해서 송구합니다. ㅜㅜ)
MainManager를 만지는 것이 낯설긴 한데 오늘까지는 완성할 수 있을 것 같습니다.
혹 궁금한 점 있으면 카카오톡으로 여쭙겠습니다!

**Comment by KimYC1223** [comment]
넵 알겠습니다.
처음 하시는 거라 어려우실텐데 고생이 많으십니다

git push하는 방법은 Issue #5 에 올려놓았으니 참고하시고,
push후 본 issue에 코멘트 작성바랍니다

**Comment by sayiovme** [comment]
안녕하세요. 
늦어져서 정말로 죄송합니다. ㅜㅜ
방금 push 완료하였습니다.  

+
처음에는 Button을 눌러야만 이미지가 바뀌는 것으로 구현했다가,
이것이 불편한 것 같아 입력이 완료되면 자동으로 이미지가 바뀌는 방식으로 구현했습니다.
따라서, Button이 필요 없는 관계로 ButtonHandler의 코드를 작성하지 않았습니다.
혹 필요하면 말씀해주세요.
(첫 구현 과정에서 버튼 사용법은 숙지하였습니다!) 

친절한 강습 감사합니다!

**Comment by KimYC1223** [comment]
# 코드 리뷰

지금 코드 확인해봤는데 잘하셨습니다.

버튼의 동작 뿐아니라 InputField 컴포넌트의 속성까지 잘 이해하셨다니 다행입니다.

다만 코드 단계에서 몇 가지 주의하거나 유의해야 하는 사항을 말씀드리도록 하겠습니다.

---

일단, [CalendarWaterLogHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/HSY_Script/CalendarWaterLogHandler.cs)에서,

```C#
    public void HSY_input()
    {
        water = int.Parse(i.text);
        change();
    }
```

또한, 지금은 아래 사진처럼 Input Field 오브젝트의

```InputField```컴포넌트 ```Content Type```속성이 Integer Number이기 때문에

![image](https://user-images.githubusercontent.com/40852277/104862216-206d9e80-5976-11eb-81c1-e27f14b0a857.png)

문제가 없이 파싱이 되겠지만, ```Int.Parse(string str)```메소드 같은 경우

익셉션을 리턴하기 매우 쉬우므로, (예 : "abc"를 int로 파싱하는 경우)

사용할 때 항상 try-catch문을 사용해주시길 바랍니다.

```C#
    public void HSY_input()
    {
        try {
            water = int.Parse(i.text);
        } catch (System.Exception e) {
            Debug.Log(e.ToString());
            water = 0;
            i.text = "0";
        }
        change();
    }
```

---

또한, ```public void change()```함수도, 

```C#
    public void change()
    {
        Debug.Log(water);
        switch (water)
        {
            case 0:
                testimage.sprite = water_0;
                break;

            // 중략

            case 5:
                testimage.sprite = water_5;
                break;
            default:
                testimage.sprite = water_5;
                break;
        }
    }
```

코드에 따르면, 값이 -1이하 일 때 5.png가 출력됩니다.

switch문 밖에 따로 처리를 해 주어서 음수일 경우에도 처리를 해 두면 좋겠습니다.

물론 당연히 처음부터 음수를 넣지 않아주면 되지만,

다른 사람이 보기에는 그 사실을 모르기 때문입니다.

---

마지막으로,

```C#
    public InputField i;
    public Text t;
```

변수의 이름이 모호합니다. 앞으로의 co-work에서 이는 주의해주셔야 합니다!

앞으로 Calendar Water Log Handler는 선영님만 작업하시고 선영님만 보실 예정이기 때문에

로컬 변수나 private 변수의 이름은 어찌 작성하든 상관 없습니다만

public 변수나 함수는 작명에 신경을 써 주셔야 합니다.

너무 구체적일 필요는 없고, ```public Sprite water_5;``` 이 정도면 충분히 이해 됩니다.

---

전반적인 Unity 사용 방법은 잘 이해하신 것 같습니다.

디테일한 코딩 스타일("어느 부분에서는 if else를 쓸 지, switch를 쓸지" 와 같은)까지 말씀드리고 싶은 생각은 없습니다.

다만 사용자에게 실제로 배포가 되는 어플리케이션인 만큼, 예외처리는 확실할수록 좋고,

3명이서 개발을 하게 된 지금, co-work 스킬은 필수라고 생각합니다.

<br>

다음 목표는 최대한 오전 중으로 업로드 해 드리도록 하겠습니다.

수고하셨습니다.

**Comment by KimYC1223** [comment]
# DataHandler와 연동

이제 본격적으로 FluidTrack 서버와 연동하여 데이터를 그리는 작업을 해 보겠습니다.

일단 지금 현재 FluidTrack App과 서버의 통신은 다음과 같이 이루어집니다.

![image](https://user-images.githubusercontent.com/40852277/104873978-1f983500-5995-11eb-800c-c9e2e8dcf3e5.png)

DB에 저장된 데이터는 구축해 놓은 Rest API 서버를 통해 [CRUD](https://www.google.com/search?q=CRUD&oq=CRUD&aqs=chrome..69i57.2219j0j4&sourceid=chrome&ie=UTF-8) 할 수 있으며,

App에서는 DataHandler라는 클래스가 서버와 통신을 담당합니다.

DataHandler는 App이 실행되면 사용자의 ID에 맞는 데이터들(정원기록, 물 섭취, 오줌, 똥 로그 등등)을

서버로부터 Fetch하고 List형태(Array형태)로 저장합니다.

물 로그로 예를 들면, 현재 사용자의 물 로그 기록은

DataHandler의 ```Water_logs```에 ```WaterLogs```라는 이름으로 저장되어 있습니다.

```C#
    // DataHandler.cs 중
    internal static WaterLogsJson  Water_logs;

    public class WaterLogsJson {
        public WaterLog[] WaterLogs;
    }

    public class WaterLog {
        public int log_id;
        public int id;
        public string timestamp;
        public int type;
    }
```

```WaterLog``` 클래스에는 로그의 고유 아이디인 ```log_id```,

로그의 소유자를 나타내는 ```id```, 로그가 생성된 시각인 ```timestamp```,

그리고 물/음료를 나타내는 ```type```이 있습니다.

---

@sayiovme 님이 처음 하신 예제에서는 ```InputField```로부터 그 값을 받아오고 업데이트를 하였지만,

이제는 DataHandler에서 직접 데이터를 받아와서 그림을 그려보는 작업을 진행하겠습니다.

다만, 바로 실제 데이터를 쓰면 어려울 수 있으니, 지금은 가상의 데이터를 사용해서 진행해보도록 하겠습니다.

다음은 제가 ```DataHandler.cs```에 임시로 만든 함수입니다.

```C#
    static public WaterLog[] GetTempWaterData() {
        WaterLog[] returnArray = new WaterLog[40];
        //중략
        return returnArray;
    }
```

```GetTempWaterData``` 함수는 호출하면 모아밴드에서 물 버튼을 누른 40회의 기록을 리턴하여 줍니다.

static함수이므로, 인스턴스를 호출하지 않고 class상에서 바로 호출이 가능합니다.

다시 말하면, 스크립트 상 어디에서든

```C#
    DataHandler.WaterLog[] logs = DataHandler.GetTempWaterData();
```

라는 코드로 40회의 임시 로그를 얻어 올 수 있다는 뜻입니다.

40회의 기록은 2021년 01월 01일부터 2021년 01월 07일까지의 Timestamp를 가지고 있습니다.

이해가 잘 안되신다면 [DataHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/DataHandler.cs)의 ```GetTempWaterData``` 구현 부분을 참고하세요

<br><br>

이제 선영님이 하실 일은, 이 7일치 데이터를 아래처럼 표시하는 일 입니다.

![image](https://user-images.githubusercontent.com/40852277/104875392-88cd7780-5998-11eb-9449-7fb5363397a9.png)

이제 Input Field는 지울 것이고, Image도 7개, 그 밑에 Text도 7개가 생겼으니

Scene도 많이 수정을 해야 할 것입니다.

아래와 같은 일을 하시면 됩니다.

- 지난번 피드백 반영하기
- Scene을 위 사진과 같이 수정하기. 7개의 Image와 바로 밑에 7개의 Text를 추가 할 것.
- DataHandler의 임시 데이터에 따라 7개의 Image 데이터가 바뀔 것
- DataHandler의 임시 데이터에 따라 7개의 Text 데이터가 바뀔 것 (n0~n6)
- n0가 위치한 곳이 1월1일, n6이 위치한 곳이 1월 7일이 되도록 할 것
- Editor의 Play버튼을 눌러 앱을 실행시키자 마자 값이 변하도록 할 것. ([유니티 Life cycle](https://docs.unity3d.com/kr/530/Manual/ExecutionOrder.html)참조)

앱이 시작되자마자 값이 바뀌어야 하므로,

```Start()```, ```OnEnable()```, ```Awake()``` 중 하나를 활용하길 바랍니다.

이번 프로젝트 **데드라인**은 **목요일(21.01.21) 아침 회의(AM 11:00)전** 까지로 하겠습니다.

이해가 안되거나 문제가 있다면, 언제든 알려주시길 바랍니다.

**Comment by junhyungmoon** [comment]
눈에 보이는 것이 있어서 짚고 넘어갑니다.
1) Water handler 속에서 type 으로 물/음료를 구분한다고 하는데, 그러면 fluid handler 로 이름을 바꿔주세요.
2) 그보다 음료는 물과 달리 종류와 양 정보도 기입하게 됩니다(원노트 내용 참고). 어쩌면 handler 를 분리하는 것이 맞지 않을까 싶은데 참고해 주세요.
3) 제가 코드를 다 보진 않았는데 HSY 는 선영학생 이름으로 추정되네요. 코딩할 때 좋지 않은 작명 방식이니 영찬, 동현 학생 모두 이렇게 작명하지 않도록 처음부터 이름을 잘 정리하기 바랍니다. 앞으로 작명할 것은 물론이고 이미 작명한 변수 및 파일들까지 모두 유의하여 작명 부탁합니다.

**Comment by KimYC1223** [comment]
> 눈에 보이는 것이 있어서 짚고 넘어갑니다.
> 
> 1. Water handler 속에서 type 으로 물/음료를 구분한다고 하는데, 그러면 fluid handler 로 이름을 바꿔주세요.
> 2. 그보다 음료는 물과 달리 종류와 양 정보도 기입하게 됩니다(원노트 내용 참고). 어쩌면 handler 를 분리하는 것이 맞지 않을까 싶은데 참고해 주세요.
> 3. 제가 코드를 다 보진 않았는데 HSY 는 선영학생 이름으로 추정되네요. 코딩할 때 좋지 않은 작명 방식이니 영찬, 동현 학생 모두 이렇게 작명하지 않도록 처음부터 이름을 잘 정리하기 바랍니다. 앞으로 작명할 것은 물론이고 이미 작명한 변수 및 파일들까지 모두 유의하여 작명 부탁합니다.

오 좋은 지적 감사합니다

1. 말씀 하신대로 Fluid Handler가 더 적당한 듯 싶네요. 그걸로 변경하도록 하겠습니다
2. 일단 선영님이 작업하시는 부분은 8주차 기록 모음 페이지의 Water Log Handler입니다. 현재 페이지에서는 음료를 고려하지 않는 것으로, 기록 확인 페이지와 같이 음료와 물을 분리해서 생각해야 하는 페이지에서는 Handler를 분리할 생각입니다.
3. 동의합니다. 좋은 작명은 협업의 큰 도움이 됩니다.

@sayiovme  @dannyboy0103 모두 다음을 참고해서 작업해주세요!

- Class이름의 첫 글자는 **대문자**로 시작하고 띄어쓰기 대신 **첫 글자**를  대문자로 합니다. **명사 형태**로 작성합니다. 해당 클래스가 어떤 역할을 하는지 잘 알 수 있도록 합니다.(Ex. ProtocolManager)
- Private 변수 이름의 첫 글자는 **소문자**로 시작하고 띄어쓰기 대신 **첫 글자**를 대문자로 합니다. **명사 형태**로 작성합니다. (Ex. currentValue)
- Public 변수 이름의 첫 글자는 **대문자**로 시작하고 띄어쓰기 대신 **첫 글자**를 대문자로 합니다. **명사 형태**로 작성합니다. (Ex. NextIndex)
- Private/Public 함수 이름의 첫 글자는 **대문자**로 시작하고 띄어쓰기 대신 **첫 글자를** 대문자로 합니다. **동사 형태**로 작성합니다. (Ex. OpenWindow() )
- 예외로 Trigger되어 실행 되는 함수(Ex. 버튼을 눌렀을 때)는 On + V +ed 형태로 작성합니다.  (Ex. OnButtonClicked() )
- enum이나 상수값은 **모두 대문자**로 하고, 띄어쓰기 대신 _를 사용합니다. (Ex. PI , LOG_MAX, WINDOW_ALERT)

물론 지키지 않는다고 해서 큰 일이 나는 것은 아니며,

실수 하시거나 빠트린 부분이 있다고 하여도 제가 코드 리뷰하는 과정에서 수정 해 드릴 터이니

너무 부담을 느끼시지 않으셔도 됩니다.

다만 @junhyungmoon 님 말씀이 맞고 습관을 들여 놓는다고 해도 절대 손해보는 나쁜 습관은 아니니

조금만 더 신경쓴다는 느낌으로 작업해주시면 되겠습니다.

감사합니다.

<br><br>

**Comment by sayiovme** [comment]
> > 눈에 보이는 것이 있어서 짚고 넘어갑니다.
> > 
> > 1. Water handler 속에서 type 으로 물/음료를 구분한다고 하는데, 그러면 fluid handler 로 이름을 바꿔주세요.
> > 2. 그보다 음료는 물과 달리 종류와 양 정보도 기입하게 됩니다(원노트 내용 참고). 어쩌면 handler 를 분리하는 것이 맞지 않을까 싶은데 참고해 주세요.
> > 3. 제가 코드를 다 보진 않았는데 HSY 는 선영학생 이름으로 추정되네요. 코딩할 때 좋지 않은 작명 방식이니 영찬, 동현 학생 모두 이렇게 작명하지 않도록 처음부터 이름을 잘 정리하기 바랍니다. 앞으로 작명할 것은 물론이고 이미 작명한 변수 및 파일들까지 모두 유의하여 작명 부탁합니다.
> 
> 오 좋은 지적 감사합니다
> 
> 1. 말씀 하신대로 Fluid Handler가 더 적당한 듯 싶네요. 그걸로 변경하도록 하겠습니다
> 2. 일단 선영님이 작업하시는 부분은 8주차 기록 모음 페이지의 Water Log Handler입니다. 현재 페이지에서는 음료를 고려하지 않는 것으로, 기록 확인 페이지와 같이 음료와 물을 분리해서 생각해야 하는 페이지에서는 Handler를 분리할 생각입니다.
> 3. 동의합니다. 좋은 작명은 협업의 큰 도움이 됩니다.
> 
> @sayiovme @dannyboy0103 모두 다음을 참고해서 작업해주세요!
> 
> * Class이름의 첫 글자는 **대문자**로 시작하고 띄어쓰기 대신 **첫 글자**를  대문자로 합니다. **명사 형태**로 작성합니다. 해당 클래스가 어떤 역할을 하는지 잘 알 수 있도록 합니다.(Ex. ProtocolManager)
> * Private 변수 이름의 첫 글자는 **소문자**로 시작하고 띄어쓰기 대신 **첫 글자**를 대문자로 합니다. **명사 형태**로 작성합니다. (Ex. currentValue)
> * Public 변수 이름의 첫 글자는 **대문자**로 시작하고 띄어쓰기 대신 **첫 글자**를 대문자로 합니다. **명사 형태**로 작성합니다. (Ex. NextIndex)
> * Private/Public 함수 이름의 첫 글자는 **대문자**로 시작하고 띄어쓰기 대신 **첫 글자를** 대문자로 합니다. **동사 형태**로 작성합니다. (Ex. OpenWindow() )
> * 예외로 Trigger되어 실행 되는 함수(Ex. 버튼을 눌렀을 때)는 On + V +ed 형태로 작성합니다.  (Ex. OnButtonClicked() )
> * enum이나 상수값은 **모두 대문자**로 하고, 띄어쓰기 대신 _를 사용합니다. (Ex. PI , LOG_MAX, WINDOW_ALERT)
> 
> 물론 지키지 않는다고 해서 큰 일이 나는 것은 아니며,
> 
> 실수 하시거나 빠트린 부분이 있다고 하여도 제가 코드 리뷰하는 과정에서 수정 해 드릴 터이니
> 
> 너무 부담을 느끼시지 않으셔도 됩니다.
> 
> 다만 @junhyungmoon 님 말씀이 맞고 습관을 들여 놓는다고 해도 절대 손해보는 나쁜 습관은 아니니
> 
> 조금만 더 신경쓴다는 느낌으로 작업해주시면 되겠습니다.
> 
> 감사합니다.


안녕하세요!
영찬님의 리뷰 및 미션, 그리고 준형님의 코멘트 전부 잘 읽어보았습니다.
목요일 오전 11시 회의 전까지, 이 스레드를 참고하여 작업해가겠습니다.

감사합니다!
황선영 드림

**Comment by KimYC1223** [comment]
@sayiovme

오늘 회의가 매우 길었는데, 선영님 작업이 더욱 바빠지실 것 같아서

개발 업무는 시간을 더 드리는 것이 나을 것 같다고 생각했습니다.

목요일 오전 11시 회의 전에서 금요일 오후 9시로 변경하겠습니다.

혹시 시간 더 필요하시면 말씀 해 주시길 바랍니다

**Comment by sayiovme** [comment]
> @sayiovme
> 
> 오늘 회의가 매우 길었는데, 선영님 작업이 더욱 바빠지실 것 같아서
> 
> 개발 업무는 시간을 더 드리는 것이 나을 것 같다고 생각했습니다.
> 
> 목요일 오전 11시 회의 전에서 금요일 오후 9시로 변경하겠습니다.
> 
> 혹시 시간 더 필요하시면 말씀 해 주시길 바랍니다



> # DataHandler와 연동
> 이제 본격적으로 FluidTrack 서버와 연동하여 데이터를 그리는 작업을 해 보겠습니다.
> 
> 일단 지금 현재 FluidTrack App과 서버의 통신은 다음과 같이 이루어집니다.
> 
> ![image](https://user-images.githubusercontent.com/40852277/104873978-1f983500-5995-11eb-800c-c9e2e8dcf3e5.png)
> 
> DB에 저장된 데이터는 구축해 놓은 Rest API 서버를 통해 [CRUD](https://www.google.com/search?q=CRUD&oq=CRUD&aqs=chrome..69i57.2219j0j4&sourceid=chrome&ie=UTF-8) 할 수 있으며,
> 
> App에서는 DataHandler라는 클래스가 서버와 통신을 담당합니다.
> 
> DataHandler는 App이 실행되면 사용자의 ID에 맞는 데이터들(정원기록, 물 섭취, 오줌, 똥 로그 등등)을
> 
> 서버로부터 Fetch하고 List형태(Array형태)로 저장합니다.
> 
> 물 로그로 예를 들면, 현재 사용자의 물 로그 기록은
> 
> DataHandler의 `Water_logs`에 `WaterLogs`라는 이름으로 저장되어 있습니다.
> 
> ```cs
>     // DataHandler.cs 중
>     internal static WaterLogsJson  Water_logs;
> 
>     public class WaterLogsJson {
>         public WaterLog[] WaterLogs;
>     }
> 
>     public class WaterLog {
>         public int log_id;
>         public int id;
>         public string timestamp;
>         public int type;
>     }
> ```
> 
> `WaterLog` 클래스에는 로그의 고유 아이디인 `log_id`,
> 
> 로그의 소유자를 나타내는 `id`, 로그가 생성된 시각인 `timestamp`,
> 
> 그리고 물/음료를 나타내는 `type`이 있습니다.
> 
> @sayiovme 님이 처음 하신 예제에서는 `InputField`로부터 그 값을 받아오고 업데이트를 하였지만,
> 
> 이제는 DataHandler에서 직접 데이터를 받아와서 그림을 그려보는 작업을 진행하겠습니다.
> 
> 다만, 바로 실제 데이터를 쓰면 어려울 수 있으니, 지금은 가상의 데이터를 사용해서 진행해보도록 하겠습니다.
> 
> 다음은 제가 `DataHandler.cs`에 임시로 만든 함수입니다.
> 
> ```cs
>     static public WaterLog[] GetTempWaterData() {
>         WaterLog[] returnArray = new WaterLog[40];
>         //중략
>         return returnArray;
>     }
> ```
> 
> `GetTempWaterData` 함수는 호출하면 모아밴드에서 물 버튼을 누른 40회의 기록을 리턴하여 줍니다.
> 
> static함수이므로, 인스턴스를 호출하지 않고 class상에서 바로 호출이 가능합니다.
> 
> 다시 말하면, 스크립트 상 어디에서든
> 
> ```cs
>     DataHandler.WaterLog[] logs = DataHandler.GetTempWaterData();
> ```
> 
> 라는 코드로 40회의 임시 로그를 얻어 올 수 있다는 뜻입니다.
> 
> 40회의 기록은 2021년 01월 01일부터 2021년 01월 07일까지의 Timestamp를 가지고 있습니다.
> 
> 이해가 잘 안되신다면 [DataHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/DataHandler.cs)의 `GetTempWaterData` 구현 부분을 참고하세요
> 
> 
> 
> 
> 이제 선영님이 하실 일은, 이 7일치 데이터를 아래처럼 표시하는 일 입니다.
> 
> ![image](https://user-images.githubusercontent.com/40852277/104875392-88cd7780-5998-11eb-9449-7fb5363397a9.png)
> 
> 이제 Input Field는 지울 것이고, Image도 7개, 그 밑에 Text도 7개가 생겼으니
> 
> Scene도 많이 수정을 해야 할 것입니다.
> 
> 아래와 같은 일을 하시면 됩니다.
> 
> * 지난번 피드백 반영하기
> * Scene을 위 사진과 같이 수정하기. 7개의 Image와 바로 밑에 7개의 Text를 추가 할 것.
> * DataHandler의 임시 데이터에 따라 7개의 Image 데이터가 바뀔 것
> * DataHandler의 임시 데이터에 따라 7개의 Text 데이터가 바뀔 것 (n0~n6)
> * n0가 위치한 곳이 1월1일, n6이 위치한 곳이 1월 7일이 되도록 할 것
> * Editor의 Play버튼을 눌러 앱을 실행시키자 마자 값이 변하도록 할 것. ([유니티 Life cycle](https://docs.unity3d.com/kr/530/Manual/ExecutionOrder.html)참조)
> 
> 앱이 시작되자마자 값이 바뀌어야 하므로,
> 
> `Start()`, `OnEnable()`, `Awake()` 중 하나를 활용하길 바랍니다.
> 
> 이번 프로젝트 **데드라인**은 **목요일(21.01.21) 아침 회의(AM 11:00)전** 까지로 하겠습니다.
> 
> 이해가 안되거나 문제가 있다면, 언제든 알려주시길 바랍니다.


안녕하세요.
과제 완료하였습니다.

단, 현재 구현한 코드에서
아이가 버튼을 누르지 않은 날, 즉 기록이 없는 날의 Data는 Skip하고 보여주도록 되어있습니다.
이 부분은 반드시 필요한 기능이므로 내일 추가로 수정하겠습니다.

감사합니다!
황선영 드림

**Comment by KimYC1223** [comment]
본 이슈는 close하고, @dannyboy0103 전담으로

#13 에서 관리합니다.
