### ISSUE TITLE
[LOG] 로그 페이지 제스처 횡스크롤 문제

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#20]
# 로그 페이지 횡스크롤 문제

로그 페이지 제스처 횡스크롤이 제대로 동작하지 않음

- 횡스크롤 제스처 시간대 변경
- 횡스크롤 제스처시, 손가락이 움직인 거리에 비례해서 움직이는 기능이 작동하지 않음

**Comment by KimYC1223** [comment]
# 참고 사항

@sanghyuplee20 

```Input.TocuhCount```와 ```Input.GetTouch(int i)```뿐 아니라

```Input.GetTouch(int i).deltaposition```등으로 터치 드래그 제스처 중 포인터 속도를 알 수도 있습니다.

자세한 내용은 [이 블로그](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=pxkey&logNo=221312986925)를 참고하세요

---

또한, 터치를 하고 시간대를 옮기는 방법은

[```LogCanvasHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs)의 [```public void TimeRightButtonClick()```](https://github.com/FluidTrack/MOA_garden/blob/b98c1519a0a6eb1ae38c0234ee9b11452cdac921/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs#L875)과 [```public void TimeLeftButtonClick()```](https://github.com/FluidTrack/MOA_garden/blob/b98c1519a0a6eb1ae38c0234ee9b11452cdac921/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs#L927)함수를 참고하세요.

아래처럼 사용하면 됩니다.

```C#
// 시간대 변경할 때 (왼쪽으로 한 칸 이동)
if(LogCanvasHandler.Instance != null && LogCanvasHandler.Instance.gameObject.activeSelf == true) {
    LogCanvasHandler.Instance.TimeLeftButtonClick();
}

// 시간대 변경할 때 (오른쪽으로 한 칸 이동)
if (LogCanvasHandler.Instance != null && LogCanvasHandler.Instance.gameObject.activeSelf == true) {
    LogCanvasHandler.Instance.TimeRightButtonClick();
}
```

**Comment by KimYC1223** [comment]
@sanghyuplee20

해당 이슈는 잘 처리되고 있나요?

**Comment by sanghyuplee20** [comment]
잘 끝냈습니다.

카운터랑 쓰레쉬홀드를 이용함으로서 움직이게 코딩하였습니다!
