### ISSUE TITLE
[BUG] 하루보기 - 데이터 추가 불가 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#22]
상단의 4가지 아이콘 + 를 눌러도 데이터 추가 기능으로 넘어가지 않음 (길게, 짧게 모두 시도하였음)

**Comment by KimYC1223** [comment]
![ezgif-1-dfc5c3586b6f](https://user-images.githubusercontent.com/40852277/122718617-1dba0100-d2a8-11eb-8742-2aff1d466953.gif)

혹시, 구체적으로 어떤 상황에서 문제가 된 것인지 알 수 있을까요?

제가 여러번 확인했을 때는 문제 없이 잘 되는 모습입니다

---

@josephhanbin  @2sukhyunlee  @sayiovme @Yeohyun00 

다른 분들도 해당 이슈확인하시고, 증상이 있으시다면 꼭 보고해주시길 바랍니다.

**Comment by KimYC1223** [comment]
# 원인 분석

현재 모아정원은 데이터를 내부에 저장하는 로컬 방식이 아닌

AWS E2C 데이터베이스에 실시간으로 데이터를 넣고, 읽어오는 서버 방식을 사용합니다.

이 과정에서 데이터를 읽어 올 때, 서버와 통신하는 시간 지연으로

본 이슈가 발생 한 것으로 생각됩니다.

또한, 이 이슈 뿐 아니라

- [#23 [BUG] 정원가기&하루보기 - 모아밴드 연동된 상태에서 기록 반영 시간 딜레이 문제](https://github.com/FluidTrack/MOA_garden/issues/23)
- [#42 [BUG] '하루보기'와 '꽃 키우기'의 물 데이터 로딩 지연 및 불일치](https://github.com/FluidTrack/MOA_garden/issues/42)
- [#49 [BUG] 하루보기에서 특정 영역 선택 시 물, 소변 데이터 누락](https://github.com/FluidTrack/MOA_garden/issues/49)

모두 같은 원인이라고 판단하고 있는 상황입니다.

---

자세히 설명드리긴 어렵지만,

현재 방식은 서버로부터 데이터를 안전하게 수신 했을 때, ACK신호를 받고,

이 ACK신호를 수신하면 다음으로 넘어가도록 설계했습니다만,

해당 기능이 정상적으로 잘 동작하지 않고, 예기치 못한 동작도 빈번히 발생하는 것 같아

일정 시간을 대기하고 넘어가는 방식으로 변경했습니다.

---

일단 이렇게 변경함으로써 언급된 버그들은

(제가 테스트 했을 땐) 어느정도 해결 한 것 같아서,

이 이슈와 나머지 비슷한 이슈들을 모두 클로즈합니다.

혹시라도 비슷한 오류(로그를 추가했는데, 추가가 잘 안되거나, 화면을 갱신했을 때 복구되는 현상)를 발견하시면

Reopen하지 말고 새롭게 이슈를 만들어서 작성 부탁드립니다.

감사합니다.
