### ISSUE TITLE
[BUG] 정원가기&하루보기 - 모아밴드 연동된 상태에서 기록 반영 시간 딜레이 문제

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#23]
모아밴드와 App을 블루투스로 연결한 상태에서 버튼을 누르면 즉시 반영 안됨
예시)
물 버튼을 1회 누름
-> 상단의 기록에 반영 안됨
-> 물/오줌/똥 중 아무 버튼이나 1회 누름
-> 이전에 반영되지 않았던 물 1회 기록과 함께 지금 막 누른 버튼의 기록이 동시에 반영됨

**Comment by junhyungmoon** [comment]
모아밴드 연동이 된 상태에서 재현이 가능하길래 영상으로 이슈의 설명을 보완해 드립니다. 14초쯤 오줌 버튼을 눌렀을때 카운트가 올라가지 않고 다음 똥 버튼을 누를 때 동시에 오줌과 똥이 카운트 상승합니다. 

https://user-images.githubusercontent.com/8017454/122843283-0cb9d000-d33a-11eb-91d9-34964e0e54ce.mp4

**Comment by junhyungmoon** [comment]
위 영상을 사진과 마찬가지로 드래그앤 드롭으로 업로드 했는데 오디오 파일처럼 올라갔네요. 번거롭지만 다운로드 받으면 영상으로 보실 수 있습니다

**Comment by 2sukhyunlee** [comment]
비슷한 버그인 것 같아서 덧붙입니다.

이슈내용: '하루보기'를 띄운 채로 버튼을 눌렀을 때 바로 숫자에 반영되지 않음. '정원가기' 화면으로 이동하면 상단 숫자에는 반영되어 있음. 다시 '하루보기'로 돌아가면 반영 되어있음.
'정원가기' 화면에서 시작해도 비슷한 이슈 발생

**Comment by KimYC1223** [comment]
해당 이슈는 [#22 [BUG] 하루보기 - 데이터 추가 불가 현상](https://github.com/FluidTrack/MOA_garden/issues/22#issuecomment-877820631)에서 해결하였습니다.

#22에서 설명드린대로, 해당 이슈는 클로즈합니다.
