### ISSUE TITLE
[BUG] 벡터 이미지 사용 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#24]
벡터 이미지를 사용하여 선명하게 나오면 좋겠습니다

![Screenshot_20210621-094838_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122694470-6659c600-d278-11eb-8b38-aadb67f12d86.jpg)

**Comment by KimYC1223** [comment]
![image](https://user-images.githubusercontent.com/40852277/124697289-7da7dd00-df21-11eb-82ba-2bbc9cc13ab3.png)

@Yeohyun00 의 도움을 받아 수정 완료

**Comment by KimYC1223** [comment]
# [#46 [BUG] 똥 모양 선택요청 메세지 오류](https://github.com/FluidTrack/MOA_garden/issues/46) 보고 생각남

![image](https://user-images.githubusercontent.com/40852277/124893413-ac06e480-e015-11eb-9220-9859a40b48eb.png)

똥 모양 선택, 모아보기 건강 상식 말해주는 몽몽이 또한 고화질로 변경이 필요..

이슈 reopen함

**Comment by KimYC1223** [comment]
# Figma Export

@Yeohyun00 님...

제가 #24 의 몽몽이, #25 의 구름에서 부탁 드렸던 작업을 기본 몽몽이1 / 기본 몽몽이 2 에도 똑같이 부탁드립니다.

**Comment by KimYC1223** [comment]
![image](https://user-images.githubusercontent.com/40852277/125110944-3dfb1400-e120-11eb-94d9-6b8fbd638b73.png)

@Yeohyun00 의 도움을 받아 수정 완료
