### ISSUE TITLE
[BUG] 이미지 크롭된 부분 보완 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#25]
소변과 대변 아이콘 테두리 선의 하단이 잘려있습니다

![Screenshot_20210621-094809_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122694558-b9cc1400-d278-11eb-923e-b8b5e229e0d7.jpg)

**Comment by KimYC1223** [comment]
수정 완료

**Comment by junhyungmoon** [comment]
새로 가입하면서 보니 아직 해결이 안된것 같아서 reopen 하였습니다. 혹시나 하여 정확히 쓰자면 소변과 대변의 "검정색 테두리" 하단이 잘려있다는 코멘트였습니다

**Comment by KimYC1223** [comment]
앗... 이해했네요 후다닥 읽고 좌우 여백문제를 말씀 하신줄 알았습니다.

수정해보겠습니다

**Comment by KimYC1223** [comment]
수정 완료

**Comment by junhyungmoon** [comment]
새로운게 발견
![Uploading Screenshot_20210703-132645_MOA GARDEN.jpg…]()

**Comment by junhyungmoon** [comment]
![Uploading Screenshot_20210703-132645_MOA GARDEN.jpg…]()

**Comment by junhyungmoon** [comment]
새로운 것이 발견되어서 reopen 하였습니다 (구름)
그리고 구름 테두리가 잘린것뿐만 아니라 좀 깨지는 것처럼 보입니다

![Screenshot_20210703-132645_MOA GARDEN](https://user-images.githubusercontent.com/8017454/124343168-7bcdd900-dc04-11eb-92e0-fbdb8582e541.jpg)

**Comment by KimYC1223** [comment]
@Yeohyun00 의 도움을 받아 수정 완료!

![image](https://user-images.githubusercontent.com/40852277/124715767-4c89d580-df3e-11eb-90d1-908814574e64.png)
