### ISSUE TITLE
[BUG] 개발자용 팝업이 남아있음

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#26]
해당 문구를 보여주려면 다른 팝업 메세지와 동일한 수준으로 표현되어야겠습니다.

![Screenshot_20210621-094736_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122694630-f861ce80-d278-11eb-8125-6e3f72fbf316.jpg)

**Comment by KimYC1223** [comment]
수정 완료

**Comment by junhyungmoon** [comment]
위 이미지는 최초 모아밴드 등록시 나타난 팝업이고, 이번에 첨부한 이미지는 등록 후 재접속시 모아밴드 연결 성공하면 나오는 팝업입니

![Screenshot_20210622-092506_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122844172-09bfdf00-d33c-11eb-8b7a-42d1014a9024.jpg)

**Comment by KimYC1223** [comment]
업데이트할 1.0.2 버전에서는 수정이 되어있을 겁니다!
