### ISSUE TITLE
[BUG] 최초 세팅 화면 - 시간 설정 기준이 모호해 보입니다

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#27]
45분, 30분 단위의 시간이 특정 항목에만 보이는데 규칙의 의도를 잘 모르겠습니다.

![Screenshot_20210621-094558_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122694733-51c9fd80-d279-11eb-8d45-a42d6f7cd3ef.jpg)
![Screenshot_20210621-094634_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122694736-52fb2a80-d279-11eb-85af-f14d3c422537.jpg)

**Comment by KimYC1223** [comment]
@junhyungmoon

버튼을 한 번 눌렀을 때 증감되는 시간 (15분 단위)이 애매하다는 뜻인가요?

아니면 시간의 초기 값인 ```아침 식사 오전 8시 00분, 점심식사 오후 12시 00분, ... ``` 이 애매하다는 뜻일까요?

---

전자의 경우라면, 버튼을 눌러서 증감시키는 인터페이스 특성상 1분 단위의 증감으로 설정하면,

원하는 시간으로 맞추기 위해 버튼을 너무 많이 눌러야 한다고 생각해 15분 단위로 맞춘 것입니다.

<br><br>

후자의 경우, 정확한 기준은 없었습니다만, 처음 개발할 때

등원 시간 9시, 하원 시간 6시로 생각했을 때 8시 30분에는 버스를 타야 할 것 같아서, 식사시간 30분을 뺀 8시를

아침 식사 시간으로 설정했고, 그보다 30분 전을 모닝콜 시간으로 설정했습니다.

점심식사는 일반적으로 12시에 먹을 것 같아서 12시로 설정했으며,

저녁식사는 6시에 하원을 하고 난 뒤, 30분 이동 시간 후 집 와서 쉬고 밥 먹을 준비하는 시간으로 15분을 주어

6시 45분이라고 생각했습니다.

---

전자,후자 모두 제가 생각한 기준이며, 얼마든지 수정 가능합니다.

원하시는 증감량/시간대 있으시면 변경해드리도록 하겠습니다.

**Comment by junhyungmoon** [comment]
화면을 처음 딱 봤을때 왜 이 항목만 시간이 00시가 아니라 다르게 조절되어있지? 란 인상을 받았습니다. 영찬학생이 고심해서 정한 그러한 기준을 짐작해볼 생각이 들지 않았어요. 아마 사용자들도 그러하지 않을까 싶습니다. 나름 고민해서 무언가를 정한 노력은 좋지만, 여기에 그런 디테일이 필요할지 모르겠고 또 엄연히 말하면 모든 아이들의 하원 시간이 6시가 아니고 또 버스를 타는 시간도 다 다를 것입니다. 대략적으로만 보여줘도 충분한 항목이라 생각됩니다.

**Comment by KimYC1223** [comment]
> 화면을 처음 딱 봤을때 왜 이 항목만 시간이 00시가 아니라 다르게 조절되어있지? 란 인상을 받았습니다. 영찬학생이 고심해서 정한 그러한 기준을 짐작해볼 생각이 들지 않았어요. 아마 사용자들도 그러하지 않을까 싶습니다. 나름 고민해서 무언가를 정한 노력은 좋지만, 여기에 그런 디테일이 필요할지 모르겠고 또 엄연히 말하면 모든 아이들의 하원 시간이 6시가 아니고 또 버스를 타는 시간도 다 다를 것입니다. 대략적으로만 보여줘도 충분한 항목이라 생각됩니다.

이해했습니다!

그럼 ```저녁식사 6시 00분```, ```모닝콜 7시 00분```으로 변경하겠습니다.

**Comment by KimYC1223** [comment]
수정 완료
