### ISSUE TITLE
[BUG] 하루보기&꽃키우기 - 빨간점 표기 누락

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#28]
해야 할 일이 남아 있어도 우측 상단의 꽃키우기 버튼에는 빨간 점이 나타나지 않습니다.
하단의 하루보기 버튼에만 나타납니다.
![Screenshot_20210621-100358_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122694809-92c21200-d279-11eb-8022-5d8523b08c10.jpg)

**Comment by KimYC1223** [comment]
꽃키우기 버튼에도 빨간점이 나타나야 하나요?

해당 기능은 전달받은 내용이 없어 구현하지 않은 상태입니다.

**Comment by junhyungmoon** [comment]
하루보기 화면에 빨간점을 띄우는 것이 직접 해야할 일이 있다는 것을 사용자에게 나타내주자는 것이 목표라고 회의에서 논의하였습니다. 그 맥락에서 생각해보면 꽃 키우기 버튼에도 표시해 주는 것이 일관성이 있지 않을까 생각됩니다.

**Comment by KimYC1223** [comment]
# 문제 해결

[#34 [BUG] 하루보기의 빨간점 출현 누락 현상](https://github.com/FluidTrack/MOA_garden/issues/34#issuecomment-877747540)에서

자세한 내용을 기술하였으므로,

해당 이슈는 클로즈하겠습니다.
