### ISSUE TITLE
[BUG] 꽃키우기 - 해야할 일 확인 알고리즘 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#29]
사용할 아이템이 없는데에도 사용하라고 요구하는 팝업이 등장

![Screenshot_20210621-100309_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122694994-2562b100-d27a-11eb-86f4-c305d04696d0.jpg)

**Comment by KimYC1223** [comment]
해당 문제는

이슈 #37 [[BUG] 꽃키우기 - 10개 초과 꽃 표현 방식](https://github.com/FluidTrack/MOA_garden/issues/37)를 해결하면서 자연스럽게 고쳐진 것으로 확인 됨.

꽃 키우기 화면에서 ```돌아가기``` 버튼을 누르면,

[```FlowerPageHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/Flower/FlowerPageHandler.cs#L137)의 [```public void BackButtonClicked()```](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Flower/FlowerPageHandler.cs#L137)을 호출하는데...

```C#
public void BackButtonClicked() {
    if (!isTouchAble) return;
    if (iconCount == 0) BackButtonRealActive();
    else {
          AlertWindow.SetActive(true);
           SoundHandler.Instance.Play_SFX(SoundHandler.SFX.ERROR);
    }
}
```

에서 ```iconCount```라는 변수의 값에 따라 경고 창을 띄울지 말지를 결정함.

**이때, ```iconCount```는 ```waterIconCount + peeIconCount + pooIconCount```인데,**

#37 처럼 ```waterIconCount```를 잘못 세는 버그가 있어서,

```iconCount``` 값 역시 문제가 됐던 것으로 보이며

해당 이슈가 해결 됨에 따라 본 이슈도 해결된 것으로 보임

---

다만, 혹시라도 같은 증상을 발견하면 Reopen 할 것...!
