### ISSUE TITLE
[Calendar] Pee Log Handler 구현

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#3]
# Calendar Pee Log Handler 구현

Assignees : @dannyboy0103 

Text Field에 입력된 값에 따라 아래 Sprite가 변경됨
```Sprites/Gauge/``` 참고

0 이하일 때 : 00.png
0초과 2이하 일 때 : 01.png
2초과 10이하 일 때 : 02.png
10초과 30이하 일 때 : 03.png
30초과 일 때 : 04.png

**Comment by KimYC1223** [comment]
@dannyboy0103 

잘 진행되고 있는지 중간 보고 부탁 드립니다!

**Comment by dannyboy0103** [comment]
현재 마무리 작업 중입니다!

**Comment by KimYC1223** [comment]
push잘 되시면 해당 이슈에 코멘트 부탁드립니다.
감사합니다

**Comment by KimYC1223** [comment]
# 코드 리뷰

전체적으로 아주 잘 하셨습니다.
Unity에 대해 감을 잡길 바랬는데, 아주 잘 하신것 같아 기쁩니다.

아주 마이너하지만, 몇 가지 집어드리도록 하겠습니다.

---

일단, [InputFieldHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/KDH_Script/InputFieldHandler.cs)에서,

```C#
    public void changevalue() {
      currentValue = int.Parse(inputField.text);
      valueText.text = currentValue.ToString();
    }
```

```inputField.text```는 string 타입인데, 굳이 int로 변경 후

```valueText.text```에 다시 string으로 변경하여 넣는 이유를 잘 모르겠습니다.

```currentValue```라는 변수에 현재 값을 저장하고, 나중에 참조하려는 의도라면...

그렇다면 인정입니다.

또한, 지금은 아래 사진처럼 Input Field 오브젝트의

```InputField```컴포넌트 ```Content Type```속성이 Integer Number이기 때문에

![image](https://user-images.githubusercontent.com/40852277/104845956-69dcd000-591b-11eb-914a-67a15c84399f.png)

문제가 없이 파싱이 되겠지만, ```Int.Parse(string str)```메소드 같은 경우

익셉션을 리턴하기 매우 쉬우므로, (예 : "abc"를 int로 파싱하는 경우)

사용할 때 항상 try-catch문을 사용해주시길 바랍니다.

```C#
    public void changevalue() {
        try {
            currentValue = int.Parse(inputField.text);
        } catch(System.Exception e) {
            Debug.Log(e.ToString());
            currentValue = 0;
            inputField.text = "0";
        }
        valueText.text = currentValue.ToString();
    }
```

---

그 다음, [GaugeHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/KDH_Script/GaugeHandler.cs)에서는

제가 원하는대로 아주 잘 구상해주셨습니다.

```C#
    public void ChangeGauge() {
      if (int.Parse(inputField.text) <= 0)
      {
        beforeImage.sprite = sprite1;
      }
      else if (int.Parse(inputField.text) <= 2)
      {
        beforeImage.sprite = sprite2;
      }
      else if (int.Parse(inputField.text) <= 10)
      {
        beforeImage.sprite = sprite3;
      }
      else if (int.Parse(inputField.text) <= 30)
      {
        beforeImage.sprite = sprite4;
      }
      else
      {
        beforeImage.sprite = sprite5;
      }
    }
```

다만, 지금 코드를 보면 Range를 나누는 값이 정수(0,2,10,30)로 되어 있는데,

앞으로는 co-work를 위해 변수로 써주시길 부탁드립니다.

저 숫자들은 그냥 제가 임의로 정한 것들이고, Range값은 회의를 통해서 수시로 바뀌기 때문에

나중에 편하려면 이런 것부터 신경을 써줘야 합니다.

---

너무 마이너 한 것을 짚어 드린 것 같아서.. 조금 민망하지만

그냥 잘했다고 넘어가면 대충한다고 생각하실까봐 몇 자 적었습니다.

일단 제가 여기 적은 사항들만 업데이트 해서 git push 다시 부탁드립니다.

( 선영님이 git push하기 전까지는 계속 ```git add .```후 

```git reset HEAD /Users/kimdonghyun/Desktop/Internship_FluidTrack/MOA_garden/Assets/Scenes/TestScene_HSY.unity```

명령어 입력해주셔야 합니다.! )

<br>

다음 목표는 내일까지 업로드해드리겠습니다.

수고하셨어요! 😁

**Comment by dannyboy0103** [comment]
int.Parse() 부분과 ToString()부분은 제가 자료 찾아보면서 테스트 겸 해봤던 부분인데 신경 못쓰고 그대로 올려버린 것 같습니다. 죄송합니다...
Range를 나누는 부분에서 co-work를 위해 변수로 쓰는 방법은 앞으로 잘 기억하고 이용하도록 하겠습니다!

**Comment by KimYC1223** [comment]
> int.Parse() 부분과 ToString()부분은 제가 자료 찾아보면서 테스트 겸 해봤던 부분인데 신경 못쓰고 그대로 올려버린 것 같습니다. 죄송합니다...
> Range를 나누는 부분에서 co-work를 위해 변수로 쓰는 방법은 앞으로 잘 기억하고 이용하도록 하겠습니다!

아니 죄송할 필요까지야 전혀 없습니다.

그리고 선영님이 어제 새벽에 push하셨으니, git reset 은 하지 않으셔도 됩니다.

**Comment by KimYC1223** [comment]
# DataHandler와 연동

이제 본격적으로 FluidTrack 서버와 연동하여 데이터를 그리는 작업을 해 보겠습니다.

일단 지금 현재 FluidTrack App과 서버의 통신은 다음과 같이 이루어집니다.

![image](https://user-images.githubusercontent.com/40852277/104873978-1f983500-5995-11eb-800c-c9e2e8dcf3e5.png)

DB에 저장된 데이터는 구축해 놓은 Rest API 서버를 통해 [CRUD](https://www.google.com/search?q=CRUD&oq=CRUD&aqs=chrome..69i57.2219j0j4&sourceid=chrome&ie=UTF-8) 할 수 있으며,

App에서는 DataHandler라는 클래스가 서버와 통신을 담당합니다.

DataHandler는 App이 실행되면 사용자의 ID에 맞는 데이터들(정원기록, 물 섭취, 오줌, 똥 로그 등등)을

서버로부터 Fetch하고 List형태(Array형태)로 저장합니다.

오줌 로그로 예를 들면, 현재 사용자의 오줌 로그 기록은

DataHandler의 ```Pee_logs```에 ```PeeLogs```라는 이름으로 저장되어 있습니다.

```C#
    // DataHandler.cs 중
    internal static PeeLogsJson  Pee_logs;

    public class PeeLogsJson {
        public PeeLog[] PeeLogs;
    }

    public class PeeLog {
        public int log_id;
        public int id;
        public string timestamp;
    }
```

```WaterLog``` 클래스에는 로그의 고유 아이디인 ```log_id```,

로그의 소유자를 나타내는 ```id```, 로그가 생성된 시각인 ```timestamp```가 있습니다.

---

@dannyboy0103 님이 처음 하신 예제에서는 ```InputField```로부터 그 값을 받아오고 업데이트를 하였지만,

이제는 DataHandler에서 직접 데이터를 받아와서 그림을 그려보는 작업을 진행하겠습니다.

다만, 바로 실제 데이터를 쓰면 어려울 수 있으니, 지금은 가상의 데이터를 사용해서 진행해보도록 하겠습니다.

다음은 제가 ```DataHandler.cs```에 임시로 만든 함수입니다.

```C#
    static public PeeLog[] GetTempPeeData() {
        PeeLog[] returnArray = new PeeLog[100];
        //중략
        return returnArray;
    }
```

```GetTempPeeData``` 함수는 호출하면 모아밴드에서 오줌 버튼을 누른 100회의 기록을 리턴하여 줍니다.

static함수이므로, 인스턴스를 호출하지 않고 class상에서 바로 호출이 가능합니다.

다시 말하면, 스크립트 상 어디에서든

```C#
    DataHandler.PeeLog[] logs = DataHandler.GetTempPeeData();
```

라는 코드로 100회의 임시 로그를 얻어 올 수 있다는 뜻입니다.

100회의 기록은 2021년 01월 01일부터 2021년 01월 07일까지의 Timestamp를 가지고 있습니다.

이해가 잘 안되신다면 [DataHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/DataHandler.cs)의 ```GetTempPeeData``` 구현 부분을 참고하세요

<br><br>

이제 동현님이 하실 일은, 이 7일치 데이터를 아래처럼 표시하는 일 입니다.

![image](https://user-images.githubusercontent.com/40852277/104876006-0f368900-599a-11eb-862b-d2a37b22ad1f.png)

이제 Input Field는 지울 것이고, Image도 7개, 그 밑에 Text도 7개가 생겼으니

Scene도 많이 수정을 해야 할 것입니다.

아래와 같은 일을 하시면 됩니다.

- 지난번 피드백 반영하기
- Scene을 위 사진과 같이 수정하기. 7개의 Image와 바로 밑에 7개의 Text를 추가 할 것.
- DataHandler의 임시 데이터에 따라 7개의 Image 데이터가 바뀔 것
- DataHandler의 임시 데이터에 따라 7개의 Text 데이터가 바뀔 것 (n0~n6)
- n0가 위치한 곳이 1월1일, n6이 위치한 곳이 1월 7일이 되도록 할 것
- Editor의 Play버튼을 눌러 앱을 실행시키자 마자 값이 변하도록 할 것. ([유니티 Life cycle](https://docs.unity3d.com/kr/530/Manual/ExecutionOrder.html)참조)

앱이 시작되자마자 값이 바뀌어야 하므로,

```Start()```, ```OnEnable()```, ```Awake()``` 중 하나를 활용하길 바랍니다.

이번 프로젝트 **데드라인**은 **목요일(21.01.21) 아침 회의(AM 11:00)전** 까지로 하겠습니다.

이해가 안되거나 문제가 있다면, 언제든 알려주시길 바랍니다.

**Comment by KimYC1223** [comment]
# 코드 리뷰

역시 잘 하시네요. 만족했습니다.

다만 한가지 신경쓰이는 것이 있다면, TotalHandler라는 이름입니다.

```Total Handler```는 그 성격이 모호합니다. 이는 개발자 간의 co-work관점에서도 문제가 될 수 있지만,

더 나아가서는 나중에 있을 개발에 충돌의 위험이 있습니다.

현재 ```Assets/Scripts/TotalManager.cs```에 각 FluidTrack 어플리케이션에 포함된

모듈 및 스크립트, Canvas간 통신을 조율하는, 전반적인 메인 컨트롤 class인 ```TotalManager```가 있습니다.

동현님이 만드신 ```TotalHandler```는 작은 의미에서 보면 잘 지은 작명이지만,

**달력 페이지, 그것도 Pee log 관련해서 총괄하는 기능을 담당하는 class에게 주어지기엔 너무 모호합니다.**

따라서 class이름을 변경하여 주시길 바랍니다.

---

# Next Mission

다음 미션입니다.

## 미션 1 _ 현실성 있는 ```GetTempPeeData()```함수

현재 동현님은 날짜를 비교하기 위해 다음과 같은 string과 단순 비교 연산을 수행하였습니다.

![image](https://user-images.githubusercontent.com/40852277/105319485-4611d680-5c08-11eb-8f40-ed9395256734.png)

하지만 실제로 저희가 다룰 데이터는12:0:0과 같이 시간이 딱 떨어지지 않을것입니다.

따라서 기존의 ```GetTempPeeData()```함수를 아래와 같이 수정하였습니다.

```C#
    static public PeeLog[] GetTempPeeData() {
        PeeLog[] returnArray = new PeeLog[100];

        for (int i = 0; i < 100; i ++) {
            returnArray[i] = new PeeLog();
            returnArray[i].id = 0;
            returnArray[i].log_id = i;
        }

        for (int i = 0; i < 10; i++)
            returnArray[i].timestamp = RandomTimeStamp("2021-01-01");
        for (int i = 10; i < 12; i++)
            returnArray[i].timestamp = RandomTimeStamp("2021-01-02");
        for (int i = 12; i < 30; i++)
            returnArray[i].timestamp = RandomTimeStamp("2021-01-03");
        for (int i = 30; i < 60; i++)
            returnArray[i].timestamp = RandomTimeStamp("2021-01-04");
        for (int i = 60; i < 80; i++)
            returnArray[i].timestamp = RandomTimeStamp("2021-01-05");
        for (int i = 80; i < 85; i++)
            returnArray[i].timestamp = RandomTimeStamp("2021-01-06");
        for (int i = 85; i < 100; i++)
            returnArray[i].timestamp = RandomTimeStamp("2021-01-07");

        return returnArray;
    }

   static public string RandomTimeStamp(string str) {
        string output = str;
        str += " " + Random.Range(0, 24);
        str += ":" + Random.Range(0, 60);
        str += ":" + Random.Range(0, 60);

        return output;
    }
```

함수를 호출하면 1월 1일부터 1월 7일까지 로그 100개를 받아옵니다,

다만 각 로그의 ```HH:MM:SS```부분이  랜덤하게 될 것 입니다.

당연하게도 현재 동현님이 작성한 코드에서는

**변경된 GetTempPeeData함수에 대해서 작동하지 않습니다.**

변경된 ```GetTempPeeData```에서도 잘 동작하도록 코드를 수정해주세요.

<details>
<summary>Keyword Hint</summary>
<a href="https://www.google.com/search?hl=ko&sxsrf=ALeKk00h-wulsM0iOyWt7w_RNv6s3-H1bg%3A1611215851768&source=hp&ei=6zMJYMPALMe4mAXxjoqIAw&q=Unity+String+Split&oq=Unity+String+Split&gs_lcp=CgZwc3ktYWIQAzIECCMQJzICCAAyAggAMgQIABAeMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeUM8DWM8DYIIKaABwAHgAgAF9iAF9kgEDMC4xmAEAoAECoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwiD4v7jxqzuAhVHHKYKHXGHAjEQ4dUDCAc&uact=5">Unity String Split</a>
</details>

---

## 미션 2 _ 향상된 CountPeeByTime

**미션1이 선행되어야 합니다.**

동현님의 ```CountPeeByTime()```함수의 구현 코드는 아래와 같습니다.

```C#
  public int CountPeeByTime(string Date) {
    int Count = 0;
    for (int k = 0; k < 100; k++) {
      if (logs[k].timestamp == Date) {
        Count++;
      }
    }
    return Count;
  }
```

**일단 시작하기 앞서, 100이라는 상수는 쓰지 않도록 부탁드립니다.**

동현님이 구현하는 대로 실제 App에 구현될 예정이니 

logs의 길이에 맞게 가변적으로 동작할 수 있도록 수정해주세요.

좌우간,

코드를 살펴 보면 모든 logs(100개)를 살펴 보는 작업을 모든 Date(7개)만큼 호출 하는 것을 알 수 있습니다.

700번 연산을 하게 되는 것이죠!

즉, 표현하고자 하는 Date가 n개고 logs가 m개면 ```CountPeeByTimes```함수의 시간 복잡도는 ```O(nm)```입니다.

```O(n^2)```형태로 그닥 좋은 성능은 아닌 상황이죠.

특히 저희 프로젝트와 같은 많은 데이터(로그)를 다루는 환경에서는 좋은 상황은 아닙니다.

하지만, ```DataHandler```에서 제가 구현한 ```GetTempPeeData()```를 살펴보면,

1월 1일 부터의 데이터가 **순서대로** 들어온다는 것을 **알 수 있기 때문에**,

이 함수 결과값을 700회까지 계산을 하지 않더라도 구할 수 있을 겁니다.

잘 생각해보시고 CountPeeByTime 함수를 향상시켜주세요.

---

## 추가미션 _ Sorting By TimeStamp

**미션2가 선행되어야 합니다.** 추가 미션은 하셔도 되고 안 하셔도 됩니다.

진짜 안 하셔도 괜찮으니 동현님 편하신대로 진행해주세요.

미션2의 경우, 데이터가 순서대로 들어온다는 것이 전제 조건이었습니다.

로그의 데이터가 순서대로 들어오지 않는다면 정말 ```O(nm)```이 될 것입니다.

따라서, 추가 미션은 ```DataHandler```의 ```GetTempRandomPeeData()```이라는 함수로 받아온 100개의 로그를

TimeStamp 순서대로 정렬하는 것입니다.

새로 등장한 ```GetTempRandomPeeData()```함수는 아래와 같습니다.

```C#
    static public PeeLog[] GetTempRandomPeeData() {
        PeeLog[] returnArray = new PeeLog[100];

        for (int i = 0; i < 100; i++) {
            returnArray[i] = new PeeLog();
            returnArray[i].id = 0;
            returnArray[i].log_id = i;
        }

        for (int i = 0; i < 100; i++)
            returnArray[i].timestamp = RandomTimeStamp("2020-01-0" + Random.Range(1, 8));

        return returnArray;
    }
```

함수를 실행하면

1월 1일 00시 00분 00초 부터, 1월 7일 23시 59분 59초 사이의 타임 스탬프 값이 100개가 리턴 됩니다.

이를 순서대로 정렬하고, 이 데이터에 맞게 7개의 Sprite가 변경되도록 수정해주세요.

**물론 당연히 O(n^2)이상이 소요되는 정렬은 쓰면 안됩니다!**

그 이하로 구현해주세요.

**📌 참고사항**

제가 예전에 구현한 ```TimeHandler```클래스에

```public static int CmpDateTimeStampDetail(string a, string b)```이라는 함수를 만들어 놓았습니다.

이 함수는 a가 더 과거라면 ```-1```, 미래라면 ```1```을 리턴하고, a와 b가 같은 시간이라면 ```0```을 리턴 합니다.

<details>
<summary>Keyword Hint</summary>
<a href="https://www.google.com/search?q=Unity+Array+sorting&oq=Unity+Array+sorting&aqs=chrome..69i57.3349j0j7&sourceid=chrome&ie=UTF-8">Unity Array Sorting</a><br>
</details>

---

쓰다 보니 엄청나네요.

기한은 일요일 (01.24) 오후 6시로 하겠습니다.

빠듯하거나 못 맞출것 같으면 말씀해주세요. 감사합니다.

**Comment by dannyboy0103** [comment]
TotalHandler 이름은 충돌이 일어나지 않도록 바꾸겠습니다.
다음 개발도 열심히 해보겠습니다.
좋은 조언해주셔서 감사합니다!

**Comment by KimYC1223** [comment]
# Calendar Page

![image](https://user-images.githubusercontent.com/40852277/105993822-27b94880-60ea-11eb-9dcd-7554c7f755b1.png)

최신 이미지를 구하지 못해 구 버전으로 준비 함

**Comment by KimYC1223** [comment]
@dannyboy0103 해당 페이지의 High-fi 디자인이 완성되면,

새로운 업무 assign 해 드리도록 하겠습니다. 그때까진 대기해주세요!

**Comment by dannyboy0103** [comment]
넵 알겠습니다!

**Comment by KimYC1223** [comment]
본 이슈는 close하고, @dannyboy0103 전담으로

#13 에서 관리합니다.
