### ISSUE TITLE
[BUG] 모아밴드 연결 불가 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#30]
가이드라인 문서에 따라 최초 앱 설치 및 실행할 때 모아밴드가 정상적으로 연결되었으며 앞서 리포트한 버그들을 찾아내는데에 사용하였음.
그러나 앱 종료 후 블루투스를 껐다가 다시 블루투스를 켜고 앱을 실행하였는데, 자동/수동 모두 연결되지 않음

모아밴드의 배터리는 충분히 많으며 실제로 태블릿에서 스캔했을 시 리스트에 뜨고, 버튼을 눌렀을때 LED 점등됨

![Screenshot_20210621-101746_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122695202-b3d73280-d27a-11eb-8fc5-ee9b479ceb77.jpg)
![Screenshot_20210621-101718_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122695206-b6398c80-d27a-11eb-88bc-7a45234c6447.jpg)
![Screenshot_20210621-101806_Settings](https://user-images.githubusercontent.com/8017454/122695208-b8035000-d27a-11eb-9282-cb92d931349f.jpg)

**Comment by junhyungmoon** [comment]
참고로 알려드리자면 현재 nrf toolbox 앱에서도 모아밴드를 scan 하지 못하고 있습니다. 다른 모아밴드는 모두 다른 방의 가방 속에 넣어두고 오전부터 1개만 가지고 테스트 했었고, 최초 App 설치 과정에서 사용 중인 1개 외의 다른 모아밴드는 스캔이 되지도 않았었습니다. 최초 App 설치 과정에서는 nrf toolbox 와 App 에서 모아밴드가 정상 연동/동작 했었습니다.

**Comment by KimYC1223** [comment]
@sayiovme  @2sukhyunlee  @Yeohyun00 

모두 같은 증상을 겪고 있는것 같아 이슈에 참여시켜 드렸습니다.

**Comment by KimYC1223** [comment]
문제 해결

감사합니다
