### ISSUE TITLE
[BUG] 모아밴드 연동시간오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#31]
모아밴드 수동연결이 실패했는데 연동된 시간이 계속 업데이트 됩니다

![Screenshot_20210621-155406_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122719737-966d8d00-d2a9-11eb-9763-d5292eddc9cc.jpg)

**Comment by KimYC1223** [comment]
#38 이슈로 전환하여 진행
