### ISSUE TITLE
[BUG] 모아밴드 연결실패

### ISSUE THREAD

**Issue by josephhanbin** [FluidTrack/MOA_garden#32]
가이드라인대로 [4. 모아밴드 준비]는 정상적으로 진행을 했고, input도 성공적으로 받고있지만
<img width="542" alt="Screen Shot 2021-06-21 at 5 19 43 PM" src="https://user-images.githubusercontent.com/85919101/122730154-e140d200-d2b4-11eb-91ad-f11e3ccfd57a.png">

설정 팝업대로 허용을 눌렀음에도 불구하고 모아정원 앱에서 연결을 안됩니다.
<img width="958" alt="Screen Shot 2021-06-21 at 5 20 46 PM" src="https://user-images.githubusercontent.com/85919101/122730298-07ff0880-d2b5-11eb-812f-faceb5e72baa.png">

설치 삭제하고 다시 다운로드 하는데도 문제가 아직도 생깁니다.

**Comment by KimYC1223** [comment]
혹시 nrf toolbox에서 disconnect를 하고 스캔을 시도하셨나요?

nrf toolbox에서 connect된 상태로 app에서 스캔을 하면, 디바이스를 찾을 수 없습니다.

disconnect되어 있는지 확인부탁드립니다... ㅠㅜ

**Comment by josephhanbin** [comment]
nrf toolbox에 disconnect 해보니깐 드디어 됩니다! 갑사합니다.

하지만 연결을 시키려고 할때 이런 창이 ㄸ뜨는데 정상적으로 나오는 창인가요?
It doesn't seem to cause any issues, as I can still test the buttons successfully aftwards but I wanted to confirm!

<img width="953" alt="Screen Shot 2021-06-22 at 9 50 17 AM" src="https://user-images.githubusercontent.com/85919101/122845732-4b05be00-d33f-11eb-80da-b55feb31f679.png">

**Comment by KimYC1223** [comment]
되셨다니 다행입니다.

Devug.LogError 팝업은 버그가 맞으며,

#26 이슈에서 확인가능합니다.

해당 버그는 추후 드릴 1.0.2버전에서는 고쳐져 있을겁니다.
