### ISSUE TITLE
하루보기 화면 중 추가 취소 기능 

### ISSUE THREAD

**Issue by sayiovme** [FluidTrack/MOA_garden#33]
https://user-images.githubusercontent.com/60974691/122758550-e6614980-d2d3-11eb-9fb8-e522a8ff202a.mp4

실수로 추가 버튼을 눌렀을 경우에 취소할 수 있는 방법이 없습니다.

기존 디자인에서는 Gray zone을 클릭하면 취소되었던 걸로 기억하는데요.

혹시 추가 취소 기능이 삭제되었다든지, 제 기억이 다르다면 언제든 알려주시기 바랍니다. 감사합니다!

**Comment by KimYC1223** [comment]
![ezgif-6-1a629f6929f9](https://user-images.githubusercontent.com/40852277/122774070-dbaeb080-d2e3-11eb-8b5b-32301b25885f.gif)

Gray zone이 아니라 버튼을 한번 더 눌러서 취소하고 있습니다.

감사합니다.

**Comment by junhyungmoon** [comment]
만약 영찬학생 의도대로 두려면, + 버튼을 눌렀을 때 해당 버튼이 + 가 아닌 취소 기능이 있는 표시로 변경되어야 합니다. 
유사한 피드백을 이미 회의에서 들어봤기 때문에 제 설명이 이해가 되시리라 생각됩니다.
혹시 잘 모르겠으면 질문 주세요~
유저 인터페이스 전문가분들께 피드백을 받기 전에 보완해야 할 부분이라 생각됩니다.

![Screenshot_20210622-092417_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122844242-37a52380-d33c-11eb-862d-3bb61871d045.jpg)

**Comment by KimYC1223** [comment]
[```LogBlocker.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/Log/LogBlocker.cs)의 [```public void OnShieldClick()](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Log/LogBlocker.cs#L32)에, 로그를 추가하는 상황이면

해당 상황을 캔슬하는 코드를 추가함

```C#
public void OnSideClick() {

    // ----------------------------------------------------------
    //      ....  중략  ....
    // ----------------------------------------------------------

    } else if (log.WaterButtonClicked || log.DrinkButtonClicked ||
               log.PooButtonClicked || log.PeeButtonClicked) {
        log.WaterButton.GetComponent<Button>().enabled = true;
        log.DrinkButton.GetComponent<Button>().enabled = true;
        log.PeeButton.GetComponent<Button>().enabled = true;
        log.PooButton.GetComponent<Button>().enabled = true;

        log.WaterButton2.interactable = true;
        log.DrinkButton2.interactable = true;
        log.PeeButton2.interactable = true;
        log.PooButton2.interactable = true;

        log.WaterButtonClicked = false;
        log.DrinkButtonClicked = false;
        log.PooButtonClicked = false;
        log.PeeButtonClicked = false;

        log.UpShield.SetActive(false);
        log.DownShield.SetActive(false);

        BlockOff();
    }
}
```

**Comment by junhyungmoon** [comment]
"만약 영찬학생 의도대로 두려면, + 버튼을 눌렀을 때 해당 버튼이 + 가 아닌 취소 기능이 있는 표시로 변경되어야 합니다."
위 코멘트의 의도가 잘 전달되지 않은 것 같아서 다시 설명드립니다.

아래와 같이 + (추가) 버튼을 눌렀을 때 상황에서 삭제를 위한 친절한 안내 방식은 어딜 눌러야 취소가 될지
표시를 해야한다는 의미입니다.
즉, + (추가) 버튼 을 다시 눌러서 취소가 되게 하려면 아래와 같은 상황에서는 버튼 모양이 + 가 아니라
취소를 나타내는 아이콘으로 바뀌어야 한다는 말이었습니다.
(추가) 버튼이 추가의 기능을 갖고 있는데, 그걸 누르면 취소가 된다는 것이 어색하다는 것이지요.

과거 회의에서 이봉신 박사님께서 유사한 피드백을 하셨다고 제가 위의 댓글에 썼었는데
이제 너무 시간이 많이 흘러서 기억은 나지 않네요.

이미지를 새로 삽입하는 방향으로 개선한다면 한빈학생에게 이미지를 요청하셔도 됩니다.

![Screenshot_20210714-123101_MOA GARDEN](https://user-images.githubusercontent.com/8017454/125556844-2f4c21e9-8c0e-480f-b2d1-c00fc41965f5.jpg)

**Comment by KimYC1223** [comment]
이해 했습니다. 취소 모양 아이콘을 새로 디자인 하는 방법밖에 없는것 같아서,

@josephhanbin 님께 카톡으로 취소 아이콘을 새로 디자인해달라고 요청드렸습니다.

다만, 취소 아이콘을 +대신 -로 해야할지, X로 해야할지, 아니면 전혀 다른 새로운 아이콘으로 해야할지는 잘 몰라서

@josephhanbin 님이 판단하셔서 디자인을 하셔야 할 것 같습니다.

감사합니다.

**Comment by KimYC1223** [comment]
# 문제 해결

![image](https://user-images.githubusercontent.com/40852277/131644798-3e378ab9-c021-4a1f-9e0b-90e566b7c5c4.png)

그냥 제가 고쳤습니다.

이슈 닫습니다
