### ISSUE TITLE
[BUG] 하루보기의 빨간점 출현 누락 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#34]
아래 2개 이미지가 모아밴드 연결 테스트를 하는 도중에 찍은 것이어서 좌측 상단의 모아밴드 연결상태가 다르긴 한데, 시간 순으로 맞는 그림입니다. 첫번째 이미지는 앱에 막 접속한 상황인데 하루보기 메뉴에 빨간 점이 뜨지 않습니다. 두번째 이미지는 접속하여 하루보기 버튼을 눌러 이동한 상황인데 이동을 하면서 빨간 점이 출현하는 것을 확인했습니다.

![Screenshot_20210622-092252_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122844864-83a49800-d33d-11eb-91d9-ae96541f3fe0.jpg)
![Screenshot_20210622-093533_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122844869-856e5b80-d33d-11eb-8a79-ab44b2b5b69a.jpg)

**Comment by junhyungmoon** [comment]
여러 방식으로 테스트 해본 결과, 하루보기 화면을 사용자가 가야만 하루보기 화면에 해야할 일이 있다는 빨간 점이 뜬다는 것이 근본적인 문제인 것 같습니다.

**Comment by KimYC1223** [comment]
# 문제 해결

하루보기 페이지 버튼과 꽃 키우기 버튼의 빨간점을 추가하고,

어느 페이지에 있든 해야 할 일이 생기면 빨간 점들이 활성화되도록 변경하였습니다.

---

## 1. 하루보기 버튼의 빨간 버튼 출현 조건

하루보기 페이지 버튼의 빨간 점은

**오늘 날짜 기록들 중, 똥 모양을 선택해야 하는 기록이 있는 경우 ( [#46 [BUG] 똥 모양 선택요청 메세지 오류](https://github.com/FluidTrack/MOA_garden/issues/46#issuecomment-877746551) 참고 )**

또는

**오늘 날짜의 꽃 키우기 페이지에 사용하지 않은 아이콘이 남아 있는 경우**

입니다. **또는**이므로, 한 가지 조건만 만족해도 나타납니다.

---

## 2. 꽃 키우기 버튼의 빨간 점의 출현 조건

꽃 키우기 버튼의 빨간 점은

**현재 하부로기 페이지에서 보고있는 날짜의 꽃 키우기 페이지에 사용하지 않은 아이콘이 남아있는 경우**

입니다.

---

여기서, 하루보기 버튼의 빨간 점은 **오늘 날짜**를 기준으로 나타나고,

꽃 키우기 버튼의 빨간 점은  **현재 하루보기 페이지에서 보고있는 날짜**를 기준으로 나타나는 것임을 유의해주시면 됩니다.

---

자세한 구현 내용은 [ProtocolHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/ProtocolHandler.cs) 를 참고하시길 바랍니다.

감사합니다.

**Comment by junhyungmoon** [comment]
캡쳐화면은 아래 링크에 리포트한 것과 동일한 상황입니다.
https://github.com/FluidTrack/MOA_garden/issues/46#issuecomment-880292412
모아밴드 <-> 모아정원 앱 연결된 상태에서 모아밴드로 버튼을 눌렀습니다. (앱에서 추가 X)
물을 꽃으로 피우지 않았고, 똥 모양을 안 골랐기 때문에 빨간점이 나와야 할 것 같습니다.
하지만 꽃키우기에는 빨간점이 뜨나, 하루보기에는 빨간점이 뜨지 않습니다. (다른 화면을 다녀와도 변하지 않음)

![Screenshot_20210715-091239_MOA GARDEN](https://user-images.githubusercontent.com/8017454/125708948-1e005ac2-7104-4bb9-833c-a946afa21d03.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

"오늘 날짜의 꽃 키우기 페이지에 사용하지 않은 아이콘이 남아 있는 경우"의 구현에 문제가 있어서 수정하였습니다.

아래는 관련 코드입니다.

```C#
    public void ReadGardenLogs() {
        bool ThereAreTodos = false;
        bool ThereAreTodosToday = false;
        bool ThereIsUnknown = false;

        if (DataHandler.Poop_logs != null && DataHandler.Poop_logs.PoopLogs != null && DataHandler.Poop_logs.PoopLogs.Length > 0)
            foreach (DataHandler.PoopLog log in DataHandler.Poop_logs.PoopLogs) {
                if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(new TimeHandler.DateTimeStamp(log.timestamp), TimeHandler.CurrentTime) == 0) {
                    if (log.type == 8) {
                        ThereIsUnknown = true;
                        break;
                    }
                }
            }

        if (DataHandler.Garden_logs != null && DataHandler.Garden_logs.GardenLogs != null && DataHandler.Garden_logs.GardenLogs.Length > 0) {
            foreach (DataHandler.GardenLog log in DataHandler.Garden_logs.GardenLogs) {
                if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(new TimeHandler.DateTimeStamp(log.timestamp), TimeHandler.LogCanvasTime) == 0) {
                    if (( log.log_water > 0 && log.flower < 10 ) || ( log.log_pee > 0 && log.item_0 == 0 ) || ( log.log_poop > 0 && log.item_1 == 0 )) 
                        ThereAreTodos = true;
                }
            }

            foreach (DataHandler.GardenLog log in DataHandler.Garden_logs.GardenLogs) {
                if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(new TimeHandler.DateTimeStamp(log.timestamp), TimeHandler.CurrentTime) == 0) {
                    if (( log.log_water > 0 && log.flower < 10 ) || ( log.log_pee > 0 && log.item_0 == 0 ) || ( log.log_poop > 0 && log.item_1 == 0 ))
                        ThereAreTodosToday = true;
                }
            }
        }

        LogCircle.SetActive(ThereAreTodosToday || ThereIsUnknown);
        FlowerCircle.SetActive(ThereAreTodos);
    }
```
