### ISSUE TITLE
[BUG] "생일"화면 이상

### ISSUE THREAD

**Issue by josephhanbin** [FluidTrack/MOA_garden#35]
![Screen Shot 2021-06-22 at 9 47 12 AM](https://user-images.githubusercontent.com/85919101/122845488-d5015700-d33e-11eb-8bcc-3b95b3d6e783.png)

"나의 하루"화면부터 이전에 있었던 "생일"화면으로 다시 돌아갈때 날짜말고 시간 범위로 나옵니다. 버트 아무거나 누를때 자동으로 다시 날짜로 바뀌지만 참고해주시기 바랍니다.

**Comment by KimYC1223** [comment]
수정 완료.

감사합니다
