### ISSUE TITLE
[BUG] 꽃키우기 - 10개 초과 꽃 표현 방식

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#37]
물섭취 기록이 10개 초과이면 그게 그대로 다 표현되었다가 1개아이템 쓰는 순간 10개 제한이 걸린 표현으로 바뀌는데, 자연스러운 흐름이 아닌것 같습니다.

![Screenshot_20210622-165332_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122886493-fb44e800-d37a-11eb-8352-5bbd8772f731.jpg)
![Screenshot_20210622-165344_MOA GARDEN](https://user-images.githubusercontent.com/8017454/122886517-00a23280-d37b-11eb-9ab9-3374bc02442b.jpg)

**Comment by KimYC1223** [comment]
앗 이건 의도가 아니라 버그가 맞습니다.

살펴보도록 하겠습니다

**Comment by KimYC1223** [comment]
해결 완료
