### ISSUE TITLE
[BUG] 모아밴드 수동연결 문제

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#38]
# 모아밴드 수동연결 문제

환경설정 UI의 모아밴드 수동연결 버튼이 정상적으로 동작하지 않음

- 최초 1회에 한하여, ```Coroutine continue failure``` 라는 메세제가 출력됨
- 스캔이 정상적으로 이루어지지 않음
- 스캔 결과에 따라 목표 디바이스를 찾으면 **자동으로**연결되어야 하는데, 동작하지 않음

**Comment by junhyungmoon** [comment]
연결이 안된 상태인데 연결을 해제한다고 나오는 것도 오류인것 같습니다
![Screenshot_20210627-105659_MOA GARDEN](https://user-images.githubusercontent.com/8017454/123530560-dbc10d00-d736-11eb-8f21-c38603e32420.jpg)

**Comment by KimYC1223** [comment]
해결 완료
