### ISSUE TITLE
[BUG] 목표보기 빨간 점 및 데이터 비반영 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#39]
물을 10번 마셨는데, 
1) 목표보기 버튼 아이콘에 빨간 점이 생기지 않고
2) 목표보기 화면 안에 보니 목표 달성이라고 표시되지 않습니다.

![Screenshot_20210628-133542_MOA GARDEN](https://user-images.githubusercontent.com/8017454/123581021-fe762300-d815-11eb-9f58-0f05bf99b562.jpg)
![Screenshot_20210628-133547_MOA GARDEN](https://user-images.githubusercontent.com/8017454/123581033-05049a80-d816-11eb-8c70-69532ffbb126.jpg)

**Comment by KimYC1223** [comment]
[```MissionCanvasHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/7b932389d06fce2ee4c53f847ca1b50c5e643336/Assets/Scripts/CanvasHandler/Mission/MissionCanvasHandler.cs#L190) [코드](https://github.com/FluidTrack/MOA_garden/blob/7b932389d06fce2ee4c53f847ca1b50c5e643336/Assets/Scripts/CanvasHandler/Mission/MissionCanvasHandler.cs#L190)를 보니 물을마신 횟수가 아니라

꽃을 피운 횟수로 카운트하고 있었습니다.

수정 완료했습니다.

---

빨간점은 아직 미완입니다. 빨간점까지 마무리 되면  클로즈 하겠습니다.

**Comment by Yeohyun00** [comment]
물을 10번 마셨는데 목표보기에 칭찬 몽몽이가 나타나지 않고, 꽃을 10번 피워야 나타나는 현상이 계속되고 있습니다.

**Comment by KimYC1223** [comment]
# 해결

목표보기 페이지에서 몽몽이의 동작을 제어하는 [```MissionPageMongMongHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/MongMong/MissionPageMongMongHandler.cs)에서,

정원 정보에서 오늘 날짜와 어제 날짜를 찾는 함수 [```public IEnumerator FetchData()```](https://github.com/FluidTrack/MOA_garden/blob/d5479ac4fffc12fa06f359439b4d3aeaa01cd7f3/Assets/Scripts/CanvasHandler/MongMong/MissionPageMongMongHandler.cs#L106)중,

찾는 조건이 ```log.flower```로만 되어있어 이를 수정하였습니다.

```C#
if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(
        yesterday, new TimeHandler.DateTimeStamp(logs[i].timestamp)) == 0)
  //yesterdayLog = logs[i].flower;                        // 수정 전
    yesterdayLog = (logs[i].flower + logs[i].log_water);  // 수정 후

else if (TimeHandler.DateTimeStamp.CmpDateTimeStamp(
        today, new TimeHandler.DateTimeStamp(logs[i].timestamp)) == 0) {
  //todayLog = logs[i].flower;                          // 수정 전
    todayLog = (logs[i].flower + logs[i].log_water );   // 수정 후
    break;

}
```
