### ISSUE TITLE
[BUG] 다음날 하루보기 로드 시 로그 에러

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#40]
![Screenshot_20210629-095627_MOA GARDEN](https://user-images.githubusercontent.com/65483592/123972816-27eda500-d9f6-11eb-88f6-a5514bfe0b73.jpg)

![Screenshot_20210629-095701_MOA GARDEN](https://user-images.githubusercontent.com/65483592/123975051-0db4c680-d9f8-11eb-9576-81d2e93ecc09.jpg)

이슈내용: 다음날 앱을 처음 열었을 때 하루보기 화면에서 날짜 반영이 바로 되지 않고 해당 에러창이 떴습니다.
(상단바에 29일이라고 표기되지만 하루보기 화면은 28일)
'Bug report'를 눌러 팝업창을 닫자 28일의 데이터가 로드되지 않은 것을 확인했습니다. 상단 아이콘에는 2개라고 써있지만 타임라인에는 뜨지 않습니다.

이슈조건: 전날 마지막 화면이 어떤 화면이었는지 등 정확한 조건이 기억나지 않습니다..
30일에는 이런 버그가 뜨지 않았던 것으로 보아 특정 상황에서만 발생하는 버그인 것 같습니다. 어떤 조건인지 앞으로 계속 확인해보겠습니다.

해결: 정원가기 화면으로 갔다가 다시 하루보기로 돌아오자 29일 화면이 정상적으로 로드되었습니다.

**Comment by KimYC1223** [comment]
혹시 앱을 실행시키고 종료하지 않은 채

다음날에 앱을 저 화면(하루보기 화면)부터 보게 된 걸까요?

**Comment by 2sukhyunlee** [comment]
앱을 종료하지는 않았던 것 같습니다. (앱 사용 중 대부분의 버그는 화면 이동 하면 일단은 해결이 되어서 앱 종료는 잘 안 하고 있습니다.)

아마 '하루보기' 화면으로 시작했던 것 같습니다.
오늘 저런 에러창이 뜨지는 않았지만 유사한 버그가 있어 새로 이슈를 작성했습니다.
#44 #45

**Comment by KimYC1223** [comment]
# 이슈 해결

[#45 [DISCUSS] 00시 이후 DEFAULT 화면으로 이동](https://github.com/FluidTrack/MOA_garden/issues/45)에서 해결한 이슈.

클로즈함
