### ISSUE TITLE
[BUG] 하루보기 몽몽이 출현조건 및 빨간점 표시 - 배변모양 선택

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#41]
![Screenshot_20210628-155603_MOA GARDEN](https://user-images.githubusercontent.com/65483592/123974231-718abf80-d9f7-11eb-995a-308b6009e453.jpg)

이슈내용: 1시의 배변모양을 선택하지 않았는데 아래 몽몽이 손이 출현하지 않습니다.
빨간점도 사라져있습니다.

이슈조건: 원래 몽몽이 손이 있다가, 3시에 앱 상단 아이콘을 사용해 배변을 추가하자 여전히 1시 배변모양을 선택하지 않았음에도 몽몽이 손이 사라진 것을 확인했습니다. 빨간점도 사라졌습니다.

혹시 버그가 아니라 원래 의도된 바라면 알려주세요!

**Comment by KimYC1223** [comment]
# 원인 분석

현재 몽몽이 손을 출현시키는 트리거는 **똥 기록이 추가 될 때, 기록의 상태가 '잘 모름'일 경우**입니다.

따라서 본 이슈에서는 몽몽이 손이 출현했지만, **3시에 '잘 모름'이 아닌 기록을 추가함**으로써

몽몽이 손을 출현시키지 않는, ```MongMongHand.SetActive(false);``` 코드가 실행되어

화면에서 사라진 것으로 판단됩니다.

아래는 관련 [LogCanvasHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs)의

[public void CreatePoopLog(DataHandler.PoopLog log, int hour)](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs#L565) 함수 부분입니다.

```C#
public void CreatePoopLog(DataHandler.PoopLog log, int hour) {
        // ------------------------------------------
        //    ... 중략 ...
        // ------------------------------------------

        if(log.type == 0) {
            isLogMongMong_Poo = true;
            MongMongHand.SetActive(true);
            Circle.SetActive(true);
            wrongPooCheck[index] = true;
        } else {
            isLogMongMong_Poo = false;
            MongMongHand.SetActive(false);
            Circle.SetActive(false);
        }

        // ------------------------------------------
        //    ... 후략 ...
        // ------------------------------------------
}
```

---

# 해결 방법

하루보기 페이지의 몽몽이 출현 트리거에 대한 큰 수정이 필요하다고 판단됩니다.

따라서 비슷한 이슈는 모두 클로즈하고,

[#46 [BUG] 똥 모양 선택요청 메세지 오류](https://github.com/FluidTrack/MOA_garden/issues/46) 에 통합하여 관리하도록 합니다.
