### ISSUE TITLE
[BUG] '하루보기'와 '꽃 키우기'의 물 데이터 로딩 지연 및 불일치

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#42]
![Screenshot_20210630-224918_MOA GARDEN](https://user-images.githubusercontent.com/65483592/123975609-700dc700-d9f8-11eb-9b3e-402e89396bd8.jpg)
![Screenshot_20210630-224926_MOA GARDEN](https://user-images.githubusercontent.com/65483592/123975613-713ef400-d9f8-11eb-9c52-0c50ecd66b72.jpg)

이슈: 하루보기에 기록된 물 데이터 개수가 꽃키우기 물컵 개수로 반영되는 시간이 지연되거나 로드하는 데에 실패합니다.
이러한 이유로 아래 2가지 상황이 발생합니다.
1) '하루보기'와 '꽃키우기'의 물 개수가 일치하지 않음
2) 몇 초 시간이 지나고 '꽃키우기' 에 들어가자 물컵 개수가 뒤늦게 증가해있음. (증가한 물컵 수가 '하루보기'와 일치하는지는 확인 못함)

이슈조건: 앱을 띄운 상태에서 태블릿 화면을 끄고 모아밴드를 사용했을 때 발생.

이슈상세: 
1. (사진 1, 2)
모아밴드 물버튼을 2번 눌러 물이 2컵 기록되어있지만 꽃키우기 화면에는 물이 1컵밖에 없습니다.
이는 정원가기 화면에도 동일하게 적용되어서, 정원가기에서도 꽃이 1개만 피어있게 됩니다.

2. 모아밴드 물버튼을 3번 눌러 물이 3컵 기록되었지만 꽃키우기 화면에는 물이 2컵 생깁니다.

3. 1,2번과 유사한 상황을 반복하여 최종적으로 물 12번을 기록했지만 꽃키우기의 물컵 개수는 9개입니다.  이 과정에서 1), 2)가 반복적으로 발생했습니다. 결과적으로 물컵이 9컵인 것으로 보아 로딩하지 못한 데이터도 있는 것 같습니다.

**Comment by KimYC1223** [comment]
해당 이슈는 [#22 [BUG] 하루보기 - 데이터 추가 불가 현상](https://github.com/FluidTrack/MOA_garden/issues/22#issuecomment-877820631)에서 해결하였습니다.

#22에서 설명드린대로, 해당 이슈는 클로즈합니다.
