### ISSUE TITLE
[BUG] '정원가기'와 '꽃키우기' 화면의 꽃 배치 상이

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#43]
![Screenshot_20210630-232418_MOA GARDEN](https://user-images.githubusercontent.com/65483592/123981817-80747080-d9fd-11eb-8d70-dba57d037c4d.jpg)
![Screenshot_20210630-232427_MOA GARDEN](https://user-images.githubusercontent.com/65483592/123981824-81a59d80-d9fd-11eb-8baa-0dbfe4534d81.jpg)

이슈내용: '정원가기'에서 보이는 꽃의 배치와 '꽃키우기'에서 보이는 꽃의 배치가 다릅니다. 통일할 필요성이 있어 보입니다.

이슈조건: 해당 사진은 꽃이 9개일 경우.

**Comment by KimYC1223** [comment]
# 수정 완료

![image](https://user-images.githubusercontent.com/40852277/128589771-2819022a-1d84-498b-b211-c88bad4c98f2.png)

이제 꽃키우기에서 보이는 배치로 통일함 (가운데 정렬)
