### ISSUE TITLE
[BUG] '하루보기'에서 다음날 날짜 반영이 바로 되지 않음

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#44]
이슈내용: 아침에 태블릿을 켜면 전날밤 띄운 '하루보기'에서 오늘 날짜가 뜨지 않습니다.
이슈조건: 전날밤 '하루보기' 또는 '꽃키우기' 화면에서 태블릿을 잠그고 다음날 아침 태블릿을 처음 켰을 때.

이슈상세:
1) 직관대로라면, 아침에 태블릿을 처음 켰을 때 보이는 화면이 '하루보기'일 때 당일 날짜를 보여줘야 할 것 같습니다.
오늘(7/1) 아침에 태블릿을 켜자, 전날밤 마지막으로 본 '하루보기'의 6/29 화면이 뜹니다.

2) '하루보기' 상단, 오늘(7/1)에 해당하는 화면으로 가는 화살표가 disabled 되어 있습니다.
6/30이 넘길 수 있는 최대입니다.
'정원가기'에 갔다가 오면 오늘(7/1)화면에 접근 가능해집니다.

**Comment by KimYC1223** [comment]
# 원인 분석

개발 노트에서, **하루보기 화면을 불러 올 땐, 오늘 날짜의 정보가 표현되어야 한다**라고 정해졌기 때문에

현재 모아정원 어플리케이션은 ```Log Page``` 오브젝트가 Enable되어 [```public void OnEnable()```](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs#L222) 함수를 호출 할 때마다

[```TimeHandler.GetCurrentTime();```](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/TimeHandler.cs#L230)함수를 호출 하고 시간을 갱신하여 오늘 날짜를 확인하고 정보를 fetch합니다.

```C#
public void OnEnable() {
    StartCoroutine(UserDataCheck());
    TimeHandler.GetCurrentTime();   // 여기서 시간을 갱신 (오늘 날짜 추적)
    WriteTimeStamp(TimeHandler.LogCanvasTime);

    // ------------------------------------------------
    //      ....  후략 ....
    // ------------------------------------------------
}
```

이 [```public void OnEnable()```](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs#L222)함수는

**오브젝트가 Disable되었다 Enable될 때** (또는 App을 처음 실행하여 Enable될 때)만 트리거 되기 때문에,

하루가 지나서 화면이 켜지는 상황에서는 호출되지 않으며, 이는 시간이 갱신되지 않았다는 의미이므로

본 이슈와 같은 상황이 발생합니다. (다른 페이지를 갔다 오면 [```OnEnable()```](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs#L222)이 호출되어 갱신됩니다.(2번 내용))

문제는 Unity App상에서는 화면의 꺼짐을 감지할 수 있는 방법이 없는 것 같다는 겁니다.

---

# 해결 방법

#45 [[DISCUSS] 00시 이후 DEFAULT 화면으로 이동](https://github.com/FluidTrack/MOA_garden/issues/45)을 채택하여 해결합니다.

화면의 꺼짐을 감지할 수 없다면,

**매 순간마다 시간을 체크하는 Thread를 하나 추가하여, 날짜 변경을 감지하면 아예 Page를 바꿔버리는 것**으로

개발 방향을 변경합니다.

이 경우, 페이지의 변경이므로 ```OnEnable()```함수가 실행되어 해당 이슈를 해결 할 수 있게 됩니다.

따라서 본 이슈는 클로즈하고 #45 [[DISCUSS] 00시 이후 DEFAULT 화면으로 이동](https://github.com/FluidTrack/MOA_garden/issues/45)에 병합하여 관리하는 것으로 처리 합니다.
