### ISSUE TITLE
[BUG] 우울한 몽몽이(?) 출현 조건 이상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#47]
장기간 미접속 후에 오늘 접속해서 물 버튼을 1회 누르고 꽃도 피웠는데 여전히 몽몽이가 우울합니다

![Screenshot_20210703-132931_MOA GARDEN](https://user-images.githubusercontent.com/8017454/124343267-2b0ab000-dc05-11eb-95be-617cb3f63171.jpg)

**Comment by KimYC1223** [comment]
초기에 결정된 몽몽이의 행동이 새롭게 갱신되지 않았다는 점에서

[#36 정원가기 몽몽이 출현 문제](https://github.com/FluidTrack/MOA_garden/issues/36)와 비슷하여,

본 이슈는 클로즈하고 해당 이슈로 통합하여 관리합니다.
