### ISSUE TITLE
[BUG] 정원가기와 꽃키우기의 꽃 색상 불일치

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#48]
![Screenshot_20210703-191706_MOA GARDEN](https://user-images.githubusercontent.com/65483592/124369628-a8d3c780-dca8-11eb-90d3-5a4671268bef.jpg)
![Screenshot_20210703-191654_MOA GARDEN](https://user-images.githubusercontent.com/65483592/124369629-aa04f480-dca8-11eb-9604-e47bb6655991.jpg)

소변 아이템을 사용하여 꽃키우기의 꽃색상은 밝아진 반면 정원가기의 꽃 색상은 소변 아이템 사용 '전'색상과 같습니다. (개수가 다른 것은 버그가 아니니 무시하셔도 괜찮습니다)

다른 의미로는, 정원가기에서 소변아이템을 쓴 날과 안 쓴 날의 구별이 되지 않습니다.

**Comment by KimYC1223** [comment]
# 구현 완료

![image](https://user-images.githubusercontent.com/40852277/128590141-65ceebef-f072-49e2-a56a-c76d706978d3.png)
