### ISSUE TITLE
[BUG] 하루보기에서 특정 영역 선택 시 물, 소변 데이터 누락

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#49]
![InkedScreenshot_20210703-191454_MOA GARDEN_LI](https://user-images.githubusercontent.com/65483592/124369733-0ddbed00-dcaa-11eb-874d-e2f9734a3728.jpg)

앱에서 아이콘을 직접 추가할 때 발생합니다.
항상 일정하게 발생하는 버그가 아니고, 아직까지 주스, 대변은 문제가 없었으나 지속 확인이 필요합니다.

1. 물의 경우 타임라인 영역의 위쪽, 소변의 경우 타임라인 영역의 아래쪽을 선택하여 추가하면 아이콘이 추가되지 않는다.
2. 아이콘을 다시 추가하면 2개 아이콘이 한꺼번에 추가된다. 
- 1번에서 누른 자리에 추가하면 2개 아이콘이 한꺼번에 추가되고, 1번이 아닌 자리(물: 아래자리) 를 누르면 1개만 추가되기도 함

**Comment by KimYC1223** [comment]
해당 이슈는 [#22 [BUG] 하루보기 - 데이터 추가 불가 현상](https://github.com/FluidTrack/MOA_garden/issues/22#issuecomment-877820631)에서 해결하였습니다.

#22에서 설명드린대로, 해당 이슈는 클로즈합니다.
