### ISSUE TITLE
[DESIGN] 하루보기 아이콘의 opacity

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#50]
![Screenshot_20210703-191454_MOA GARDEN](https://user-images.githubusercontent.com/65483592/124369848-5051f980-dcab-11eb-8fce-044d5163da57.jpg)

물과 소변 아이콘은 반투명하고 주스, 대변 아이콘은 투명합니다.
모든 아이콘을 불투명한 아이콘으로 사용하는 것이 좋을 것 같습니다.

**Comment by KimYC1223** [comment]
@Yeohyun00 의 도움을 받아 수정 완료

![image](https://user-images.githubusercontent.com/40852277/124744860-240fd480-df5a-11eb-80da-9b148601cd5f.png)

하루보기의 모든 아이콘이 불투명해짐

**Comment by KimYC1223** [comment]
분명 수정했는데, 반영이 안되어 있어서 제대로 다시 고쳤습니다.

**2021.08.02 23:47 작성**
