### ISSUE TITLE
[BUG] 하루보기 음료 아이콘 양 선택 없이도 추가됨

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#51]
![Screenshot_20210703-191930_MOA GARDEN](https://user-images.githubusercontent.com/65483592/124369879-9f982a00-dcab-11eb-9875-0aeea0dbe912.jpg)

(버그가 발생한 화면은 아닙니다.)

원래 음료종류와 양을 모두 선택한 뒤에 확인버튼이 활성화되어야 하는데, 음료종류 선택만으로 확인버튼 활성화가 될 때가 있습니다.

주스를 선택했을 때 해당 버그가 발생했습니다.
버그가 일정하지 않아 다른 음료를 선택해도 같은 버그가 발생하는지는 확인하지 못했습니다.

**Comment by KimYC1223** [comment]
이럴수가 이거는 감이 안잡히는데... 뭘까요 확인해보겠습니다 감사합니다

**Comment by KimYC1223** [comment]
[```AddDrinkLogHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Popups/AddDrinkLogHandler.cs)에서 [```public void OnEnable()```](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Popups/AddDrinkLogHandler.cs#L22)함수에

```isClicked```와 ```isChanged```변수의 초기화를 추가함으로써 해결

```C#
public void OnEnable() {
    LogCanvasHandler.Instance.DrinkWindow_ScrollAutoAdjust = true;
    OkayButton.interactable = false;
    isClicked = false;
    isChanged = false;
}
```
