### ISSUE TITLE
[BUG] 하루보기 똥 기록 제거 후 빨간점과 몽몽이 손 지속문제

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#52]
똥 모양을 '잘 모름'으로 선택하고 똥 기록을 추가하자 빨간점과 몽몽이 손이 등장하였고, 똥 기록을 제거했는데 빨간점과 몽몽이 손이 사라지지 않고 지속되고 있습니다. 
또한, 회의에서 논의된 대로, 똥 모양을 '잘 모름'으로 선택하고 똥 기록을 추가하면 빨간점과 몽몽이 손이 나오지 않는 것이 자연스러울 것 같습니다.

**Comment by KimYC1223** [comment]
# 원인 분석

현재 몽몽이 손을 출현시키는 트리거는 **똥 기록이 추가 될 때, 기록의 상태가 '잘 모름'일 경우**입니다.

따라서 본 이슈에서는 '잘 모름'을 선택해 몽몽이 손이 출현했지만,

기록을 삭제했을 때는 처리하는 함수가 없어 손이 사라지지 않는 것으로 판단됩니다.


아래는 관련 [LogCanvasHandler.cs](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs)의 몽몽이 손 관련 부분인

[public void CreatePoopLog(DataHandler.PoopLog log, int hour)](https://github.com/FluidTrack/MOA_garden/blob/7f76cdbb687bcefc110b6f442e6f6a586e7026d9/Assets/Scripts/CanvasHandler/Log/LogCanvasHandler.cs#L565) 함수 부분입니다.

```C#
public void CreatePoopLog(DataHandler.PoopLog log, int hour) {
        // ------------------------------------------
        //    ... 중략 ...
        // ------------------------------------------

        if(log.type == 0) {
            isLogMongMong_Poo = true;
            MongMongHand.SetActive(true);
            Circle.SetActive(true);
            wrongPooCheck[index] = true;
        } else {
            isLogMongMong_Poo = false;
            MongMongHand.SetActive(false);
            Circle.SetActive(false);
        }

        // ------------------------------------------
        //    ... 후략 ...
        // ------------------------------------------
}
```

---

# 해결 방법

하루보기 페이지의 몽몽이 출현 트리거에 대한 큰 수정이 필요하다고 판단됩니다.

따라서 비슷한 이슈는 모두 클로즈하고,

[#46 [BUG] 똥 모양 선택요청 메세지 오류](https://github.com/FluidTrack/MOA_garden/issues/46) 에 통합하여 관리하도록 합니다.

---

## P.S.

> 또한, 회의에서 논의된 대로, 똥 모양을 '잘 모름'으로 선택하고 똥 기록을 추가하면 빨간점과 몽몽이 손이 나오지 않는 것이 자연스러울 것 같습니다.

해당 기능 또한 고려하여 #46 에서 관리하도록 하겠습니다.
