### ISSUE TITLE
[BUG] 모아밴드 최초 연동 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#53]
맨 처음 APK 를 설치한 뒤 스캔 버튼을 누르면 아래와 같이 위치 정보 접근 권한 팝업이 뜹니다.
교수님들께서 테스트 하실 때 기대하는 흐름은 권한 허용을 한 뒤 자동으로 연결이 되는 것입니다.
하지만 스캔 종료 버튼을 누른 후 다시 스캔 버튼을 눌러야만 스캔이 됩니다.

이 과정을 실제 스터디에서는 연구원이 부모+아동과 함께 있을 때 할 것이어서 큰 문제는 없습니다.
다만, 고치기 어려운 것이 아니라면 교수님들께 보여드릴 때 괜한 피드백이 나오지 않도록 하는 것이
훨씬 좋습니다.

![Screenshot_20210714-121154_Permission controller](https://user-images.githubusercontent.com/8017454/125555321-e9e9a97b-67a3-4a72-8db7-a715247bf90f.jpg)

**Comment by KimYC1223** [comment]
이건... 사실 고치기 어렵다고 생각했습니다만, 오늘 혼자 생각하다가 든 구상 방향인데,

어차피 해당 로그가 앱을 사용하는 전체 기간을 통틀어 딱 1번만 나오므로,

아예 앱을 설치하고 처음 실행 할 때(모아 정원에서 데이터를 로딩 할 때) 저 팝업이 나타나도록 변경하겠습니다.

수정하고 나서 이슈 클로즈하겠습니다.

**Comment by junhyungmoon** [comment]
좋은 방법같습니다

**Comment by KimYC1223** [comment]
# 오프닝 화면에 2초간 BLE Scan하는 코드 추가

실제론 아무 의미 없는 행동이지만, 모아밴드를 최초로 사용했을 때,

BLE 사용권한을 오프닝 화면에서 물어볼 수 있도록 도와줍니다.

![ezgif-4-6cbddbc6e637](https://user-images.githubusercontent.com/40852277/128065791-b0a1c865-6ff8-4f5f-8b37-646cdf640395.gif)
