### ISSUE TITLE
[BUG] 최초 접속 시 불필요한 에러 메세지 출현

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#54]
최초 APK설치 후 모아밴드 연동 완료한 뒤 접속하자마자 뜨는 화면입니다.
아무것도 한 것이 없는데 에러 메세지가 뜹니다.

![Screenshot_20210714-121242_MOA GARDEN](https://user-images.githubusercontent.com/8017454/125555382-e097cdd8-05ee-4f90-9fff-bb4f8366443f.jpg)

**Comment by KimYC1223** [comment]
#57 해결하면서 같이 해결!
