### ISSUE TITLE
[Enhancement] 불필요한 모아밴드 해제 이슈

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#55]
수동 연결 버튼을 누르면 일부러 연결을 끊은 뒤 다시 스캔하는 것은 불필요한 기능인 것 같습니다.
괜히 연결이 꼬일 여지를 줄 수도 있고요.

현재 사용할 수 없는 기능은 보여주지 않거나 disable 하는 것이 좋겠습니다.
다른 페이지에서 이와 유사하게 논의한 바가 있는데,
예를 들어 하루보기 화면에서 "오늘가기" 버튼은 필요할 때만 활성화 됩니다.

![Screenshot_20210714-121310_MOA GARDEN](https://user-images.githubusercontent.com/8017454/125555427-5c451a88-c2a3-4f37-8d94-fd388d32edf2.jpg)

**Comment by KimYC1223** [comment]
수동 연결 기능을 구현하기 위해서는 연결을 끊고 일정 시간을 대기해야 합니다.

( 모아밴드 테스터 앱에서 연결 해제 시간이 없었던 이유는,

이렇게 연결 해제를 하자마자 바로 연결하는 기능이 없었기 때문입니다.)

**애초에 연결이 되어 있지 않을 땐 수동 연결을 시도한다면 연결 해제 UI가 뜨지 않지만,**

연결이 되어 있는 상황에서 시도 한다면

연결을 끊지 않거나, 대기 시간을 없앨 수는 없는 상황입니다.

연결 해제 UI는 그 연결 해제 시간 동안 보여줄 UI가 없으면 어색할 것이라고 생각해 추가한 것입니다.

UI를 없애거나 보여주지 않는 것, 또는 내용을 변경하는 것은 충분히 가능하나

대기 시간을 없애는 것은 어렵습니다.

**Comment by junhyungmoon** [comment]
제 코멘트의 취지는 연결이 된 상태에서는 수동연결 버튼을 못 누르게 막았으면 좋겠다는 것인데 그 것이 구현 불가능하다는 것인가요? 그래서 하루보기 화면의 오늘가기 버튼을 예로 들었습니다. 오늘의 화면에 있을때는 그 버튼이 아예 disable 되어 있어서요.

수동 연결은 자동연결이 실패했을 때, 즉, 이미 연결이 끊겨 있는 상황에서 사용되어야 하는 기능이지 연결이 이미 되어 있는데도 수동 연결을 위해 일부러 연결을 끊었다가 다시 연결시키는 것이 이상한 flow 라고 생각합니다.

**Comment by KimYC1223** [comment]
아... 이해했습니다 무슨 말인지...

아~주 예전에 최은경 교수님이 **연결중에도 연결을 끊고 다시 연결할 수 있어야한다**라고 얼핏 들은것 같아서

저렇게 구현했던것 같습니다.

---

> 연결이 된 상태에서는 수동연결 버튼을 못 누르게 막았으면 좋겠다는 것인데 그 것이 구현 불가능하다는 것인가요?

해당 기능 구현 가능합니다. 구현하면 클로즈하겠습니다.
