### ISSUE TITLE
[BUG] 정원가기 4주, 8주 view 혼용 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#56]
일단 저희가 4주 단위로 view 를 고정하고, 치료를 연장하게 되면 view 를 자동 확장하는 것으로 영찬학생이 이미 구현했다고 알고 있습니다. (과거 회의에서 공유한 적 있음)
그런데 지금 zoom-out 하여 화면 전환 직전까지 가보면 8주 단위의 view 가 보이는 듯 합니다.

![Screenshot_20210714-122545_MOA GARDEN](https://user-images.githubusercontent.com/8017454/125556255-c170d3fd-716f-41c4-a708-a30755b49cd3.jpg)

**Comment by KimYC1223** [comment]
앗... 해당 사진은 8주가 아니라 4주가 정상적으로 나오고 있는 것입니다.

비교를 위해 각 주차별 이미지를 보여드립니다.

---

# 4주차 화면

## 4주차 구름 있을 때

![image](https://user-images.githubusercontent.com/40852277/125726229-66984765-bd18-486d-92c4-dae6bd6a3b8b.png)


## 4주차 구름 없을 때

![image](https://user-images.githubusercontent.com/40852277/125726428-7dd7e544-ead9-4737-82c5-055f1a33de90.png)

---

# 6주차 화면

## 6주차 구름 있을 때

![image](https://user-images.githubusercontent.com/40852277/125726307-057cf6f0-4b10-40d7-bc01-e61ee8d5807b.png)

## 6주차 구름 없을 때

![image](https://user-images.githubusercontent.com/40852277/125726455-74a37d01-7e72-4ee2-96dc-4aa38eb7c027.png)

---

# 8주차 화면

## 8주차 구름 있을 때

![image](https://user-images.githubusercontent.com/40852277/125726332-6ad7b52b-aaf9-4491-8aee-eaff2a47411f.png)

## 8주차 구름 없을 때

![image](https://user-images.githubusercontent.com/40852277/125726496-9e5e7762-7592-4160-a7b6-282840594831.png)
