### ISSUE TITLE
[BUG] 모아밴드에 저장된 기록이 앱으로 전송되지 않는 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#57]
오늘 오전에 태블릿PC의 블루투스를 켠 채로 모아정원 앱을 실행시켜서 모아밴드와 연결된 상태에서 물 버튼을 1회만 누르고 몇가지 테스트를 하다가 종료했습니다.
그리고 나서 태블릿PC의 블루투스를 껐습니다. 제가 요새 밖에 나가지 않기 때문에 모아밴드를 들고 밖에 나가서 일과를 보내는 것을 재현하고 싶었습니다.
오후에 물 버튼을 2회 눌렀습니다. 연속해서 누르지 않았고 1시간 이상의 충분한 시간 간격을 두고 눌렀습니다.
밤이 되어 태블릿PC의 블루투스를 켜고 모아정원 앱을 실행시켜서 모아밴드가 자동으로 연결되는 것을 확인했습니다.
그런데 아래 사진처럼 물 버튼 2회 누른 기록이 반영되지 않았습니다. 
반영이 되었다면 물이 3회가 되어야 했습니다.

![Screenshot_20210714-210852_MOA GARDEN](https://user-images.githubusercontent.com/8017454/125620528-f9ec334d-6163-4272-b44a-8cd7a04b0766.jpg)

**Comment by junhyungmoon** [comment]
제가 오늘(15일) 오전 9시 8분에 모아밴드의 오줌 버튼을 1회 누르고, 9시 9분에 바로 이어서 태블릿PC 의 블루투스를 켠 뒤(원래 꺼져있었음) 모아정원 앱을 실행했습니다. 정상적으로 모아밴드와 모아정원 앱이 연동되었는데, 오줌 1회 기록은 앱에 나타나지 않았습니다. 혹시 몰라서 모아정원 앱을 켠 채로 모아밴드를 연동한 상태에서 버튼을 몇개 눌러놨는데, 9시 8분에 누른 오줌 기록은 늦게라도 반영되지 않았습니다.

**Comment by KimYC1223** [comment]
매우 크리티컬해 보이는 이슈이므로 상단에 pin하겠습니다.

**Comment by KimYC1223** [comment]
# To-do List

오랜시간의 고민 끝에 태블릿 - 서버와의 통신을 최소화 하기로 결정

서버의 부하를 줄일 수 있고, #57 #58 과 같은 버그를 없앨 수 있기 때문임

아래 내용은 단순히 @KimYC1223 이 보기 편하도록 적어둔 내용들임

---

>#### ~~0. 오프닝 화면에서 한번 다 가져와야함. 모든 로그들을~~ ✔️
>
>#### ~~1. 일단 모든 로드 함수들을 바꿔야함 어떻게? 로컬 데이터를 그냥 사용하는 것으로~~ ✔️
>
>#### ~~2. 전역 변수 리스트로 업데이트 & 추가 & 삭제 대기열을 만들어 놓아야함~~ ✔️
> ~~그리고 대기열 업데이트 함수까지 만들어야함~~ ✔️
>
>#### 3. 데이터가 추가 될 때마다 로컬 데이터를 추가하는 식으로 바꿔야함
>이때 리스트가아니라 어레이니까 그 Capa+1의 형식으로 바꿔줘야함
>
>#### 4. 그다음 트리거 조건들에 따라서 대기열이 차있으면 서버로 쿼리를 보내는 식으로 만들어 놓아야함
>4-1. 화면이 넘어 갈 때 (FooterBar.cs에서 추가하기)
>4-2. 앱이 종료될 때 (TotalManager.cs에서 OnApplicationQuit()에 추가)
>4-3. 앱 화면이 꺼질때  (TotalManager.cs OnApplicationPause()에 추가)
>4-4. 일정 시간이 지났을 때 (일단 5분마다로 해놓기)
>
>4-1~4-4까지 모두 했다면, 대기열을 비우고 4-4타이머를 리셋하기

---

완료 후 본 이슈 또는 회의 또는 메일을 통해 상세 보고 하기

**Comment by KimYC1223** [comment]
문제 해결...!

이제 데이터는 로컬 변수에 저장하고, 데이터에 변동이 생길 때만 서버에 업데이트합니다.
