### ISSUE TITLE
[BUG] 모아밴드 버튼을 눌렀을 때 앱 내에서 소리는 나는데 숫자는 증가하지 않음

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#58]
모아정원 앱과 모아밴드를 블루투스 연결 시켜놓은 상태에서 모아밴드 버튼을 누르면 "따랑" 소리가 나는 것을 확인하였습니다.
그 후에 테스트하면서 다음과 같은 현상을 발견하여 공유합니다.
테스트 할 때 버튼은 즉시 연속해서 누르지 않고 10초 정도의 간격을 두고 눌렀습니다.
(영상이 너무 커서 유투브에 올렸습니다)

42초
소변 버튼 누르면 앱 안에서 "따랑" 하는 소리가 나는데 숫자는 올라가지 않음
53초
대변 버튼 누를 때 소변 숫자도 함께 증가
1분51초
대변 버튼 누르면 앱 안에서 "따랑" 하는 소리가 나는데 숫자는 올라가지 않음 
2분1초
물 버튼 누를 때 대변 숫자도 함께 증가

https://youtu.be/HFru10KyiTc

**Comment by KimYC1223** [comment]
#57 에서 통합관리!
