### ISSUE TITLE
[BUG] 꽃 키우기 화면에 똥, 오줌 아이콘을 물 아이콘보다 먼저 사용할 때

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#59]
물 기록을 하지 않고, 똥/오줌 기록만 하여 꽃 키우기 화면에 똥/오줌 아이콘만 사용할 때
몽몽이가 꽃이 없는데도 꽃이 커졌다/화려해졌다라고 말하고 있습니다.
만약, 물/똥/오줌 기록이 다 있는 상황에서도 똥/오줌 아이콘을 먼저 사용한다면 똑같은 문제가 일어납니다.
꽃이 최소 하나가 있는 상황에서 똥, 오줌 아이콘을 사용할 수 있도록 하는 것이 좋을 것 같습니다.

**Comment by KimYC1223** [comment]
무슨 말씀이신지 이해했습니다.

그럼 물 아이콘이 없을 경우, 똥/오줌 아이콘을 클릭하지 못하게 disable 하겠습니다.

**Comment by junhyungmoon** [comment]
이 경우는 생각치 못한 상황이네요.
생각해보니 물 아이콘이 없는 것이 조건이기보다
땅에 꽃을 하나도 안 피웠으면 똥/오줌 아이콘을 disable 하는 것이 좋겠습니다.
그리고 꽃이 하나도 없는데 똥/오줌 아이콘을 사용하려고 시도할 경우에 몽몽이가 @Yeohyun00 "꽃을 먼저 피워줘" 이런 말을 하면 좋을 것 같습니다.
그냥 disable 만 해 놓으면 사용자들이 당황할 것 같습니다.

**Comment by KimYC1223** [comment]
@Yeohyun00 

꽃을 먼저 사용해달라는 텍스트/음성 5가지 정도만 뽑아서 주시면 반영해 보겠습니다.

**Comment by Yeohyun00** [comment]
> @Yeohyun00
> 
> 꽃을 먼저 사용해달라는 텍스트/음성 5가지 정도만 뽑아서 주시면 반영해 보겠습니다.

넵 알겠습니다.

**Comment by junhyungmoon** [comment]
@Yeohyun00 @KimYC1223 
이 건은 텍스트/음성 파일이 전달이 된 것인지 확인차 질문합니다

**Comment by Yeohyun00** [comment]
> @Yeohyun00 @KimYC1223
> 이 건은 텍스트/음성 파일이 전달이 된 것인지 확인차 질문합니다

네 전달되었습니다!

**Comment by KimYC1223** [comment]
# 문제 해결

[```FlowerPageHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/MongMong/FlowerPageMongMongHandler.cs)를 수정하여 해당 이슈를 해결하였습니다.

https://user-images.githubusercontent.com/40852277/128209643-c3d3dbe3-7e31-4b28-b2a5-3059e72e7471.mp4

**Comment by 2sukhyunlee** [comment]
이 이슈는 1.0.8에서 업데이트 되는건가요?

**Comment by KimYC1223** [comment]
네! 아직 릴리즈된 부분은 아닙니다
