### ISSUE TITLE
[BUG] 권장 몽몽이 멘트 오류

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#60]
권장 몽몽이 멘트 중 '물을 충분히 마시자몽!'이 음성으로는 잘 나오나 말풍선에는 '물을 많이 마시자몽!'으로 나와 업데이트가 되지 않은 것 같습니다.

**Comment by KimYC1223** [comment]
![image](https://user-images.githubusercontent.com/40852277/127836663-9ac450ea-887a-43d1-a846-a31bb1909cf7.png)

저런... 실수가 있었습니다. 수정했습니다. 감사합니다.
