### ISSUE TITLE
[Enhancement] 하루보기 화면 내에서 횡방향 스와이프 기능

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#62]
회의록인지 피그마인지 어디에 적었는지 기억나진 않지만 회의에서 이봉신 박사님께서 말씀하셨던 것은 기억이 나서 적어둡니다.

하루보기 화면 내에서 가로 방향으로 양쪽 버튼을 통해 1칸씩 네비게이션 하는데, 한번에 스와이프 하는 기능을 추가하면 좋을 것 같습니다.
다만, 버그는 아니므로 버그부터 잡는 것이 맞겠습니다.

**Comment by KimYC1223** [comment]
아, 본 내용은 [LOG] 로그 페이지 제스처 횡스크롤 문제 #20 에서 다루고 있고,

@sanghyuplee20 (상협)님이 담당하고 있습니다.

감사합니다.
