### ISSUE TITLE
[Enhancement] 음료 추가 시, 양의 default 값

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#63]
![image](https://user-images.githubusercontent.com/65483592/128015161-13fee0d6-5810-468e-a206-2d87dc4083b0.png)

App에서 음료를 추가할 때 default값으로 0ml 가 표시되면 좋을 것 같습니다.
비록 왼쪽에 '양' 이라고는 써있지만 값이 써있지 않으니 바(? 이걸 뭐라고 부르던가요...ㅎㅎ) 가 의미하는 것이 무엇인지 불분명한 것 같습니다.

**Comment by KimYC1223** [comment]
일단 명칭은 "슬라이드 바"입니다. ㅎㅎ

![image](https://user-images.githubusercontent.com/40852277/128045658-181a5821-b914-4997-8964-4e1d96b6b3f7.png)

초기 값은 0ml로 표시하도록 하였습니다.
