### ISSUE TITLE
[BUG] 정원가기 알림

### ISSUE THREAD

**Issue by josephhanbin** [FluidTrack/MOA_garden#64]
![Screenshot_20210805-104153_MOA GARDEN](https://user-images.githubusercontent.com/85919101/128278132-cc213456-aaf3-4cc3-86e4-877bb771cd86.jpg)
![Screenshot_20210805-104202_MOA GARDEN](https://user-images.githubusercontent.com/85919101/128278142-defe5e71-4ad5-4c25-a2b1-955e9090f6c5.jpg)

There is a red circle near the 정원가기 button that notifies users that there are more icons to be added, but when I go to the screen, there are no more icons to be added. UX관점에서는 user들이 헷갈릴 수 있을것 같은데 버그 확인 부탁드립니다.

**Comment by KimYC1223** [comment]
# 수정 완료

해당 내용에 조금 잘못된 부분이 있어서 수정하였습니다.

https://user-images.githubusercontent.com/40852277/128590590-d614196f-7d23-433b-bb73-6a20d434be18.mp4

문제를 추가로 더 발견하면, Reopen 해주시길 바랍니다.
