### ISSUE TITLE
[BUG] 하루보기 데이터 로그 이슈

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/MOA_garden#65]
![Screenshot_20210806-232731_MOA GARDEN](https://user-images.githubusercontent.com/65483592/128526596-2b8fd522-4584-4f7c-8a54-af57cccbc0ee.jpg)
![Screenshot_20210806-232708_MOA GARDEN](https://user-images.githubusercontent.com/65483592/128526607-463ae971-5452-42bf-9c79-c167348a1964.jpg)

위 사진(데이터 1개씩 있는 사진)이 정상 화면입니다.
아래 사진(데이터 2개씩 있는 사진)이 이슈 화면입니다.
[오후 3시경 마지막으로 태블릿을 확인 - 오후 11시쯤 모아밴드 사용 후 곧바로 태블릿 화면 킴 (모아정원이 아닌 인터넷 접속 중) - 실행 중인 앱 메뉴에서 모아정원 선택] 하자 아래 사진처럼 데이터가 2개씩 중복하여 표시되었습니다.

특이사항으로는 보통 모아밴드 사용 후 모아정원을 실행하면 데이터를 가져오는 중이라는 팝업창이 떴었는데 이번에는 그런 팝업창은 따로 없었습니다. 몇 시간만에 어플을 켰음에도 유니티 화면이 뜨지 않았던 것 같은데 이 부분은 확실치 않습니다.

**Comment by KimYC1223** [comment]
# 참고 사항

사안의 심각도가 높다고 판단하여 급하게 @2sukhyunlee 에게 직접 연락해 경위를 조사했음

내일 버그 잡을 때 참고할 것

- 로그가 2배로 보이는 현상은 다른 페이지를 이동하니 고쳐졌음 (Local, Server 데이터 오염X, **DrawCall이 한번 더 불린 듯**)
- 꽃 키우기 페이지에선 정상개수 였음 (이 역시 데이터 오염이 아님을 의미함)
- 데이터를 가져오는 중이라는 팝업은 아래 그림을 말함

![image](https://user-images.githubusercontent.com/40852277/128532360-b27f27f7-dfa4-4416-9cc9-5005a3c12744.png)

- 이 팝업이 너무 빨리 지나가서 못 본것인지, 아니면 정말 안 뜬 것인지 확실하지 않음
- @2sukhyunlee 의 진행 과정은 다음과 같음
> **진행 과정**
> 1. 태블릿이 바로 이 옆에 있는 상태에서
> 2. 모아밴드를 누르고
> 3. 바로 태블릿을 켠 후
> 4. 실행중인 앱에서 모아정원을 클릭 (하루보기 화면임)
> 5. 앱이 액티브 되고, 이 순간 데이터를 서버로 올리는 팝업이 안 뜬듯 함 (확실하지 않음)
> 6. 로그가 2배로 보임
- 단, 새로 고침을 한 후에는 정상적으로 보였다고 함 (5번까지 데이터는 잘 넘어온듯 함)

**Comment by KimYC1223** [comment]
이건... 아무리 봐도 이유를 잘 모르겠습니다.

일단 클로즈하고 다음번에 또 같은 이슈가 나온다면 리오픈하겠습니다
