### ISSUE TITLE
[Question] 종료 버튼 만들기(?)

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#67]
제가 제목에 물음표를 붙인 것은 이 기능이 반드시 필요할지 100% 확신은 없기 때문입니다.

튜토리얼을 하면서 어려웠던점 하나가 안드로이드 유저가 아니신 부모님이 세 분 중 두 분이셨고
그분들은 설정을 변경할때 화면 12시 방향에서 아래로 슬라이드 하면 UI 가 나오는 것조차 
모르시더라고요. 또한 앱을 종료할 때 화면을 12시 방향에서 아래로 슬라이드 하면 화면 최하단에
종료 UI 가 나오는 것도 잘 모르셨습니다.

제가 그 것을 보고 드는 생각은 여러 사용자들이 앱을 종료하지 않고 화면을 켜고 끄는 식으로
태블릿을 사용할 것 같습니다. 
#65 <- **이것과 유사하게 그러면 앱을 끄지 않고 내내 켜고 있는 것이 될텐데, 그래도 앱이 제대로
잘 동작할지 걱정이 되어서요~** 그래서 종료버튼을 만들면 어떨까 생각이 든 것입니다.

곧바로 요청하는 것이 아니라 discussion 이라 생각하고 의견 주세요

**Comment by KimYC1223** [comment]
앱을 개발 할 때, 저는 항상 종료(위로 스와이프 해서 실행중인 앱에서 종료하기)를 한다는 가정으로 만들었습니다만,

@2sukhyunlee 님은 앱을 끄지 않고 내내 켜고 테스트를 했던것 같습니다.

(이 때문에 #44 [[BUG] '하루보기'에서 다음날 날짜 반영이 바로 되지 않음](https://github.com/FluidTrack/MOA_garden/issues/44)과 #45 [[DISCUSS] 00시 이후 DEFAULT 화면으로 이동](https://github.com/FluidTrack/MOA_garden/issues/45)이슈가 발생했습니다.)

그런데 (지금은 해결한) 몇 이슈를 제외하고 잘 동작하는 것 같아서

제 개인적인 생각으로는 **앱을 종료하지 않고 사용해도 문제는 없겠다.** 입니다만,

**화면을 슬라이드했을 때 화면 최하단에 종료 UI가 나오는것도 잘 모른다**는 것은 좀 충격적이며

그런 사용자들에게 앱의 종료 기능이 없다는 것은 불편할 수 있는 여지가 있다고 생각하여

종료 버튼을 추가하는것은 바람직해 보입니다.

> ( 일단, 숙현님께 개인적으로 연락하며 #65 [[BUG] 하루보기 데이터 로그 이슈](https://github.com/FluidTrack/MOA_garden/issues/65)의 원인을 분석하고 있습니다만, 
> 앱을 종료하지 않고 사용해서 발생한 문제인지는 잘 모르겠습니다. )

---

이 버튼을 만드는건 아주 쉬운데, 문제는...

- 버튼을 어디에 만드는지,
- 버튼을 어떻게 디자인 할 것인지,

입니다. 제 개인적인 생각으로는...

## 버튼을 어디에 만드는지

제 생각에는, 이미 화면에는 너무 많은 정보가 들어있는 것 같습니다.

따라서, Setting Panel (볼륨 조절과 모아밴드 수동 연결이 위치한 곳)에 버튼을 넣도록 하겠습니다.

Setting Panel에 종료가 있는것은 다른 app이나 게임에서도 흔히 찾아 볼 수 있는 UX입니다.

## 버튼을 어떻게 디자인 할 것인지

정확히는 버튼을 눌렀을 때 어떻게 동작하도록 할 것인지에 대한 것입니다.

버튼을 누르기만 해도 앱이 꺼져버리는 것은 좋지 않을 것 같고,

정말 종료할 것이냐는 UI가 출력되는 것이 좋을 듯 합니다.

UI 디자인은 **꽃 키우기에서 아이콘을 다 쓰지 않고 나가면 출력되는 몽몽이 UI**를 조금 변형하면 좋을 것 같다고 생각합니다.

![image](https://user-images.githubusercontent.com/40852277/128653199-b4a5c589-730e-4666-96c5-7cf98a45ae75.png)

때문에 몽몽이의 대사와 음성이 필요합니다.

이는 @Yeohyun00 님께 따로 요청드리도록 하겠습니다.

---

다른 의견이나 코멘트 있으면 답글 달아주시길 바랍니다.

**Comment by 2sukhyunlee** [comment]
저는 앱을 종료하지 않는 것이 디폴트라고 생각하여 그렇게 테스트를 했습니다. 
이전에 모아정원을 기획하면서 태블릿에서는 앱이 항상 켜있다는 것을 가정으로 논의했던 것으로 알고 있었는데, 혹시 변경된 지점이 있나요?

그리고 종료 버튼을 만드는 것 자체에는 긍정적이지만 이것을 매일 사용해야 할 필요성과 언제 종료해야 하는 건지 모호한 것 같습니다. 
가끔 앱 사용 중에 에러가 날 때, 화면이동이나 앱 종료 후 재실행 하면 해결되는 경우가 있기 때문에 종료 버튼이 있다면 안드로이드에 익숙하지 않은 사용자에게는 도움이 될 수 있을 것 같습니다. 
하지만 그 외에는 매일 사용할 앱인데 굳이 종료를 해야 할 필요가 없을 것 같습니다. 또, 사용자가 앱을 종료해야 한다면 매일 앱 사용이 끝나면 종료해야 하나요? 아니면 한 차례 사용이 끝나고 화면 잠금 할 타이밍 마다 앱 종료를 해야 하나요?

**Comment by KimYC1223** [comment]
읽고 보니 제가 잘못 생각하고 있었던 것 같습니다.

처음 기획 의도는 앱을 종료하지 않도록 설계하는 것이었었죠,

---

장시간 사용하지 않을 때 앱을 반드시 종료해야 하도록 설계할 것은 아닙니다.

단지 사용자가 종료하고 싶은 경우엔 종료 할 수 있도록 버튼을 만들어 두는게 좋다고 생각했습니다.

**Comment by junhyungmoon** [comment]
@KimYC1223 @2sukhyunlee 
앱을 종료하지 않고 화면만 켰다 껐다 하는 식으로 사용하는 경우(=숙현 학생의 테스트 케이스)에서 문제가 발생했고, 그 것이 앱을 아예 종료했다 다시 켬으로써 해결되는 것처럼 보이길래 그렇다면 사용자도 스스로 앱을 종료할 수 있는 방법은 있어야 하지 않겠냐는 의문을 제기한 것입니다. 그리고 안드로이드 유저가 아닌 부모님들이 실제로 앱을 어떻게 종료할지를 모르시는 걸 보고 나중에 필요할 때 쉽게 버튼 한번 눌러서 종료하면 좋겠다는 생각을 했습니다. 매일 계속 켜놓아도 문제가 없다면 저도 종료 기능은 필수는 아니라고 생각합니다.

**Comment by KimYC1223** [comment]
# 종료 버튼

일단 필요할 것 같아 구현했습니다. 없애자는 의견 있으면 제거하겠습니다.

![image](https://user-images.githubusercontent.com/40852277/128859258-0d903c67-e169-486a-be9b-2b15ce1e6fb7.png)

![image](https://user-images.githubusercontent.com/40852277/128868362-bb1b61b7-46ee-4c1b-8de5-05a7ad89d0c2.png)

몽몽이의 대사는 아래와 같습니다.

- 모아정원을 나갈거야몽?
- 모아정원을 종료할까몽?
- 모아정원을 나갈까몽?
