### ISSUE TITLE
[Question] 하루보기 화면 추가 기능 먹통 현상 (작성 완료)

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#68]
이건 3번 참가자와 튜토리얼 과정에서 발생한 이슈인데, 원인이 짐작이 되지 않습니다.
모든 테스트에서 동일하게 발생하는 다른 버그와 달리 특정 상황/환경에서만 발생하는 것 같은데
혹시 이유가 짐작이 되는지 궁금합니다.

**Comment by KimYC1223** [comment]
제목만 보아서는 어떤 버그인지 잘 감이 잡히지 않습니다.

혹시 어떤 이슈인지 자세히 설명해주실 수 있나요?

**Comment by junhyungmoon** [comment]
아 쓰다 말고 뭘 좀해야해서 제목에 작성 중임 이라고 달았던거고요..ㅎ

어제 밤에 3번 참가자 부모님과 zoom 으로 튜토리얼하면서 저도 직접 본 상황인데요~
설치 하고 나서 정원가기에서 버튼 눌러보면서 상단의 숫자랑 땅 모양이 변하는걸 보여드린 다음에
땅을 눌러서 하루보기 화면으로 이동했습니다.
하루보기에 와서도 버튼 눌러보면서 아이콘이 생기는 것을 같이 해 보았고요~
그 다음에 기록을 새로 추가하려면 상단의 + 버튼을 누르면 된다고 하여 물 버튼을 가지고 따라하셨습니다.
아래와 같이 모든 시간대가 하이라이트 된 후에 특정 시간을 터치하면 원래는 터치한 시간에 아이콘이 바로 생기고 끝나는데,
이상하게도 터치한 그 막대기만 하이라이트 되고 나머지 막대기는 어둠 속으로 들어가고 아이콘은 생기지 않았습니다. 
오줌, 똥, 음료 마찬가지였어요~ 영상을 함부로 녹화할 수 없어서 그 화면 자체를 캡처하진 못했지만
어머님이 카메라로 저한테도 보여주셨고 제가 직접 확인한 현상입니다.

다만, 위에 쓴 것처럼 모든 기기에서 항상 발생하는 공통 버그라기보다 아주 특수한 케이스에 나오는 버그 같네요...
앱을 아예 종료한 뒤에 다시 해보니 되었습니다.

![Screenshot_20210809-162806_MOA GARDEN](https://user-images.githubusercontent.com/8017454/128672386-80dea020-884a-4931-a063-44dadaba26b7.jpg)

**Comment by junhyungmoon** [comment]
이건 위에 제가 리포트한 케이스 후로 어디에서도 발견되지 않았으므로 일단 닫기로 해요
