### ISSUE TITLE
[Question] 모닝콜 동작 안함

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#69]
제가 사용중이던 태블릿을 파일럿 참가자께 드린 후에 며칠간 태블릿이 없어서 잠시 
예전 모델의 태블릿에 모아정원을 설치해서 썼었습니다.
그런데 주말 아침 7시에 알림이 울리더라고요ㅠㅠㅠ

그런데 현재 모델의 태블릿으로 테스트 할 때는 한번도 모닝콜이 울린 적이 없습니다.
이전 모델에서만 울리도록 코드상에 설정된 것이지요?

질문으로만 남깁니다. 모닝콜 기능을 안 넣을 수도 있을 것 같아서요

**Comment by KimYC1223** [comment]
아닙니다. 모닝콜 동작하는 코드는 모두 들어있습니다.

혹시 모닝콜 자체를 disable 한게 아닌가요?

앱을 통해 모닝콜을 만들었는데, 이 모닝콜을 아예 꺼리면 동작하지 않습니다.

![image](https://user-images.githubusercontent.com/40852277/128727407-f8271fd1-9389-420d-9088-bcb45ffc07db.png)

(제가 태블릿이 없어서 가지고있는 아이폰 스크린샷으로 대체합니다)

저는 처음에 자꾸 아침 7시에 울리길래 테스트할때는 모닝콜을 만들자마자 지워버리고있습니다.

다른분들은 어떠신가요? 모닝콜이 울리지 않나요?

@2sukhyunlee @Yeohyun00 @sayiovme @josephhanbin  @sanghyuplee20  @phj00

**Comment by junhyungmoon** [comment]
1. 어제(9일) 처음 모아정원 설치하고 계정 생성한 태블릿PC(A라고 지칭)의 잠금화면입니다. 우측 상단에 알람 아이콘이 없습니다.
DB에서 114번 user 이며 모닝콜을 10시로 설정했었습니다.
![앱에서 모닝콜](https://user-images.githubusercontent.com/8017454/128792971-7198016e-b3e7-4f65-9c4b-1f7e36e90e03.jpg)

2. 시계 어플에서 직접 10시로 알람 설정한 또다른 태블릿PC(B라고 지칭)의 잠금화면입니다. 우측 상단에 알람 아이콘이 있습니다.
![시계앱에서 모닝콜](https://user-images.githubusercontent.com/8017454/128793340-fb84d8fe-1228-48f2-826f-4923b1b4719e.jpg)


3. 10시가 되었을 때 A는 알람이 울리지 않고 B는 알람이 울립니다
![대조](https://user-images.githubusercontent.com/8017454/128793224-d74cfb15-3992-49fd-91c7-a8c389e635b2.jpg)

4. A의 시계 앱에 들어가보니 알람이 10시로 생성되어 있긴 합니다. 제 예상에 내일부터 A도 알람이 울릴 것 같습니다. 왠지 시계 앱에 한번 들어가주어야만 모닝콜이 울리는 게 아닌가 예상하는데, 내일(11일) 리포트 추가하겠습니다.
![앱에서 모닝콜2](https://user-images.githubusercontent.com/8017454/128793298-d96927dc-0b84-4f06-8a0f-41ea9ab3cdcb.jpg)

**Comment by junhyungmoon** [comment]
모닝콜을 일단 제거하였으니 다시 필요해서 살리면 그때 테스트해보고 reopen 하기로 합니다
