### ISSUE TITLE
[Question] App 에서 추가한 기록의 시간 질문

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#70]
아래 빨간 표기한 기록은 사용자가 App 에서 저장한 기록입니다.
저게 9시를 누르면 59분 59초로 지정되는건가요? 
일반적으로 생각해보면 0분 0초를 할 것 같은데, 저렇게 지정해 놓으니 기준이 혹시 다른가 싶어서 질문 남깁니다.

![화면 캡처 2021-08-09 222822](https://user-images.githubusercontent.com/8017454/128713991-cd275381-3665-4648-8631-34ed47d42366.png)

**Comment by KimYC1223** [comment]
아아... 저것은 ```auto```열이 없었을 때,

물이나 오줌 기록을 삭제할 경우 항상 앱에서 추가한 기록이 먼저 삭제되도록 맨 뒤에 추가하기 위해 저렇게 작성한겁니다.

잊고있었네요.. 0분 0초가 자연스러울 것 같으므로 변경 하겠습니다.

**Comment by KimYC1223** [comment]
# 변경점

이제 앱에서 로그를 만들거나 로그의 시간을 변경하면 00분 00초로 변경됩니다.
