### ISSUE TITLE
[Question] 데이터의 시간 정렬

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#71]
현재까지 들어온 데이터 중에서는 108번 데이터에서만 나타난 현상입니다. (107번과 110번은 아님)
사진을 보시면 밴드에서 입력한 데이터인데 8월 9일 밤 시간 데이터가 나오다가 8월 8일 밤 시간 데이터가 나왔다가 다시 8월 9일 오전 데이터가 나옵니다. 다른 데이터는 안 그래서요 혹시나 문제가 있나 싶어서 남겨봅니다.

![화면 캡처 2021-08-09 225101](https://user-images.githubusercontent.com/8017454/128717423-2c119dff-3ba3-4f1c-afc7-434c7154e1c3.png)

**Comment by KimYC1223** [comment]
결론부터 말씀드리자면, 데이터에 문제가 있는 것은 아닙니다.

히스토리 로그를 받아 올 때 한번에 전체를 다 올리는게 아니라, 

로그를 잘라서 업로드하게 되는데 이 과정에서 인터넷 연결이나 서버의 상태에 따라서

처리속도가 다르기 때문에 시간 순서가 섞일 수 있습니다.

![image](https://user-images.githubusercontent.com/40852277/128721338-ba518613-9031-4361-ae79-b845a0ef20b6.png)

DB는 서버가 처리한 순서대로 (인덱스 정렬) 보여주지만,

앱이나 리포트에선 데이터를 시간순서대로 소팅한 후, 보여주기 때문에 생기는 문제입니다.
