### ISSUE TITLE
[Question] 기록 삭제 기능 개선

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#73]
당장 무엇을 하자는 것은 아니고 기록 차원에서 남겨둡니다.

108번 데이터의 일부 화면입니다.
주변 친구들이 너도나도 다 눌러봐서 15분동안 수십개의 데이터가 들어와 있습니다.

![화면 캡처 2021-08-10 102923](https://user-images.githubusercontent.com/8017454/128794953-6429b98e-b144-4799-8537-54a221c87d40.png)

부모님께서 그 사실을 아시고 지우려고 하셨는데, 한번에 1개의 데이터만 지울수 있으니까
그걸 한번에 다 지우기가 어렵다고 하십니다.
한번에 여러개를 지울 수 있도록 하면 좋겠다고 의견을 주셨습니다.

1시간 내에 여러개의 아이콘이 있을 때 꾹 눌러서 쓰레기통을 누른 다음에
1개만 고르는게 아니라 복수 개수로 고르게 해주면 꼭 위와 같이 극단적인 상황은 아니더라도
편리하긴 할 것 같습니다.

**Comment by KimYC1223** [comment]
해당 기능은 제가 구현 할 수 있으나,

삭제하는 UI를 **어떻게 만들어야 하는지 제가 결정하기 어려운 부분**이 있는 것 같습니다.

Figma로 작업하시고 UI 넘겨주시면 제가 작업해서 해당 기능 구현하도록 하겠습니다.

물, 음료, 오줌, 똥별로 UI가 필요합니다.

@2sukhyunlee  @Yeohyun00 @josephhanbin

**Comment by Yeohyun00** [comment]
저의 제안사항입니다.

1. 똥, 음료의 경우

삭제 버튼을 누르면 '제거할 기록을 눌러주세요'라는 팝업이 뜨고 하나만 선택을 할 수 있게 되어있는데,
**복수선택을 지원** 하면 좋을 것 같습니다. 

즉, 현재는 아래 사진처럼 하나를 선택하게만 되어있는데, 
![Screenshot_20210810-112407_MOA GARDEN](https://user-images.githubusercontent.com/77374615/128799108-8deef369-df7a-4e18-8b2a-670d4e57ee5f.jpg)

아래 사진처럼 복수선택이 가능하게 해주어, 2개 이상의 음료나 똥을 한꺼번에 삭제하게 해주면 사용자들이 편리해할 것 같습니다.
![Group 547](https://user-images.githubusercontent.com/77374615/128799467-d8da34fb-e0fa-4759-9bbd-c0507b6abaa1.png)



2. 물, 오줌의 경우

물, 오줌은 똥과 음료처럼 종류, 양, 모양으로 분류가 되어있지 않기 때문에
1번의 복수선택을 적용하면 오히려 사용자들이 혼란스러워할 거라 생각합니다.
그래서 아래 사진처럼 **제거할 수량을 고르도록** 하는 것이 좋을 것 같습니다.
1시간 내 기록이 하나라면 제거할 수량을 고르게 하지 않고 바로 삭제하고,
기록이 2개 이상이라면 제거할 수량을 고르도록 하는 것입니다.

![Group 548](https://user-images.githubusercontent.com/77374615/128799646-6c62fa03-2b8c-47f7-a693-d225bc7bac84.png)

**Comment by junhyungmoon** [comment]
여현학생 아이디어가 좋은것 같습니다.

**Comment by KimYC1223** [comment]
@junhyungmoon 지금봤네요..!

현재 상협학생 @sanghyuplee20 과 함께 본 여현님 아이디어로 작업중입니다!

**Comment by KimYC1223** [comment]
@sanghyuplee20 님과 오늘 중간 점검진행했습니다.

작업 완료되면 여기에 정리해주시길 바랍니다!

**Comment by KimYC1223** [comment]
# 작업 완료

## 물 기록 / 오줌 기록

![water](https://user-images.githubusercontent.com/40852277/130343304-0c49aaff-25d1-4416-b797-2e17cb90a5af.gif)

삭제할 개수를 입력받아 삭제

너무 기록이 많을 경우, 버튼을 여러번 입력해야 할 것 같아 슬라이드도 추가함

## 음료 기록 / 똥 기록

![poo](https://user-images.githubusercontent.com/40852277/130343320-d3eeafbb-3f8d-4c1e-960d-63994b8c75d5.gif)

다중 선택 지원
