### ISSUE TITLE
[BUG] 똥 모양 기록 오류

### ISSUE THREAD

**Issue by josephhanbin** [FluidTrack/MOA_garden#75]
한 시간 사이에 똥을 2번 새로 기록하게 될때 이중 한가지의 모양을 바꿀 경우, 다른 것에도 적용이 됩니다. 기록을 변경할때도 같은 문제가 발생합니다.
![Screenshot_20210810-150829_MOA GARDEN](https://user-images.githubusercontent.com/85919101/128816922-5cde252f-63f2-4adb-9f7c-2c80476267ec.jpg)
![Screenshot_20210810-150840_MOA GARDEN](https://user-images.githubusercontent.com/85919101/128816954-deb04feb-8fa6-47c3-b8e5-d47fc0f5ba84.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

- #73 해결하면서 같이 해결
