### ISSUE TITLE
[BUG] 정원가기 날짜 업데이트 안됨 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#77]
상황: 8월9일 밤 이후로 app 을 계속 사용하지 않고 태블릿 화면만 껐음. 8월 10일 아침부터 밤까지 모아밴드로 버튼 입력만 하였음. 8월 10일 밤에 태블릿 화면을 다시 켜서 자동 연결될 때까지 잠시 대기하였고, 곧 데이터가 모두 업로드 되었음.

문제1. 화요일이 오늘인데 구름이 걷히지 않았음
문제2. 정원을 이리저리 네비게이션 하다가 우측 하단의 새로고침 버튼을 눌렀을 때 화요일이 아닌 월요일이 중심인 view 로 복귀함. 오늘을 월요일로 인식하는 것으로 보임
문제3. 화요일의 모종삽 모양과 화요일 글씨를 눌러도 하루보기로 이동하지 않았음

![Screenshot_20210810-224506_MOA GARDEN](https://user-images.githubusercontent.com/8017454/128880439-b55902d7-b2e7-4e57-992b-8670f972717a.jpg)
![Screenshot_20210810-224543_MOA GARDEN](https://user-images.githubusercontent.com/8017454/128880472-a6067d2b-9b93-4cf9-8710-c9dfcfb95371.jpg)

**Comment by junhyungmoon** [comment]
참고로 이 것은 하루보기를 갔다가 즉시 돌아와서도 해결되지 않았고, 하루보기에 가서 이것저것 눌러보고 꽃 키우기를 하고 나서 돌아오니 자동으로 화요일이 오늘인 상태로 모두 정상화 되어 있었습니다. 걸린 시간은 측정하진 않았습니다.

**Comment by junhyungmoon** [comment]
10일 밤에는 앱을 완전 종료했고, 11일 밤에 새로 켜서 밴드 연동했더니 문제가 없었습니다.
11일 밤에 앱 사용하고 종료하지 않았고, 오늘(12일) 다시 한번 앱을 종료하지 않은 상황에서 테스트 할 예정입니다.

**Comment by junhyungmoon** [comment]
수요일(11일) 밤에 앱을 끄지 않고 오늘(12일) 밤에 켰습니다. 
위 사진처럼 구름에 가려져 있진 않지만 12일을 오늘로 인식하지 않는 듯한 현상은 보입니다.

1) view 의 중심점이 12일 목요일이 아닙니다. (몽몽이 말풍선 잘림, 우측 하단 돌아가기 버튼 누르면 목요일이 중심인 view 로 이동하지 않음)

2) 목요일의 땅에서 글씨와 땅 그림 모두 클릭이 되지 않습니다.

![Screenshot_20210812-213207_MOA GARDEN](https://user-images.githubusercontent.com/8017454/129198655-4f0794ff-a112-4535-b596-19c876d5bf92.jpg)

**Comment by KimYC1223** [comment]
요일이 바뀔때가 자꾸 문제네요... 좀 더 살펴보겠습니다

**Comment by junhyungmoon** [comment]
@KimYC1223 
종료를 했다가 켜면 보정이 되는 문제라서 어쩌면 우선순위가 낮은 버그일 수도 있겠습니다.
문득 생각이 나서 적어요~

그런데 몽몽이 말이 잘리는건 종료했다 켜도 동일하던데, view 가 혹시 설정이 잘못된 것일까요?

**Comment by junhyungmoon** [comment]
12일(목) 앱 종료 안함. 화면만 끔 -> 13일(금) 테스트 -> 14일(토) 아침 화면 켜서 연동완료

view 가 토요일 기준으로 정상적으로 보임. 우측 하단의 돌아가기 아이콘 눌러도 토요일로 정상 이동
BUT, 금요일의 기록이 연동되어 모종삽 모양이 생겼는데, 금요일 글씨와 땅 모두 눌러지지 않음. 다른 모든 요일은 정상적으로 땅이 눌러짐

**Comment by KimYC1223** [comment]
시간을 계산하는 부분에서 문제가 있는 것 같은데,

이번 1.0.9에서 조치를 취해보았습니다.

확인해보고 문제가 없으면 클로즈합니다

**Comment by junhyungmoon** [comment]
1.0.9로 테스트하고 있는데, 화요일(17일)에 켰는데(좌측 상단 동기화 시간 참고) 월요일(16일)이 오늘로 되어 있습니다.
앱을 종료했다가 켜면 화요일 view 로 정상 업데이트 됩니다.

![Screenshot_20210817-231227_MOA GARDEN](https://user-images.githubusercontent.com/8017454/129818343-3e1077ec-2092-4255-b8c2-d28ad27e805e.jpg)

**Comment by junhyungmoon** [comment]
이건 앱 종료해달라고 제가 튜토리얼에서 말씀드릴 것이고, 만약 앱 종료를 하지 않아 view 가 꼬이면 앱 종료 해달라고 다시 안내하면 해결될 것 같습니다. 종료
