### ISSUE TITLE
[Question] 앱 종료 기능의 필요성

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#79]
Screen 로그를 보니 예를 들어 110번 데이터를 보면 한 페이지에 87000초 머물렀다는 기록이 있습니다.
이 것은 저 화면에서 마지막으로 머물렀다가 앱을 종료하지 않고 다음날 다시 켜서 사용했기 때문에 그런 것이 아닌가 예상합니다.

혹시 앱을 종료하지 않고도 태블릿 화면을 꺼버리면 그 시점을 저장할 수 있나요?

그리고 제가 question 으로 달아놓는 것은 당장 고치라는 뜻이 아니라 논의가 필요하여 그렇게 하는 것인데
즉시 고쳐야 하는 것처럼 대응할 필요 없습니다.

**Comment by KimYC1223** [comment]
해당 기능 추가했습니다!

이제 화면이 꺼지는 기간은 카운트하지 않습니다.
