### ISSUE TITLE
[BUG] 모양 기록된 시간 오류

### ISSUE THREAD

**Issue by josephhanbin** [FluidTrack/MOA_garden#80]
하루종일 모아밴드로 기록을 하다가 밤 10시에 앱을 처음으로 열어보니 하루동안 기록한 모양들이 다 밤 10시 기록되어 있습니다.
![Screenshot_20210812-225202_MOA GARDEN](https://user-images.githubusercontent.com/85919101/129209711-f852c139-03db-4b82-881e-0502993acb56.jpg)

**Comment by KimYC1223** [comment]
![image](https://user-images.githubusercontent.com/40852277/129278049-711d37a8-4e29-448d-9005-fca33a67ca66.png)

블루투스 연결이 끊어지지 않은 채로 화면만 꺼져서 아마

**History**가 아닌 **Realtime** 버튼 기록으로  처리된 것 같습니다.

**만약 오후 10시에 연결했으면, 사진의 시간이 오후 10시였을겁니다.**

이슈 내용을 보니, 화면이 꺼져 있을때, Realtime 버튼 로그가 쌓이다가 화면이 켜지면 한번에 기록되는 것 같습니다.

이는 명백한 버그로서, 수정하도록 하겠습니다.

---

The screen turned off without disconnecting the Bluetooth connection,

so it was probably treated as a **Realtime** button history, not a **History**.

**If you connected at 10pm, the time in the picture would be 10pm.**

Looking at the issue, it seems that when the screen is turned off, the Realtime button log is stacked

and then the screen is turned on, it is drew at once.

This is an obvious bug, and I will fix it.

**Comment by junhyungmoon** [comment]
파일럿B 에서도 같은 오류가 나왔습니다. 아래 사진은 어제이고 5일전에도 그랬다고 합니다

![Screenshot_20210814-131021_Messages](https://user-images.githubusercontent.com/8017454/129433616-6d5fbf52-4eaf-4e1a-9b11-6693b699b2db.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

![ezgif-6-b072398771ac](https://user-images.githubusercontent.com/40852277/129440908-117507a7-a2e3-44e2-8cfa-aa690e472896.gif)

이제 화면을 끄거나 Home버튼을 눌러 밖으로 나가면 모아밴드와 연결이 끊어집니다.

---

Now, if you turn off the screen or press the home button, Moaband will be disconnected.
