### ISSUE TITLE
[BUG] 모아밴드 수동 연결 버튼 작동 실패

### ISSUE THREAD

**Issue by josephhanbin** [FluidTrack/MOA_garden#81]
모아밴드가 연결되지 않은 상태에서 다시 연결 시킬려고 하는데 모아밴드 수동 연결 버튼을 눌러도 아무런 현상이 나옵니다. 모아밴드를 충분이 충전을 했는데도 재연결이 아직도 안됩니다. 확인해주시기 바랍니다.

**Comment by KimYC1223** [comment]
어제 한빈님과 개인적으로 연락했는데,

다른 모아밴드로 시도했을 땐 정상적으로 연결이 잘 됐다고 합니다.

정말로 모아밴드가 고장난것인지 확인하기 위해,

한빈님이 제게 고장난 모아밴드를 택배로 전달하여 제가 살펴보는게 좋을 것 같습니다.
