### ISSUE TITLE
[BUG] 크리티컬 - 음료 기록 디스플레이 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#83]
음료 기록은 타임라인 네비게이션을 하면(좌우 버튼과 스와이프 모두 해당) 바로 화면에서 사라져 버립니다.

확인해보니 1.0.9 버전에서는 잘 되었는데, 1.0.10 버전에서만 아래와 같이 되네요...

용량이 너무 커서 링크로..
https://drive.google.com/file/d/1qPb_e5zbgQU45gT-G_Is7ALJi4SK6V9Z/view?usp=sharing
https://drive.google.com/file/d/1iN7CGuhKjN3Sl1ek7VjH2oOqclIPph0x/view?usp=sharing

**Comment by Yeohyun00** [comment]
저도 같은 문제가 있어 댓글남깁니다. 

https://drive.google.com/file/d/1_LeGhARMcta7AlOqSXvJpbjfQeHAedgu/view?usp=sharing

스와이프/좌우클릭을 하다가 기록이 있는 시간대를 넘어가버리면, 
그 시간대에 있는 기록들만 없어져야하는데 모든 음료 기록이 없어집니다. 
반면, 물 기록은 서로 독립되어 서로 영향을 받지 않습니다. 

https://drive.google.com/file/d/12cxCHXoPakUOpqHcWfC5pdOpXsarmemc/view?usp=sharing

추가적으로, 위 영상에서 보시는 것처럼 음료를 기록한 시간이 불일치합니다.
시간 오차의 규칙(예를 들어, 항상 2시간 늦은 시간대로 기록된다든지...)은 보이지 않습니다.

https://drive.google.com/file/d/1gibmnxu04NRajbjXkqQSus1Rak2vHhPw/view?usp=sharing

음료양을 스와이프할 때, 뒤의 타임바도 스와이프되고 있는데, 
이것이 시간 불일치 문제의 원인일지는 잘 모르겠지만, 눈에 보여서 남겨봅니다.
문제의 원인이 아니다하더라도, 음료양 스와이프와 타임바 스와이프는 분리해야하지 않나 생각됩니다.

**Comment by KimYC1223** [comment]
해당 내역은 수정했습니다. 1.0.11 버전으로 업데이트하겠습니다.
