### ISSUE TITLE
[BUG] 서버 데이터 익스포트 에러

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#84]
서버와 달리 파일에는 모든 화면이 정원가기라고만 나옵니다

![image](https://user-images.githubusercontent.com/8017454/130088010-92d44dac-40ad-4d48-abd3-2ca0389f3790.png)

![image](https://user-images.githubusercontent.com/8017454/130087949-20902a9b-9b79-43e6-b127-e68f5c29bb05.png)

**Comment by KimYC1223** [comment]
# 문제해결

사소한 실수로 인해 발생한 문제입니다. 해결하고 서버에 업로드하였습니다.

![image](https://user-images.githubusercontent.com/40852277/130157082-a7bbe6a1-e42a-4aec-a2a2-58cf2b02fed4.png)
