### ISSUE TITLE
[Question] 데이터 timestamp sorting 이슈

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#85]
첨부한 파일을 보시면 오름차순으로 timestamp 를 정렬한 것입니다.
한자리수와 두자리수 간에 혼동으로 인해 정렬이 잘 되지 않습니다.
예를 들어 8월 10일의 로그보다 8월 9일의 로그가 더 나중의 시간으로 정렬됩니다. (파일 상 맨 하단에 존재)
또 다른 예로 8월 9일 안에서도 아침9시의 로그가 저녁 8시의 로그보다 더 나중의 시간으로 정렬됩니다.
혹시 한자리수 날짜나 한자리수 시간일때 0을 붙여 써주면 해결이 될까요?

timestamp 가 모아밴드 앱 상에서 포맷이 정의되는 것이라면 앱 이슈라고 생각하여 여기에 등록합니다.

[WaterLogs_ 한여준.csv](https://github.com/FluidTrack/MOA_garden/files/7026513/WaterLogs_.csv)

**Comment by KimYC1223** [comment]
# 문제 해결

[```MOA_server```](https://github.com/FluidTrack/MOA_server)에서 DB의 timestamp를 가져올 때, 단순히 데이터를 가져오면,

```수 2021-08-25 11:14:39 UTC``` 이런식으로 불필요한 내용도 같이 출력되기 때문에

해당 데이터를 trim해야 합니다.

---

일단 아래는 [```mysqlScript.js```](https://github.com/FluidTrack/MOA_server/blob/main/restApi/mysqlScript.js)의 기존 코드입니다.

```javascript
let dateParse = (timestamp) => {
  let year = timestamp.getFullYear(); // 년도
  let month = timestamp.getMonth() + 1;  // 월
  let date = timestamp.getDate();  // 날짜
  let hours = timestamp.getHours(); // 시
  let minutes = timestamp.getMinutes();  // 분
  let seconds = timestamp.getSeconds();  // 초

  return `${year}-${month}-${date} ${hours}:${minutes}:${seconds}`
}
```

이를 아래와 같이 10의 자리와 1의 자리를 구하는 함수로 변경했습니다.

```javascript
let dateParse = (timestamp) => {
  let year = timestamp.getFullYear(); // 년도
  let month = timestamp.getMonth() + 1;  // 월
  let date = timestamp.getDate();  // 날짜
  let hours = timestamp.getHours(); // 시
  let minutes = timestamp.getMinutes();  // 분
  let seconds = timestamp.getSeconds();  // 초

  return `${year}-${parseInt(month/10)}${month%10}-${parseInt(date/10)}${date%10} `+
         `${parseInt(hours/10)}${hours%10}:${parseInt(minutes/10)}${minutes%10}:${parseInt(seconds/10)}${seconds%10}`
}
```

이제 raw data를 살펴보면, 2자리로 출력됩니다.

![image](https://user-images.githubusercontent.com/40852277/130715587-fbbb6acb-1bce-4691-b05b-50edb7dd2e78.png)
