### ISSUE TITLE
[BUG] 정원가기 몽몽이 위치 조정 필요

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#87]
![Screenshot_20210822-163249_MOA GARDEN](https://user-images.githubusercontent.com/77374615/130382326-845cac17-bd68-4448-be8b-46e4c0bc2d10.jpg)
![Screenshot_20210822-163300_MOA GARDEN](https://user-images.githubusercontent.com/77374615/130382332-b229b513-8ddb-43a5-b00b-73ce899adb23.jpg)

4주차 두번째 날 땅입니다. 몽몽이가 오늘의 땅에서 많이 떨어져있어 화면에서 아예 보이지 않습니다.
몽몽이의 위치를 조금 위로 올려, 오늘의 땅 바로 아래쪽에 위치시켜주시면 좋을 것 같습니다.
감사합니다.

**Comment by KimYC1223** [comment]
# 문제 해결

4주차 몽몽이의 좌표가 ``` { 2212, 698 } ``` 이어야 하는데,

오타로 인해 ``` { 2212, -698 } ``` 로 적용되고 있었습니다.

감사합니다.

**Comment by junhyungmoon** [comment]
혹시 요것도 위치가 맞나 확인차 공유합니다. 

![Screenshot_20210905-112128_MOA GARDEN](https://user-images.githubusercontent.com/8017454/132147787-6cc35345-3880-40ae-8edf-ed1ed236c558.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

버그는 아니었습니다만, 이상한 감이 있네요. 위치 조정했습니다.

![image](https://user-images.githubusercontent.com/40852277/132383101-b25a254f-e860-408d-9e8a-6ca2b8a91701.png)
