### ISSUE TITLE
[Enhancement] 나비 문구 포함 (중요)

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#88]
@KimYC1223 
파일럿을 해보니 일단 부모님, 아동 모두 앱에 대해 너무나 좋아하십니다.
인터뷰하면서 덕분에 뿌듯했습니다. 개발팀 모두에게 감사를~!

예상대로 꽃키우기 화면이 아이들의 '최애' 화면입니다.
여기서 아이들의 흥미를 '정원가기' 화면까지 이어가는 장치로 나온 의견이
물 스티커 10개를 모으면 정원에 나비가 보인다는 사실을 알려달라는 것입니다.

워낙 튜토리얼에서 설명드릴 것이 많다보니 (프린트 메뉴얼로는 29장이네요ㅜ)
제가 말씀드렸음에도 부모님이 나비가 나온다는걸 잊고 계시더라고요~
아이들은 즉각적인걸 좋아하다보니 꽃 다키우면 끝! 이렇게 되고요.
그래서 아래 여현학생에게 부탁을 해 놓을테니 '꽃키우기' 화면에서 10개 꽃을 피우면
정원으로 나비를 확인하러 가자는 말을 추가하려고 합니다.

@Yeohyun00 

나비가 생겼다몽! 나비를 보러 정원으로 가자몽!

제가 예시로 써봤는데 적절한 문구를 녹음 파일과 함께 영찬학생에게 전달 부탁합니다.

**Comment by Yeohyun00** [comment]
멘트들을 아래와 같이 작성하여 음성과 함께 영찬님께 전달했습니다.

- 우와, 정원에 나비가 생겼어! 나비 보러 정원에 같이 가자몽!
- 정원에 나비가 생겼다몽! 나비보러 정원에 가볼까몽?
- 정원에 나비가 나풀나풀 날고 있을거야! 확인해보러 갈까몽?
- 나비가 꽃을 구경하려고 놀러왔대! 정원에 나비 보러 갈까몽?
- 나비가 꽃 위에서 훨훨 날고 있을거야! 나비보러 정원에 갈까몽?

**Comment by KimYC1223** [comment]
# 구현 완료

![image](https://user-images.githubusercontent.com/40852277/130657934-ddf2ef9c-b1d0-442b-bbd7-0bd4407ac750.png)

물을 주고 난 후, 정원에 핀 꽃의 개수가 10송이 미만일 경우엔 기존 멘트가 출력됩니다.

본 멘트는 물을 주고 난 후 꽃이 10송이일 경우에만 출력됩니다.
