### ISSUE TITLE
[REPORT] 부모용 리포트 만들기

### ISSUE THREAD

**Issue by KimYC1223** [FluidTrack/MOA_garden#9]
# 부모가 볼 수 있는 2주간 결과 리포트 만들기

## Web 기반의 2주 경과 페이지 만들기

- Server는 [기존의 database 서버](https://github.com/FluidTrack/MOA_server)인 [fluidtrack.site](http://fluidtrack.site/) 이용
- html,css로 구성하고, javascript로 그래프 구현 ([google chart ](https://developers.google.com/chart)이용 가능성 검토하기)
- DB data fetch는 [기존 CRUD 방식](https://github.com/FluidTrack/MOA_server/blob/main/restApi/routes.js) 그대로 이용함
- fetch할 때는 XMLHHttpRequest 기반의 [Ajax](https://developer.mozilla.org/ko/docs/Web/Guide/AJAX/Getting_Started) 사용
- 데이터 결과는 Json형식으로 가져오게 됨 ([예시](http://fluidtrack.site/read_users))

## 참고 자료

![image](https://user-images.githubusercontent.com/40852277/108392535-28ab4900-7256-11eb-8224-12ce33356d68.png)

본 이미지는 최종본이 아니며, 변경 될 수 있음

**Comment by KimYC1223** [comment]
# 🗃️ Fluid Track Report Auto Template

<img src="https://github.com/FluidTrack/Report/blob/main/DocumentImage/DocImage_01.gif?raw=true">

보고서 템플릿 자동 생성기

### 접속 링크 : [http://fluidtrack.site:8055/](http://fluidtrack.site:8055/)

---

## 관리 Repo

<a href="https://github.com/FluidTrack/Report"><img src="https://github.com/FluidTrack/Report/blob/main/WebSrc/IMG/metaImage.png?raw=true" width="200px"></a>

새로 관련 서버를 만들었음. [FluidTrack/Report](https://github.com/FluidTrack/Report) 레포 참조

**Comment by junhyungmoon** [comment]
오늘(12일, 금) 이봉신 박사님께서 추천해주신 d3js 와 vega-lite 2가지도 한번 살펴봐 주세요~ 반드시 사용해야 한다는 뜻은 아니지만 이봉신 박사님께서는 visualization 전문가이시기 때문에 추천해주신 것을 살펴보면 좋겠다는 말입니다.

**Comment by junhyungmoon** [comment]
원노트의 사용자 스터디 > Field study > 부모용 리포트 페이지 안에 보시면 생성 및 발송 프로토콜 내용이 있습니다. Step1 내용이 프로그래밍 되어야 할 부분입니다.
