### ISSUE TITLE
[BUG] 모아보기 몽몽이 음성

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#90]
모아보기의 몽몽이 음성이 중간에 잘립니다. 
예를 들어, "물을 충분히 마시면 더 건강해져몽!" 라는 멘트를 "물을" 까지만 말합니다.

**Comment by junhyungmoon** [comment]
제 태블릿에서도 그러네요

**Comment by KimYC1223** [comment]
나비 관련 몽몽이를 추가하다가 발생한 문제인것 같습니다.

1.0.13 버전에서 해당 버그 수정하였습니다.
