### ISSUE TITLE
앱 내에서 출현한 버그리포트 화면 리마인드

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#92]
딱히 아무것도 하지 않고 앱을 사용하고 있었는데 팝업으로 버그 리포트가 2번 나왔습니다.
BLE 에러라고 되어있는데 밴드를 태블릿PC 바로 옆에 두고 있었고, 좌측 상단에도 연결됨으로 나옵니다!

첫번째 팝업이 뜨자마자 바로 두번째 팝업으로 넘어가버려서 첫번째껀 못찍었고 아래는 두번째 팝업입니다.
서버로 보내기를 누르긴 했는데 혹시나 하여 남겨둘게요~!

![Screenshot_20210825-201839_MOA GARDEN](https://user-images.githubusercontent.com/8017454/130782016-ebbf7ea8-867e-4699-82d2-2414a611e0d0.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

제가 개발자용 옵션을 켜 놓았는데, 배포할 때 신경을 쓰지 못한것 같습니다.

일단 비활성화 시켜놓았습니다.
