### ISSUE TITLE
[BUG] 모아보기 화면에 데이터가 반영 안되는 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#93]
26일(목),27일(금) 기록만 모았다가 27일(금) 밤에 앱을 켰습니다.
1번 화면을 보시면 26일에 물이 10개 있고, 화면엔 안보이지만 27일에 13개 물이 있습니다. 
2번 화면처럼 모아보기에 26일,27일 각각 10,13이 아니라 둘다 0으로 되어있습니다.
3번 화면은 26일의 꽃을 한번 피워본 것입니다. 그래도 모아보기로 갔을때 여전히 0이었습니다.
앱을 아예 종료했다가 다시 켰더니 4번 화면처럼 정상적으로 보입니다.

제 추측은 다음과 같습니다.
- 모아보기 화면에서 물 섭취량 표기를 꽃의 개수로 나타냄
- 앱이 켜진 상황에서 꽃을 피운 것이 바로 모아보기에서 반영이 안됨

![Screenshot_20210827-221513_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131133744-73804f17-ff0f-4f86-83c4-32009a06aa8e.jpg)
![Screenshot_20210827-221521_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131133766-d95ae3c7-6ea4-4d67-9612-0706c324ae9d.jpg)
![Screenshot_20210827-221540_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131133794-0638eb51-f420-4a8b-aa43-69232d32fc57.jpg)
![Screenshot_20210827-221634_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131133821-efb999c3-698d-47b4-9bc0-b8ec40ef041f.jpg)

**Comment by junhyungmoon** [comment]
오늘(일) 같은 상황을 재현해봤더니 확실해졌네요.
참고로 어제와 오늘 모두 앱을 전날 종료하지 않고 이어서 쓴 것이 아니라 아예 새로 접속했었습니다.

보시면 어제(토) 기록이 있는데 (첫번째 사진) 꽃은 피우지 않은 상태였습니다 (두번째 사진)
모아보기에 보면 토요일 **물 섭취, 소변, 대변 모두 0** 입니다. (세번째 사진)
이 상태에서 꽃을 키워도 모아보기 화면에서 토요일이 업데이트 되지 않았습니다. 

아예 앱을 종료하고 다시 접속해보니 그제야 모아보기에서 토요일에 수치가 맞게 반영됩니다.

![Screenshot_20210829-083421_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131233578-02f7b7c6-8a34-429e-a040-81dfde0ed031.jpg)
![Screenshot_20210829-083436_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131233582-c0745d54-4230-43db-a8ea-1bbab2f49309.jpg)
![Screenshot_20210829-083401_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131233586-6512d475-f55c-4425-84ee-88b0502c71c9.jpg)
![Screenshot_20210829-083454_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131233590-4accbd48-f6c6-4a72-8a4b-ff129260517f.jpg)

**Comment by junhyungmoon** [comment]
#94 <-- 여기에 제가 댓글로 달아놓은 테스트 결과를 토대로 추론해보자면, 모아보기에서 "꽃"의 개수로 물 기록을 보여주는 건 아닌 것 같네요. 다만 꽃을 피워야만 물,오줌,똥 기록 모두가 반영되는 것은 맞는것 같습니다.

**Comment by KimYC1223** [comment]
# 문제 해결

확인해보니 앱에서 추가한 기록들은 문제가 없고, 밴드로 추가한 기록만 이렇게 나오는 것을 확인했습니다.

문제는 기록을 가져와서 timestamp를 만드는 과정에서 발생했습니다.

아래는 [```ProtocolHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/ProtocolHandler.cs)에서,

기록의 data array에서 timestamp를 만드는

```public string MakeTimeStamp(int year, int month, int day, int hour, int min, int sec)```함수입니다.

```C#
public string MakeTimeStamp(int year, int month, int day, int hour, int min, int sec) {
    return year + "-" + month + "-" + day + " " + hour + ":" + min + ":" + sec;
}
```

이 과정에서, **#89 [[BUG]모아보기 버그!!!](https://github.com/FluidTrack/MOA_garden/issues/89#issuecomment-905488187)**  와 같은 버그로 추정됩니다.

**#85 [[Question] 데이터 timestamp sorting 이슈](https://github.com/FluidTrack/MOA_garden/issues/85)**이후로

timestamp는 모두 ```YYYY-MM-DD hh:mm:ss```의 고정된 19자리를 쓰기로 결정하였는데,

이 과정에서 문제가 생긴 것 같습니다.

다만, 데이터를 저장하는 DB는 이 형식에 상관없이 입력받아 저장이 가능했기 때문에,

앱을 종료후 다시 시작했을 땐 데이터를 DB에서 가져와 정상적으로 보여졌던 것입니다.

현재 해당 문제는 아래와 같이 해결하였습니다.

```C#
public string MakeTimeStamp(int year, int month, int day, int hour, int min, int sec) {
    return year + "-" + (month/10) + (month%10) + "-" + (day/10) + (day%10) + " " + 
           (hour/10) + (hour%10) + ":" + (min/10) + (min%10) + ":" + (sec/10) + (sec%10);
}
```
