### ISSUE TITLE
[BUG] 물 모두주기 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#94]
@2sukhyunlee 
숙현학생이 내용 업데이트 해줄겁니다.
오늘 막 발견한 버그인데, 까먹을까봐 제가 이슈 오픈만 했어요~

**Comment by 2sukhyunlee** [comment]
'꽃키우기' 화면에서 [물 모두주기] 버튼을 누른 즉시 해당 버튼이 비활성화 되도록 업데이트 부탁드립니다!

현재는 [물 모두주기] 버튼을 누르면 물 주는 액션이 다 끝난 뒤에야 비활성화됩니다.
물을 주는 동안에 해당 버튼을 여러 번 다시 누를 수 있는데, 그만큼 꽃이 중복되어 피게 됩니다.
(예로, 물 아이콘은 총 6개인데 물 주는 동안 버튼을 다시 누르면 물을 그만큼 다시 줘서 꽃 10개가 핍니다.)

이 버그는 '정원가기', '꽃키우기' 화면의 꽃 개수에 영향을 미칩니다.
'정원가기', '하루보기' 상단에 나타나는 물 개수에는 영향을 미치지 않습니다.

**Comment by ycho98** [comment]
[물 모두주기] 버튼으로 물 주는 액션중에 [물 모두주기] 버튼을 한번 더 누른 후 
소변, 대변 아이콘을 모두 사용하고 나서 돌아가기를 누르면 남아있지 않지만 밑에 그림들이 남아있다고 나옵니다. 

"응 나갈래"를 선택한 뒤 다시 "꽃 키우기"로 돌아오면 아이콘이 남아있거나 돌아가기를 눌렀을때 그림이 남아있다고 나오지는 않습니다.

**Comment by junhyungmoon** [comment]
저도 해보고 사진으로 공유하는게 더 정확할 것 같아서 공유합니다.
1) 물을 3번 기록함
2) "물 모두주기" 누르고 한번 더 누름(아마 물 1개를 준 뒤에 입력이 들어간 것으로 추정됨)
3) 꽃이 총 5개가 핌
4) 나가려고 하자 그림이 남았다는 팝업UI 출현
5) 정원에도 꽃이 5개로 피어있음
6) 앱을 완전 종료 후 복귀해도 "정원가기", "꽃키우기" 화면에는 꽃이 5개이고, "하루보기" 화면에는 물 기록이 3개임. "모아보기"화면에도 물 기록이 3개임 (#93 에 참고).

![Screenshot_20210901-094512_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131594322-017c1790-5274-4baf-bba6-fc33a0c7ec83.jpg)
![Screenshot_20210901-094530_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131594329-6bc80a98-fe73-4ec2-9bdc-76e05e9c84fc.jpg)
![Screenshot_20210901-094543_MOA GARDEN](https://user-images.githubusercontent.com/8017454/131594341-372166fa-df37-4cf1-84e6-7cfd25db886b.jpg)

**Comment by KimYC1223** [comment]
# 문제 해결

[```FlowerPageHandler.cs```](https://github.com/FluidTrack/MOA_garden/blob/master/Assets/Scripts/CanvasHandler/Flower/FlowerPageHandler.cs)의 와 ```public void Watering_all()```와 ```public IEnumerator Watering_all_Routine()```에서,

시작할 때 Button의 ```interactable```값을 ```false```로 변경했지만,

물을 줄 때 마다 정원을 다시 그리는 ```IEnumerator ReDrawSpot()```에서

조건을 다시 판단하여 버튼을 활성화 하는 것을 발견했습니다.

```C#
IEnumerator ReDrawSpot() {
    // 중략
    WateringAllButton.interactable = waterIconCount > 0;
    // 후략
}
```

따라서, ```private bool wateringAllButtonClicked```라는 변수를 추가하고,

모두주기 버튼을 누를 때엔 값을 ```true```로 바꿔주는 기능을 추가했습니다.

그리고 문제가 되었던 ```IEnumerator ReDrawSpot()```에서는

```wateringAllButtonClicked```값이 ```false```일 때에만

```WateringAllButton```의 ```interactable```값을  변경하도록 하였습니다.

```C#
IEnumerator ReDrawSpot() {
    // 중략
    if(!wateringAllButtonClicked)
        WateringAllButton.interactable = waterIconCount > 0;
    // 후략
}
```

![ezgif-6-d1293bd1ebb4](https://user-images.githubusercontent.com/40852277/131624096-34a1ebd9-0a73-4f38-8c5c-0508cabba189.gif)

또한 나머지 이슈는 물 모두 주기 버튼을 연속으로 눌렀을 때에만

발생하는 것임을 확인하였기 때문에,

이렇게 수정함으로써 해결하였습니다.

감사합니다.
