### ISSUE TITLE
[Enhancement] 꽃을 먼저 피워달라는 몽몽이의 말을 듣고 꽃키우기 화면을 나갈 때

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#95]
꽃 키우기에서 꽃이 없는 상황에서 오줌이나 똥 아이콘을 사용하려고 할 때 몽몽이가 '꽃을 먼저 피워줘'라고 말합니다. 
그리고 '돌아가기' 버튼을 누르면 밑의 아이콘을 다 사용하지 않았으므로 '밑에 그림들이 있는데 갈거야?'라는 메세지가 뜹니다.
꽃을 먼저 피워달라는 것을 듣고 빠져나가려는데, '아이콘이 남아있는데 왜 가냐'는 메세지를 보면 사용자들이 뭘 해야할지 혼란스러워할 수 있을 것 같습니다. 
꽃을 먼저 피워달라는 메세지가 뜰 경우, '돌아가기' 버튼을 누르면 바로 꽃키우기 화면을 빠져나올 수 있도록 하는 게 좋을 것 같습니다.

**Comment by KimYC1223** [comment]
# 문제 해결

구현하고자 하는 상황을 정리해보면 다음과 같습니다.

종료 버튼을 눌렀을 때, 모아 정원상태에 따른 나갈거냐는 몽몽이의 출현조건은

| 번호 | 물 아이콘이 | 꽃이 | 오줌/똥 아이콘이 | 그럼 몽몽이가... |
|:-----:|:-------------:|:-----:|:--------------------:|:------------------:|
| 1 | X | X | X | 안나옴 |
| 2 | X | X | O | **안나옴** |
| 3 | X | O | X | 안나옴 |
| 4 | X | O | O | 나옴 |
| 5 | O | X | X |  나옴 |
| 6 | O | X | O | 나옴 |
| 7 | O | O | X | 나옴 |
| 8 | O | O | O | 나옴 |

입니다.

현재는 **전체 아이콘의 개수가 0이 아니면 출현**하므로, "2번"상황의 경우

이슈에 적어주신대로 몽몽이가 출현하고 있습니다.

따라서, 조건을 바꿔 **전체 아이콘의 개수가 0이 아니거나,** (1,3번 조건)

**물아이콘과 꽃이 없고 (똥 기록 + 오줌 기록)의 개수가 1이상 이면** (2번 조건)출현하도록 바꾸겠습니다.

말이 복잡한데 잘 생각해보면 당연한 소리입니다.

## 수정 전

```C#
public void BackButtonClicked() {
    if (!isTouchAble) return;
    if (iconCount == 0) BackButtonRealActive();
    else {
        AlertWindow.SetActive(true);
        SoundHandler.Instance.Play_SFX(SoundHandler.SFX.ERROR);
    }
}
```

## 수정 후

```C#
public void BackButtonClicked() {
    if (!isTouchAble) return;
    if (iconCount == 0 || 
        ( waterIconCount == 0 && FlowerCount == 0 && (pooIconCount + peeIconCount > 0) ) ) 
        BackButtonRealActive();
    else {
        AlertWindow.SetActive(true);
        SoundHandler.Instance.Play_SFX(SoundHandler.SFX.ERROR);
    }
}
```
