### ISSUE TITLE
[BUG] 똥 기록 시 간헐적으로 꽃키우기 버튼에 빨간점 비출현 및 꽃키우기 화면에 아이콘 없음

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/MOA_garden#96]
![Screenshot_20210831-220710_MOA GARDEN](https://user-images.githubusercontent.com/77374615/131531952-cbf39ade-ebf3-4667-9501-b21b7a0c5b58.jpg)
![Screenshot_20210831-221252_MOA GARDEN](https://user-images.githubusercontent.com/77374615/131531959-6bbd99b8-980f-46fd-8112-9cf4b6ff122f.jpg)

똥 기록을 할 때 간헐적으로(10번 중에 3-4번은 그런 것 같습니다.) 꽃 키우기 버튼에 빨간점이 나타나지 않고,
꽃 키우기 화면에 들어가보면 똥 아이콘이 뜨지 않습니다. 
앱으로 추가할 때, 모아밴드로 추가할 때 마찬가지입니다.

**Comment by KimYC1223** [comment]
# 문제 해결

[**```SelectPooHandler.cs```**](https://github.com/FluidTrack/MOA_garden/blob/161074a8acb1a1b1555e31cc74e17f1fef53459d/Assets/Scripts/CanvasHandler/Popups/SelectPooHandler.cs#L179)에 오타가 있었네요.

```C#
if (TargetGardenLog.log_poop > 0) TargetGardenLog.log_poop =- realClickedIconIndex.Count;
```

이럴 경우 원래 값에서 빼는게 아니라 Count * -1 값이 들어가네요.

아래와 같이 수정했습니다.

```C#
if (TargetGardenLog.log_poop > 0) TargetGardenLog.log_poop -= realClickedIconIndex.Count;
```

참조 : @sanghyuplee20
