### ISSUE TITLE
[BUG] 종료 버튼을 누르면 버그리포트 팝업 출현

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/MOA_garden#99]
팝업이 뜬 상태에서 바로 앱이 종료되어 버려서 캡처는 하지 못했습니다 (3회 시도 모두 동일)

**Comment by junhyungmoon** [comment]
@KimYC1223 
이 버그가 혹시 누락된건가 싶어서 리마인드해요~
주말에 튜토리얼 할때도 이거 왜나오냐고 물어보셨습니다.

**Comment by KimYC1223** [comment]
# 문제 해결

안드로이드 유니티 프로젝트에서 앱을 종료하는 코드를 검색해보니

```C#
Application.Quit();
System.Diagnostics.Process.GetCurrentProcess().Kill();
```

라는 코드로 종료할 수 있었습니다만,

```System.Diagnostics.Process.GetCurrentProcess().Kill();```에서 문제가 있었던 것 같습니다.

1.0.17 버전에서는 문제를 해결하였습니다.
